[
    "y/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inump\n             y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-bro\n             adwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/in\n             clude/python3.8 -c'\n     864     gcc: _configtest.c\n865     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     866         3 | #pragma clang diagnostic error \"-Wattributes\"\n     867           |\n     868     _configtest.c: In function '__declspec':\n  >> 869     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'",
    "870         5 | int __declspec(thread) foo;\n     871           |                        ^~~\n  >> 872     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     873         9 | {\n     874           | ^\n875     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     876         5 | int __declspec(thread) foo;\n     877           |     ^~~~~~~~~~\n  >> 878     _configtest.c:11: error: expected '{' at end of input\n     879        11 | }\n     880           |",
    "implicit-int]\n     876         5 | int __declspec(thread) foo;\n     877           |     ^~~~~~~~~~\n  >> 878     _configtest.c:11: error: expected '{' at end of input\n     879        11 | }\n     880           |\n881     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     882        11 | }\n     883           |\n     884     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     885         3 | #pragma clang diagnostic error \"-Wattributes\"",
    "879        11 | }\n     880           |\n     881     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     882        11 | }\n     883           |\n884     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     885         3 | #pragma clang diagnostic error \"-Wattributes\"\n     886           |\n     887     _configtest.c: In function '__declspec':\n  >> 888     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'",
    "889         5 | int __declspec(thread) foo;\n     890           |                        ^~~\n  >> 891     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     892         9 | {\n     893           | ^\n894     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     895         5 | int __declspec(thread) foo;\n     896           |     ^~~~~~~~~~\n  >> 897     _configtest.c:11: error: expected '{' at end of input\n     898        11 | }\n     899           |",
    "implicit-int]\n     895         5 | int __declspec(thread) foo;\n     896           |     ^~~~~~~~~~\n  >> 897     _configtest.c:11: error: expected '{' at end of input\n     898        11 | }\n     899           |\n900     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     901        11 | }\n     902           |\n     903     failure.\n\n     ...",
    "z56muf3y24twbgptm5fwkbrmdx/lib/python3.8/site-packages/setuptools/\n             command/install.py:34: SetuptoolsDeprecationWarning: setup.py inst\n             all is deprecated. Use build and pip and other standards-based too\n             ls.\n     4083      warnings.warn(\n     4084    numpy/random/mtrand/mtrand.c: In function 'PyInit_mtrand':\n4085    numpy/random/mtrand/mtrand.c:43644:3: warning: 'tp_print' is depre\n             cated [-Wdeprecated-declarations]\n     4086    43644 |   __pyx_type_6mtrand_RandomState.tp_print = 0;\n     4087          |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n     4088    In file included from /p/vast1/koparasy/BUILD/spack_cluster_instal\n             ler/quartz/nrm/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/pytho\n             n-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/include/python3.8/object",
    "st.o -o _configtest\n     110     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 111     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.0-bjwoovoeupz3\n             xnm5u73gfnwjiee7k2sm/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 112     collect2: error: ld returned 1 exit status\n     113     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 114     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.0-bjwoovoeupz3\n             xnm5u73gfnwjiee7k2sm/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 115     collect2: error: ld returned 1 exit status",
    ">> 112     collect2: error: ld returned 1 exit status\n     113     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 114     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.0-bjwoovoeupz3\n             xnm5u73gfnwjiee7k2sm/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 115     collect2: error: ld returned 1 exit status\n     116     failure.\n     117     removing: _configtest.c _configtest.o\n     118     C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     119",
    "y/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inump\n             y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-bro\n             adwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/in\n             clude/python3.8 -c'\n     168     gcc: _configtest.c\n>> 169     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory\n     170         1 | #include <sys/endian.h>\n     171           |          ^~~~~~~~~~~~~~\n     172     compilation terminated.\n  >> 173     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory",
    "168     gcc: _configtest.c\n  >> 169     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory\n     170         1 | #include <sys/endian.h>\n     171           |          ^~~~~~~~~~~~~~\n     172     compilation terminated.\n>> 173     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory\n     174         1 | #include <sys/endian.h>\n     175           |          ^~~~~~~~~~~~~~\n     176     compilation terminated.\n     177     failure.\n     178     removing: _configtest.c _configtest.o",
    "y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-bro\n             adwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/in\n             clude/python3.8 -c'\n     284     gcc: _configtest.c\n     285     _configtest.c: In function 'main':\n>> 286     _configtest.c:7:12: error: 'SIZEOF_LONGDOUBLE' undeclared (first u\n             se in this function); did you mean 'SIZEOF_LONG_DOUBLE'?\n     287         7 |     (void) SIZEOF_LONGDOUBLE;\n     288           |            ^~~~~~~~~~~~~~~~~\n     289           |            SIZEOF_LONG_DOUBLE\n     290     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "287         7 |     (void) SIZEOF_LONGDOUBLE;\n     288           |            ^~~~~~~~~~~~~~~~~\n     289           |            SIZEOF_LONG_DOUBLE\n     290     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in\n     291     _configtest.c: In function 'main':\n>> 292     _configtest.c:7:12: error: 'SIZEOF_LONGDOUBLE' undeclared (first u\n             se in this function); did you mean 'SIZEOF_LONG_DOUBLE'?\n     293         7 |     (void) SIZEOF_LONGDOUBLE;\n     294           |            ^~~~~~~~~~~~~~~~~\n     295           |            SIZEOF_LONG_DOUBLE\n     296     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "st.o -o _configtest\n     430     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 431     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.0-bjwoovoeupz3\n             xnm5u73gfnwjiee7k2sm/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 432     collect2: error: ld returned 1 exit status\n     433     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 434     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.0-bjwoovoeupz3\n             xnm5u73gfnwjiee7k2sm/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 435     collect2: error: ld returned 1 exit status",
    ">> 432     collect2: error: ld returned 1 exit status\n     433     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 434     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.0-bjwoovoeupz3\n             xnm5u73gfnwjiee7k2sm/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 435     collect2: error: ld returned 1 exit status\n     436     failure.\n     437     removing: _configtest.c _configtest.o\n     438     C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     439",
    "864     gcc: _configtest.c\n     865     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     866         3 | #pragma clang diagnostic error \"-Wattributes\"\n     867           |\n     868     _configtest.c: In function '__declspec':\n>> 869     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     870         5 | int __declspec(thread) foo;\n     871           |                        ^~~\n  >> 872     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     873         9 | {",
    "867           |\n     868     _configtest.c: In function '__declspec':\n  >> 869     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     870         5 | int __declspec(thread) foo;\n     871           |                        ^~~\n>> 872     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     873         9 | {\n     874           | ^\n     875     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     876         5 | int __declspec(thread) foo;",
    "873         9 | {\n     874           | ^\n     875     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     876         5 | int __declspec(thread) foo;\n     877           |     ^~~~~~~~~~\n>> 878     _configtest.c:11: error: expected '{' at end of input\n     879        11 | }\n     880           |\n     881     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     882        11 | }\n     883           |",
    "883           |\n     884     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     885         3 | #pragma clang diagnostic error \"-Wattributes\"\n     886           |\n     887     _configtest.c: In function '__declspec':\n>> 888     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     889         5 | int __declspec(thread) foo;\n     890           |                        ^~~\n  >> 891     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     892         9 | {",
    "886           |\n     887     _configtest.c: In function '__declspec':\n  >> 888     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     889         5 | int __declspec(thread) foo;\n     890           |                        ^~~\n>> 891     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     892         9 | {\n     893           | ^\n     894     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     895         5 | int __declspec(thread) foo;",
    "892         9 | {\n     893           | ^\n     894     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     895         5 | int __declspec(thread) foo;\n     896           |     ^~~~~~~~~~\n>> 897     _configtest.c:11: error: expected '{' at end of input\n     898        11 | }\n     899           |\n     900     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     901        11 | }\n     902           |",
    "y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-bro\n             adwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/in\n             clude/python3.8 -c'\n     1230    gcc: _configtest.c\n     1231    _configtest.c: In function 'main':\n>> 1232    _configtest.c:8:12: error: 'HAVE_DECL_SIGNBIT' undeclared (first u\n             se in this function); did you mean 'HAVE_DECL_ISNAN'?\n     1233        8 |     (void) HAVE_DECL_SIGNBIT;\n     1234          |            ^~~~~~~~~~~~~~~~~\n     1235          |            HAVE_DECL_ISNAN\n     1236    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "1233        8 |     (void) HAVE_DECL_SIGNBIT;\n     1234          |            ^~~~~~~~~~~~~~~~~\n     1235          |            HAVE_DECL_ISNAN\n     1236    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in\n     1237    _configtest.c: In function 'main':\n>> 1238    _configtest.c:8:12: error: 'HAVE_DECL_SIGNBIT' undeclared (first u\n             se in this function); did you mean 'HAVE_DECL_ISNAN'?\n     1239        8 |     (void) HAVE_DECL_SIGNBIT;\n     1240          |            ^~~~~~~~~~~~~~~~~\n     1241          |            HAVE_DECL_ISNAN\n     1242    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "st.o -o _configtest\n     1824    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1825    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.0-bjwoovoeupz3\n             xnm5u73gfnwjiee7k2sm/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 1826    collect2: error: ld returned 1 exit status\n     1827    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1828    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.0-bjwoovoeupz3\n             xnm5u73gfnwjiee7k2sm/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 1829    collect2: error: ld returned 1 exit status",
    ">> 1826    collect2: error: ld returned 1 exit status\n     1827    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1828    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.0-bjwoovoeupz3\n             xnm5u73gfnwjiee7k2sm/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 1829    collect2: error: ld returned 1 exit status\n     1830    failure.\n     1831    removing: _configtest.c _configtest.o\n     1832    C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     1833",
    "nidc7o5wtbfqu64d3ld/include/python3.8/cpython/object.h:260:30: not\n             e: declared here\n     4012      260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *,\n              int);\n     4013          |                              ^~~~~~~~\n     4014    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionSave':\n>> 4015    numpy/random/mtrand/mtrand.c:45472:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4016    45472 |     *type = tstate->exc_type;\n     4017          |                     ^~~~~~~~\n     4018          |                     curexc_type\n  >> 4019    numpy/random/mtrand/mtrand.c:45473:22: error: 'PyThreadState' {aka",
    ">> 4015    numpy/random/mtrand/mtrand.c:45472:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4016    45472 |     *type = tstate->exc_type;\n     4017          |                     ^~~~~~~~\n     4018          |                     curexc_type\n>> 4019    numpy/random/mtrand/mtrand.c:45473:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4020    45473 |     *value = tstate->exc_value;\n     4021          |                      ^~~~~~~~~\n     4022          |                      curexc_value\n  >> 4023    numpy/random/mtrand/mtrand.c:45474:19: error: 'PyThreadState' {aka",
    ">> 4019    numpy/random/mtrand/mtrand.c:45473:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4020    45473 |     *value = tstate->exc_value;\n     4021          |                      ^~~~~~~~~\n     4022          |                      curexc_value\n>> 4023    numpy/random/mtrand/mtrand.c:45474:19: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4024    45474 |     *tb = tstate->exc_traceback;\n     4025          |                   ^~~~~~~~~~~~~\n     4026          |                   curexc_traceback\n     4027    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4024    45474 |     *tb = tstate->exc_traceback;\n     4025          |                   ^~~~~~~~~~~~~\n     4026          |                   curexc_traceback\n     4027    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':\n>> 4028    numpy/random/mtrand/mtrand.c:45481:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4029    45481 |     tmp_type = tstate->exc_type;\n     4030          |                        ^~~~~~~~\n     4031          |                        curexc_type\n  >> 4032    numpy/random/mtrand/mtrand.c:45482:25: error: 'PyThreadState' {aka",
    ">> 4028    numpy/random/mtrand/mtrand.c:45481:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4029    45481 |     tmp_type = tstate->exc_type;\n     4030          |                        ^~~~~~~~\n     4031          |                        curexc_type\n>> 4032    numpy/random/mtrand/mtrand.c:45482:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4033    45482 |     tmp_value = tstate->exc_value;\n     4034          |                         ^~~~~~~~~\n     4035          |                         curexc_value\n  >> 4036    numpy/random/mtrand/mtrand.c:45483:22: error: 'PyThreadState' {aka",
    ">> 4032    numpy/random/mtrand/mtrand.c:45482:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4033    45482 |     tmp_value = tstate->exc_value;\n     4034          |                         ^~~~~~~~~\n     4035          |                         curexc_value\n>> 4036    numpy/random/mtrand/mtrand.c:45483:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4037    45483 |     tmp_tb = tstate->exc_traceback;\n     4038          |                      ^~~~~~~~~~~~~\n     4039          |                      curexc_traceback\n  >> 4040    numpy/random/mtrand/mtrand.c:45484:13: error: 'PyThreadState' {aka",
    ">> 4036    numpy/random/mtrand/mtrand.c:45483:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4037    45483 |     tmp_tb = tstate->exc_traceback;\n     4038          |                      ^~~~~~~~~~~~~\n     4039          |                      curexc_traceback\n>> 4040    numpy/random/mtrand/mtrand.c:45484:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4041    45484 |     tstate->exc_type = type;\n     4042          |             ^~~~~~~~\n     4043          |             curexc_type\n  >> 4044    numpy/random/mtrand/mtrand.c:45485:13: error: 'PyThreadState' {aka",
    ">> 4040    numpy/random/mtrand/mtrand.c:45484:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4041    45484 |     tstate->exc_type = type;\n     4042          |             ^~~~~~~~\n     4043          |             curexc_type\n>> 4044    numpy/random/mtrand/mtrand.c:45485:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4045    45485 |     tstate->exc_value = value;\n     4046          |             ^~~~~~~~~\n     4047          |             curexc_value\n  >> 4048    numpy/random/mtrand/mtrand.c:45486:13: error: 'PyThreadState' {aka",
    ">> 4044    numpy/random/mtrand/mtrand.c:45485:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4045    45485 |     tstate->exc_value = value;\n     4046          |             ^~~~~~~~~\n     4047          |             curexc_value\n>> 4048    numpy/random/mtrand/mtrand.c:45486:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4049    45486 |     tstate->exc_traceback = tb;\n     4050          |             ^~~~~~~~~~~~~\n     4051          |             curexc_traceback\n     4052    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4049    45486 |     tstate->exc_traceback = tb;\n     4050          |             ^~~~~~~~~~~~~\n     4051          |             curexc_traceback\n     4052    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':\n>> 4053    numpy/random/mtrand/mtrand.c:45541:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4054    45541 |     tmp_type = tstate->exc_type;\n     4055          |                        ^~~~~~~~\n     4056          |                        curexc_type\n  >> 4057    numpy/random/mtrand/mtrand.c:45542:25: error: 'PyThreadState' {aka",
    ">> 4053    numpy/random/mtrand/mtrand.c:45541:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4054    45541 |     tmp_type = tstate->exc_type;\n     4055          |                        ^~~~~~~~\n     4056          |                        curexc_type\n>> 4057    numpy/random/mtrand/mtrand.c:45542:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4058    45542 |     tmp_value = tstate->exc_value;\n     4059          |                         ^~~~~~~~~\n     4060          |                         curexc_value\n  >> 4061    numpy/random/mtrand/mtrand.c:45543:22: error: 'PyThreadState' {aka",
    ">> 4057    numpy/random/mtrand/mtrand.c:45542:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4058    45542 |     tmp_value = tstate->exc_value;\n     4059          |                         ^~~~~~~~~\n     4060          |                         curexc_value\n>> 4061    numpy/random/mtrand/mtrand.c:45543:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4062    45543 |     tmp_tb = tstate->exc_traceback;\n     4063          |                      ^~~~~~~~~~~~~\n     4064          |                      curexc_traceback\n  >> 4065    numpy/random/mtrand/mtrand.c:45544:13: error: 'PyThreadState' {aka",
    ">> 4061    numpy/random/mtrand/mtrand.c:45543:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4062    45543 |     tmp_tb = tstate->exc_traceback;\n     4063          |                      ^~~~~~~~~~~~~\n     4064          |                      curexc_traceback\n>> 4065    numpy/random/mtrand/mtrand.c:45544:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4066    45544 |     tstate->exc_type = local_type;\n     4067          |             ^~~~~~~~\n     4068          |             curexc_type\n  >> 4069    numpy/random/mtrand/mtrand.c:45545:13: error: 'PyThreadState' {aka",
    ">> 4065    numpy/random/mtrand/mtrand.c:45544:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4066    45544 |     tstate->exc_type = local_type;\n     4067          |             ^~~~~~~~\n     4068          |             curexc_type\n>> 4069    numpy/random/mtrand/mtrand.c:45545:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4070    45545 |     tstate->exc_value = local_value;\n     4071          |             ^~~~~~~~~\n     4072          |             curexc_value\n  >> 4073    numpy/random/mtrand/mtrand.c:45546:13: error: 'PyThreadState' {aka",
    ">> 4069    numpy/random/mtrand/mtrand.c:45545:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4070    45545 |     tstate->exc_value = local_value;\n     4071          |             ^~~~~~~~~\n     4072          |             curexc_value\n>> 4073    numpy/random/mtrand/mtrand.c:45546:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4074    45546 |     tstate->exc_traceback = local_tb;\n     4075          |             ^~~~~~~~~~~~~\n     4076          |             curexc_traceback\n     4077    Running from numpy source directory.",
    "nidc7o5wtbfqu64d3ld/include/python3.8/cpython/object.h:260:30: not\n             e: declared here\n     4093      260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *,\n              int);\n     4094          |                              ^~~~~~~~\n     4095    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionSave':\n>> 4096    numpy/random/mtrand/mtrand.c:45472:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4097    45472 |     *type = tstate->exc_type;\n     4098          |                     ^~~~~~~~\n     4099          |                     curexc_type\n  >> 4100    numpy/random/mtrand/mtrand.c:45473:22: error: 'PyThreadState' {aka",
    ">> 4096    numpy/random/mtrand/mtrand.c:45472:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4097    45472 |     *type = tstate->exc_type;\n     4098          |                     ^~~~~~~~\n     4099          |                     curexc_type\n>> 4100    numpy/random/mtrand/mtrand.c:45473:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4101    45473 |     *value = tstate->exc_value;\n     4102          |                      ^~~~~~~~~\n     4103          |                      curexc_value\n  >> 4104    numpy/random/mtrand/mtrand.c:45474:19: error: 'PyThreadState' {aka",
    ">> 4100    numpy/random/mtrand/mtrand.c:45473:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4101    45473 |     *value = tstate->exc_value;\n     4102          |                      ^~~~~~~~~\n     4103          |                      curexc_value\n>> 4104    numpy/random/mtrand/mtrand.c:45474:19: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4105    45474 |     *tb = tstate->exc_traceback;\n     4106          |                   ^~~~~~~~~~~~~\n     4107          |                   curexc_traceback\n     4108    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4105    45474 |     *tb = tstate->exc_traceback;\n     4106          |                   ^~~~~~~~~~~~~\n     4107          |                   curexc_traceback\n     4108    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':\n>> 4109    numpy/random/mtrand/mtrand.c:45481:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4110    45481 |     tmp_type = tstate->exc_type;\n     4111          |                        ^~~~~~~~\n     4112          |                        curexc_type\n  >> 4113    numpy/random/mtrand/mtrand.c:45482:25: error: 'PyThreadState' {aka",
    ">> 4109    numpy/random/mtrand/mtrand.c:45481:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4110    45481 |     tmp_type = tstate->exc_type;\n     4111          |                        ^~~~~~~~\n     4112          |                        curexc_type\n>> 4113    numpy/random/mtrand/mtrand.c:45482:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4114    45482 |     tmp_value = tstate->exc_value;\n     4115          |                         ^~~~~~~~~\n     4116          |                         curexc_value\n  >> 4117    numpy/random/mtrand/mtrand.c:45483:22: error: 'PyThreadState' {aka",
    ">> 4113    numpy/random/mtrand/mtrand.c:45482:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4114    45482 |     tmp_value = tstate->exc_value;\n     4115          |                         ^~~~~~~~~\n     4116          |                         curexc_value\n>> 4117    numpy/random/mtrand/mtrand.c:45483:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4118    45483 |     tmp_tb = tstate->exc_traceback;\n     4119          |                      ^~~~~~~~~~~~~\n     4120          |                      curexc_traceback\n  >> 4121    numpy/random/mtrand/mtrand.c:45484:13: error: 'PyThreadState' {aka",
    ">> 4117    numpy/random/mtrand/mtrand.c:45483:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4118    45483 |     tmp_tb = tstate->exc_traceback;\n     4119          |                      ^~~~~~~~~~~~~\n     4120          |                      curexc_traceback\n>> 4121    numpy/random/mtrand/mtrand.c:45484:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4122    45484 |     tstate->exc_type = type;\n     4123          |             ^~~~~~~~\n     4124          |             curexc_type\n  >> 4125    numpy/random/mtrand/mtrand.c:45485:13: error: 'PyThreadState' {aka",
    ">> 4121    numpy/random/mtrand/mtrand.c:45484:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4122    45484 |     tstate->exc_type = type;\n     4123          |             ^~~~~~~~\n     4124          |             curexc_type\n>> 4125    numpy/random/mtrand/mtrand.c:45485:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4126    45485 |     tstate->exc_value = value;\n     4127          |             ^~~~~~~~~\n     4128          |             curexc_value\n  >> 4129    numpy/random/mtrand/mtrand.c:45486:13: error: 'PyThreadState' {aka",
    ">> 4125    numpy/random/mtrand/mtrand.c:45485:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4126    45485 |     tstate->exc_value = value;\n     4127          |             ^~~~~~~~~\n     4128          |             curexc_value\n>> 4129    numpy/random/mtrand/mtrand.c:45486:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4130    45486 |     tstate->exc_traceback = tb;\n     4131          |             ^~~~~~~~~~~~~\n     4132          |             curexc_traceback\n     4133    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4130    45486 |     tstate->exc_traceback = tb;\n     4131          |             ^~~~~~~~~~~~~\n     4132          |             curexc_traceback\n     4133    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':\n>> 4134    numpy/random/mtrand/mtrand.c:45541:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4135    45541 |     tmp_type = tstate->exc_type;\n     4136          |                        ^~~~~~~~\n     4137          |                        curexc_type\n  >> 4138    numpy/random/mtrand/mtrand.c:45542:25: error: 'PyThreadState' {aka",
    ">> 4134    numpy/random/mtrand/mtrand.c:45541:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4135    45541 |     tmp_type = tstate->exc_type;\n     4136          |                        ^~~~~~~~\n     4137          |                        curexc_type\n>> 4138    numpy/random/mtrand/mtrand.c:45542:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4139    45542 |     tmp_value = tstate->exc_value;\n     4140          |                         ^~~~~~~~~\n     4141          |                         curexc_value\n  >> 4142    numpy/random/mtrand/mtrand.c:45543:22: error: 'PyThreadState' {aka",
    ">> 4138    numpy/random/mtrand/mtrand.c:45542:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4139    45542 |     tmp_value = tstate->exc_value;\n     4140          |                         ^~~~~~~~~\n     4141          |                         curexc_value\n>> 4142    numpy/random/mtrand/mtrand.c:45543:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4143    45543 |     tmp_tb = tstate->exc_traceback;\n     4144          |                      ^~~~~~~~~~~~~\n     4145          |                      curexc_traceback\n  >> 4146    numpy/random/mtrand/mtrand.c:45544:13: error: 'PyThreadState' {aka",
    ">> 4142    numpy/random/mtrand/mtrand.c:45543:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4143    45543 |     tmp_tb = tstate->exc_traceback;\n     4144          |                      ^~~~~~~~~~~~~\n     4145          |                      curexc_traceback\n>> 4146    numpy/random/mtrand/mtrand.c:45544:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4147    45544 |     tstate->exc_type = local_type;\n     4148          |             ^~~~~~~~\n     4149          |             curexc_type\n  >> 4150    numpy/random/mtrand/mtrand.c:45545:13: error: 'PyThreadState' {aka",
    ">> 4146    numpy/random/mtrand/mtrand.c:45544:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4147    45544 |     tstate->exc_type = local_type;\n     4148          |             ^~~~~~~~\n     4149          |             curexc_type\n>> 4150    numpy/random/mtrand/mtrand.c:45545:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4151    45545 |     tstate->exc_value = local_value;\n     4152          |             ^~~~~~~~~\n     4153          |             curexc_value\n  >> 4154    numpy/random/mtrand/mtrand.c:45546:13: error: 'PyThreadState' {aka",
    ">> 4150    numpy/random/mtrand/mtrand.c:45545:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4151    45545 |     tstate->exc_value = local_value;\n     4152          |             ^~~~~~~~~\n     4153          |             curexc_value\n>> 4154    numpy/random/mtrand/mtrand.c:45546:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4155    45546 |     tstate->exc_traceback = local_tb;\n     4156          |             ^~~~~~~~~~~~~\n     4157          |             curexc_traceback\n  >> 4158    error: Command \"/p/vast1/koparasy/BUILD/head/spack/lib/spack/env/g"
]