[
    "==> [2022-01-10-11:24:20.898172] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/legion/legion-stable.tar.gz\n==> [2022-01-10-11:24:20.898438] Cloning git repository: https://github.com/StanfordLegion/legion.git on branch stable\n==> [2022-01-10-11:24:20.899926] '/usr/tce/bin/git' '--version'\n==> [2022-01-10-11:24:20.906385] '/usr/tce/bin/git' '-c' 'advice.detachedHead=false' '--version'\n==> [2022-01-10-11:24:20.912039] '/usr/tce/bin/git' '-c' 'advice.detachedHead=false' '--version'\n==> [2022-01-10-11:24:20.917497] '/usr/tce/bin/git' '-c' 'advice.detachedHead=false' 'clone' '--branch' 'stable' '--single-branch' '--depth' '1' 'https://github.com/StanfordLegion/legion.git'\n==> [2022-01-10-11:24:24.982960] Error: Error: Destination path '/var/tmp/koparasy/spack-stage/spack-stage-legion-stable-wizcv527pbdr32fkhuwtkzi5blpbwmao/spack-src/legion' already exists\n\n/p/vast1/koparasy/BUILD/head/spack/lib/spack/spack/package.py:1386, in do_fetch:\n       1383\n       1384        self.stage.create()\n       1385        err_msg = None if not self.manual_download else self.download_instr\n  >>   1386        start_time = time.time()",
    "self.clone(commit=self.commit, branch=self.branch, tag=self.tag)\n  File \"/p/vast1/koparasy/BUILD/head/spack/lib/spack/spack/fetch_strategy.py\", line 982, in clone\n    shutil.move(repo_name, dest)\n  File \"/usr/tce/packages/python/python-3.7.2/lib/python3.7/shutil.py\", line 561, in move\n    raise Error(\"Destination path '%s' already exists\" % real_dst)\nshutil.Error: Destination path '/var/tmp/koparasy/spack-stage/spack-stage-legion-stable-wizcv527pbdr32fkhuwtkzi5blpbwmao/spack-src/legion' already exists\n==> [2022-01-10-11:24:24.983408] Flagging legion-stable-2pnpotwgctwd3amvu5yafhk6yglsbuwe as failed: Error: Destination path '/var/tmp/koparasy/spack-stage/spack-stage-legion-stable-wizcv527pbdr32fkhuwtkzi5blpbwmao/spack-src/legion' already exists\n==> [2022-01-10-11:24:25.383406] Skip view update, this environment does not maintain a view\n==> [2022-01-10-11:24:25.385163] ChildError: Error: Destination path '/var/tmp/koparasy/spack-stage/spack-stage-legion-stable-wizcv527pbdr32fkhuwtkzi5blpbwmao/spack-src/legion' already exists",
    "shutil.move(repo_name, dest)\n  File \"/usr/tce/packages/python/python-3.7.2/lib/python3.7/shutil.py\", line 561, in move\n    raise Error(\"Destination path '%s' already exists\" % real_dst)\nshutil.Error: Destination path '/var/tmp/koparasy/spack-stage/spack-stage-legion-stable-wizcv527pbdr32fkhuwtkzi5blpbwmao/spack-src/legion' already exists\n==> [2022-01-10-11:24:24.983408] Flagging legion-stable-2pnpotwgctwd3amvu5yafhk6yglsbuwe as failed: Error: Destination path '/var/tmp/koparasy/spack-stage/spack-stage-legion-stable-wizcv527pbdr32fkhuwtkzi5blpbwmao/spack-src/legion' already exists\n==> [2022-01-10-11:24:25.383406] Skip view update, this environment does not maintain a view\n==> [2022-01-10-11:24:25.385163] ChildError: Error: Destination path '/var/tmp/koparasy/spack-stage/spack-stage-legion-stable-wizcv527pbdr32fkhuwtkzi5blpbwmao/spack-src/legion' already exists"
]