[
    "y/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inump\n             y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-bro\n             adwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/in\n             clude/python3.8 -c'\n     764     gcc: _configtest.c\n765     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     766         3 | #pragma clang diagnostic error \"-Wattributes\"\n     767           |\n     768     _configtest.c: In function '__declspec':\n  >> 769     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'",
    "770         5 | int __declspec(thread) foo;\n     771           |                        ^~~\n  >> 772     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     773         9 | {\n     774           | ^\n775     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     776         5 | int __declspec(thread) foo;\n     777           |     ^~~~~~~~~~\n  >> 778     _configtest.c:11: error: expected '{' at end of input\n     779        11 | }\n     780           |",
    "implicit-int]\n     776         5 | int __declspec(thread) foo;\n     777           |     ^~~~~~~~~~\n  >> 778     _configtest.c:11: error: expected '{' at end of input\n     779        11 | }\n     780           |\n781     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     782        11 | }\n     783           |\n     784     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     785         3 | #pragma clang diagnostic error \"-Wattributes\"",
    "779        11 | }\n     780           |\n     781     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     782        11 | }\n     783           |\n784     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     785         3 | #pragma clang diagnostic error \"-Wattributes\"\n     786           |\n     787     _configtest.c: In function '__declspec':\n  >> 788     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'",
    "789         5 | int __declspec(thread) foo;\n     790           |                        ^~~\n  >> 791     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     792         9 | {\n     793           | ^\n794     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     795         5 | int __declspec(thread) foo;\n     796           |     ^~~~~~~~~~\n  >> 797     _configtest.c:11: error: expected '{' at end of input\n     798        11 | }\n     799           |",
    "implicit-int]\n     795         5 | int __declspec(thread) foo;\n     796           |     ^~~~~~~~~~\n  >> 797     _configtest.c:11: error: expected '{' at end of input\n     798        11 | }\n     799           |\n800     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     801        11 | }\n     802           |\n     803     failure.\n\n     ...",
    "z56muf3y24twbgptm5fwkbrmdx/lib/python3.8/site-packages/setuptools/\n             command/install.py:34: SetuptoolsDeprecationWarning: setup.py inst\n             all is deprecated. Use build and pip and other standards-based too\n             ls.\n     3998      warnings.warn(\n     3999    numpy/random/mtrand/mtrand.c: In function 'PyInit_mtrand':\n4000    numpy/random/mtrand/mtrand.c:41024:3: warning: 'tp_print' is depre\n             cated [-Wdeprecated-declarations]\n     4001    41024 |   __pyx_type_6mtrand_RandomState.tp_print = 0;\n     4002          |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n     4003    In file included from /p/vast1/koparasy/BUILD/spack_cluster_instal\n             ler/quartz/nrm/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/pytho\n             n-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/include/python3.8/object",
    "st.o -o _configtest\n     90      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 91      /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.11.3-xjtpuwifds6r\n             hwtpmt3z6ov5d73tn3oz/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 92      collect2: error: ld returned 1 exit status\n     93      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 94      /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.11.3-xjtpuwifds6r\n             hwtpmt3z6ov5d73tn3oz/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 95      collect2: error: ld returned 1 exit status",
    ">> 92      collect2: error: ld returned 1 exit status\n     93      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 94      /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.11.3-xjtpuwifds6r\n             hwtpmt3z6ov5d73tn3oz/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 95      collect2: error: ld returned 1 exit status\n     96      failure.\n     97      removing: _configtest.c _configtest.o\n     98      C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     99",
    "y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-bro\n             adwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/in\n             clude/python3.8 -c'\n     248     gcc: _configtest.c\n     249     _configtest.c: In function 'main':\n>> 250     _configtest.c:7:12: error: 'SIZEOF_LONGDOUBLE' undeclared (first u\n             se in this function); did you mean 'SIZEOF_LONG_DOUBLE'?\n     251         7 |     (void) SIZEOF_LONGDOUBLE;\n     252           |            ^~~~~~~~~~~~~~~~~\n     253           |            SIZEOF_LONG_DOUBLE\n     254     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "251         7 |     (void) SIZEOF_LONGDOUBLE;\n     252           |            ^~~~~~~~~~~~~~~~~\n     253           |            SIZEOF_LONG_DOUBLE\n     254     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in\n     255     _configtest.c: In function 'main':\n>> 256     _configtest.c:7:12: error: 'SIZEOF_LONGDOUBLE' undeclared (first u\n             se in this function); did you mean 'SIZEOF_LONG_DOUBLE'?\n     257         7 |     (void) SIZEOF_LONGDOUBLE;\n     258           |            ^~~~~~~~~~~~~~~~~\n     259           |            SIZEOF_LONG_DOUBLE\n     260     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "st.o -o _configtest\n     394     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 395     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.11.3-xjtpuwifds6r\n             hwtpmt3z6ov5d73tn3oz/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 396     collect2: error: ld returned 1 exit status\n     397     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 398     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.11.3-xjtpuwifds6r\n             hwtpmt3z6ov5d73tn3oz/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 399     collect2: error: ld returned 1 exit status",
    ">> 396     collect2: error: ld returned 1 exit status\n     397     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 398     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.11.3-xjtpuwifds6r\n             hwtpmt3z6ov5d73tn3oz/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 399     collect2: error: ld returned 1 exit status\n     400     failure.\n     401     removing: _configtest.c _configtest.o\n     402     C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     403",
    "764     gcc: _configtest.c\n     765     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     766         3 | #pragma clang diagnostic error \"-Wattributes\"\n     767           |\n     768     _configtest.c: In function '__declspec':\n>> 769     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     770         5 | int __declspec(thread) foo;\n     771           |                        ^~~\n  >> 772     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     773         9 | {",
    "767           |\n     768     _configtest.c: In function '__declspec':\n  >> 769     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     770         5 | int __declspec(thread) foo;\n     771           |                        ^~~\n>> 772     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     773         9 | {\n     774           | ^\n     775     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     776         5 | int __declspec(thread) foo;",
    "773         9 | {\n     774           | ^\n     775     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     776         5 | int __declspec(thread) foo;\n     777           |     ^~~~~~~~~~\n>> 778     _configtest.c:11: error: expected '{' at end of input\n     779        11 | }\n     780           |\n     781     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     782        11 | }\n     783           |",
    "783           |\n     784     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     785         3 | #pragma clang diagnostic error \"-Wattributes\"\n     786           |\n     787     _configtest.c: In function '__declspec':\n>> 788     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     789         5 | int __declspec(thread) foo;\n     790           |                        ^~~\n  >> 791     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     792         9 | {",
    "786           |\n     787     _configtest.c: In function '__declspec':\n  >> 788     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     789         5 | int __declspec(thread) foo;\n     790           |                        ^~~\n>> 791     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     792         9 | {\n     793           | ^\n     794     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     795         5 | int __declspec(thread) foo;",
    "792         9 | {\n     793           | ^\n     794     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     795         5 | int __declspec(thread) foo;\n     796           |     ^~~~~~~~~~\n>> 797     _configtest.c:11: error: expected '{' at end of input\n     798        11 | }\n     799           |\n     800     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     801        11 | }\n     802           |",
    "y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-bro\n             adwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/in\n             clude/python3.8 -c'\n     1130    gcc: _configtest.c\n     1131    _configtest.c: In function 'main':\n>> 1132    _configtest.c:8:12: error: 'HAVE_DECL_SIGNBIT' undeclared (first u\n             se in this function); did you mean 'HAVE_DECL_ISNAN'?\n     1133        8 |     (void) HAVE_DECL_SIGNBIT;\n     1134          |            ^~~~~~~~~~~~~~~~~\n     1135          |            HAVE_DECL_ISNAN\n     1136    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "1133        8 |     (void) HAVE_DECL_SIGNBIT;\n     1134          |            ^~~~~~~~~~~~~~~~~\n     1135          |            HAVE_DECL_ISNAN\n     1136    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in\n     1137    _configtest.c: In function 'main':\n>> 1138    _configtest.c:8:12: error: 'HAVE_DECL_SIGNBIT' undeclared (first u\n             se in this function); did you mean 'HAVE_DECL_ISNAN'?\n     1139        8 |     (void) HAVE_DECL_SIGNBIT;\n     1140          |            ^~~~~~~~~~~~~~~~~\n     1141          |            HAVE_DECL_ISNAN\n     1142    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "st.o -o _configtest\n     1720    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1721    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.11.3-xjtpuwifds6r\n             hwtpmt3z6ov5d73tn3oz/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 1722    collect2: error: ld returned 1 exit status\n     1723    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1724    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.11.3-xjtpuwifds6r\n             hwtpmt3z6ov5d73tn3oz/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 1725    collect2: error: ld returned 1 exit status",
    ">> 1722    collect2: error: ld returned 1 exit status\n     1723    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1724    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.11.3-xjtpuwifds6r\n             hwtpmt3z6ov5d73tn3oz/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 1725    collect2: error: ld returned 1 exit status\n     1726    failure.\n     1727    removing: _configtest.c _configtest.o\n     1728    C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     1729",
    "e: declared here\n     3923      260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *,\n              int);\n     3924          |                              ^~~~~~~~\n     3925    numpy/random/mtrand/mtrand.c: In function '__Pyx_PyCFunction_FastC\n             all':\n>> 3926    numpy/random/mtrand/mtrand.c:42611:13: error: too many arguments t\n             o function '(PyObject * (*)(PyObject *, PyObject * const*, Py_ssiz\n             e_t))meth'\n     3927    42611 |     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, n\n             args, NULL);\n     3928          |            ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n     3929    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionSave':",
    "o function '(PyObject * (*)(PyObject *, PyObject * const*, Py_ssiz\n             e_t))meth'\n     3927    42611 |     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, n\n             args, NULL);\n     3928          |            ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n     3929    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionSave':\n>> 3930    numpy/random/mtrand/mtrand.c:43052:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3931    43052 |     *type = tstate->exc_type;\n     3932          |                     ^~~~~~~~\n     3933          |                     curexc_type\n  >> 3934    numpy/random/mtrand/mtrand.c:43053:22: error: 'PyThreadState' {aka",
    ">> 3930    numpy/random/mtrand/mtrand.c:43052:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3931    43052 |     *type = tstate->exc_type;\n     3932          |                     ^~~~~~~~\n     3933          |                     curexc_type\n>> 3934    numpy/random/mtrand/mtrand.c:43053:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3935    43053 |     *value = tstate->exc_value;\n     3936          |                      ^~~~~~~~~\n     3937          |                      curexc_value\n  >> 3938    numpy/random/mtrand/mtrand.c:43054:19: error: 'PyThreadState' {aka",
    ">> 3934    numpy/random/mtrand/mtrand.c:43053:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3935    43053 |     *value = tstate->exc_value;\n     3936          |                      ^~~~~~~~~\n     3937          |                      curexc_value\n>> 3938    numpy/random/mtrand/mtrand.c:43054:19: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3939    43054 |     *tb = tstate->exc_traceback;\n     3940          |                   ^~~~~~~~~~~~~\n     3941          |                   curexc_traceback\n     3942    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3939    43054 |     *tb = tstate->exc_traceback;\n     3940          |                   ^~~~~~~~~~~~~\n     3941          |                   curexc_traceback\n     3942    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':\n>> 3943    numpy/random/mtrand/mtrand.c:43061:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3944    43061 |     tmp_type = tstate->exc_type;\n     3945          |                        ^~~~~~~~\n     3946          |                        curexc_type\n  >> 3947    numpy/random/mtrand/mtrand.c:43062:25: error: 'PyThreadState' {aka",
    ">> 3943    numpy/random/mtrand/mtrand.c:43061:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3944    43061 |     tmp_type = tstate->exc_type;\n     3945          |                        ^~~~~~~~\n     3946          |                        curexc_type\n>> 3947    numpy/random/mtrand/mtrand.c:43062:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3948    43062 |     tmp_value = tstate->exc_value;\n     3949          |                         ^~~~~~~~~\n     3950          |                         curexc_value\n  >> 3951    numpy/random/mtrand/mtrand.c:43063:22: error: 'PyThreadState' {aka",
    ">> 3947    numpy/random/mtrand/mtrand.c:43062:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3948    43062 |     tmp_value = tstate->exc_value;\n     3949          |                         ^~~~~~~~~\n     3950          |                         curexc_value\n>> 3951    numpy/random/mtrand/mtrand.c:43063:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3952    43063 |     tmp_tb = tstate->exc_traceback;\n     3953          |                      ^~~~~~~~~~~~~\n     3954          |                      curexc_traceback\n  >> 3955    numpy/random/mtrand/mtrand.c:43064:13: error: 'PyThreadState' {aka",
    ">> 3951    numpy/random/mtrand/mtrand.c:43063:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3952    43063 |     tmp_tb = tstate->exc_traceback;\n     3953          |                      ^~~~~~~~~~~~~\n     3954          |                      curexc_traceback\n>> 3955    numpy/random/mtrand/mtrand.c:43064:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3956    43064 |     tstate->exc_type = type;\n     3957          |             ^~~~~~~~\n     3958          |             curexc_type\n  >> 3959    numpy/random/mtrand/mtrand.c:43065:13: error: 'PyThreadState' {aka",
    ">> 3955    numpy/random/mtrand/mtrand.c:43064:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3956    43064 |     tstate->exc_type = type;\n     3957          |             ^~~~~~~~\n     3958          |             curexc_type\n>> 3959    numpy/random/mtrand/mtrand.c:43065:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3960    43065 |     tstate->exc_value = value;\n     3961          |             ^~~~~~~~~\n     3962          |             curexc_value\n  >> 3963    numpy/random/mtrand/mtrand.c:43066:13: error: 'PyThreadState' {aka",
    ">> 3959    numpy/random/mtrand/mtrand.c:43065:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3960    43065 |     tstate->exc_value = value;\n     3961          |             ^~~~~~~~~\n     3962          |             curexc_value\n>> 3963    numpy/random/mtrand/mtrand.c:43066:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3964    43066 |     tstate->exc_traceback = tb;\n     3965          |             ^~~~~~~~~~~~~\n     3966          |             curexc_traceback\n     3967    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3964    43066 |     tstate->exc_traceback = tb;\n     3965          |             ^~~~~~~~~~~~~\n     3966          |             curexc_traceback\n     3967    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':\n>> 3968    numpy/random/mtrand/mtrand.c:43121:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3969    43121 |     tmp_type = tstate->exc_type;\n     3970          |                        ^~~~~~~~\n     3971          |                        curexc_type\n  >> 3972    numpy/random/mtrand/mtrand.c:43122:25: error: 'PyThreadState' {aka",
    ">> 3968    numpy/random/mtrand/mtrand.c:43121:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3969    43121 |     tmp_type = tstate->exc_type;\n     3970          |                        ^~~~~~~~\n     3971          |                        curexc_type\n>> 3972    numpy/random/mtrand/mtrand.c:43122:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3973    43122 |     tmp_value = tstate->exc_value;\n     3974          |                         ^~~~~~~~~\n     3975          |                         curexc_value\n  >> 3976    numpy/random/mtrand/mtrand.c:43123:22: error: 'PyThreadState' {aka",
    ">> 3972    numpy/random/mtrand/mtrand.c:43122:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3973    43122 |     tmp_value = tstate->exc_value;\n     3974          |                         ^~~~~~~~~\n     3975          |                         curexc_value\n>> 3976    numpy/random/mtrand/mtrand.c:43123:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3977    43123 |     tmp_tb = tstate->exc_traceback;\n     3978          |                      ^~~~~~~~~~~~~\n     3979          |                      curexc_traceback\n  >> 3980    numpy/random/mtrand/mtrand.c:43124:13: error: 'PyThreadState' {aka",
    ">> 3976    numpy/random/mtrand/mtrand.c:43123:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3977    43123 |     tmp_tb = tstate->exc_traceback;\n     3978          |                      ^~~~~~~~~~~~~\n     3979          |                      curexc_traceback\n>> 3980    numpy/random/mtrand/mtrand.c:43124:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3981    43124 |     tstate->exc_type = local_type;\n     3982          |             ^~~~~~~~\n     3983          |             curexc_type\n  >> 3984    numpy/random/mtrand/mtrand.c:43125:13: error: 'PyThreadState' {aka",
    ">> 3980    numpy/random/mtrand/mtrand.c:43124:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3981    43124 |     tstate->exc_type = local_type;\n     3982          |             ^~~~~~~~\n     3983          |             curexc_type\n>> 3984    numpy/random/mtrand/mtrand.c:43125:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3985    43125 |     tstate->exc_value = local_value;\n     3986          |             ^~~~~~~~~\n     3987          |             curexc_value\n  >> 3988    numpy/random/mtrand/mtrand.c:43126:13: error: 'PyThreadState' {aka",
    ">> 3984    numpy/random/mtrand/mtrand.c:43125:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3985    43125 |     tstate->exc_value = local_value;\n     3986          |             ^~~~~~~~~\n     3987          |             curexc_value\n>> 3988    numpy/random/mtrand/mtrand.c:43126:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3989    43126 |     tstate->exc_traceback = local_tb;\n     3990          |             ^~~~~~~~~~~~~\n     3991          |             curexc_traceback\n     3992    Running from numpy source directory.",
    "e: declared here\n     4008      260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *,\n              int);\n     4009          |                              ^~~~~~~~\n     4010    numpy/random/mtrand/mtrand.c: In function '__Pyx_PyCFunction_FastC\n             all':\n>> 4011    numpy/random/mtrand/mtrand.c:42611:13: error: too many arguments t\n             o function '(PyObject * (*)(PyObject *, PyObject * const*, Py_ssiz\n             e_t))meth'\n     4012    42611 |     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, n\n             args, NULL);\n     4013          |            ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n     4014    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionSave':",
    "o function '(PyObject * (*)(PyObject *, PyObject * const*, Py_ssiz\n             e_t))meth'\n     4012    42611 |     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, n\n             args, NULL);\n     4013          |            ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n     4014    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionSave':\n>> 4015    numpy/random/mtrand/mtrand.c:43052:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4016    43052 |     *type = tstate->exc_type;\n     4017          |                     ^~~~~~~~\n     4018          |                     curexc_type\n  >> 4019    numpy/random/mtrand/mtrand.c:43053:22: error: 'PyThreadState' {aka",
    ">> 4015    numpy/random/mtrand/mtrand.c:43052:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4016    43052 |     *type = tstate->exc_type;\n     4017          |                     ^~~~~~~~\n     4018          |                     curexc_type\n>> 4019    numpy/random/mtrand/mtrand.c:43053:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4020    43053 |     *value = tstate->exc_value;\n     4021          |                      ^~~~~~~~~\n     4022          |                      curexc_value\n  >> 4023    numpy/random/mtrand/mtrand.c:43054:19: error: 'PyThreadState' {aka",
    ">> 4019    numpy/random/mtrand/mtrand.c:43053:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4020    43053 |     *value = tstate->exc_value;\n     4021          |                      ^~~~~~~~~\n     4022          |                      curexc_value\n>> 4023    numpy/random/mtrand/mtrand.c:43054:19: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4024    43054 |     *tb = tstate->exc_traceback;\n     4025          |                   ^~~~~~~~~~~~~\n     4026          |                   curexc_traceback\n     4027    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4024    43054 |     *tb = tstate->exc_traceback;\n     4025          |                   ^~~~~~~~~~~~~\n     4026          |                   curexc_traceback\n     4027    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':\n>> 4028    numpy/random/mtrand/mtrand.c:43061:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4029    43061 |     tmp_type = tstate->exc_type;\n     4030          |                        ^~~~~~~~\n     4031          |                        curexc_type\n  >> 4032    numpy/random/mtrand/mtrand.c:43062:25: error: 'PyThreadState' {aka",
    ">> 4028    numpy/random/mtrand/mtrand.c:43061:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4029    43061 |     tmp_type = tstate->exc_type;\n     4030          |                        ^~~~~~~~\n     4031          |                        curexc_type\n>> 4032    numpy/random/mtrand/mtrand.c:43062:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4033    43062 |     tmp_value = tstate->exc_value;\n     4034          |                         ^~~~~~~~~\n     4035          |                         curexc_value\n  >> 4036    numpy/random/mtrand/mtrand.c:43063:22: error: 'PyThreadState' {aka",
    ">> 4032    numpy/random/mtrand/mtrand.c:43062:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4033    43062 |     tmp_value = tstate->exc_value;\n     4034          |                         ^~~~~~~~~\n     4035          |                         curexc_value\n>> 4036    numpy/random/mtrand/mtrand.c:43063:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4037    43063 |     tmp_tb = tstate->exc_traceback;\n     4038          |                      ^~~~~~~~~~~~~\n     4039          |                      curexc_traceback\n  >> 4040    numpy/random/mtrand/mtrand.c:43064:13: error: 'PyThreadState' {aka",
    ">> 4036    numpy/random/mtrand/mtrand.c:43063:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4037    43063 |     tmp_tb = tstate->exc_traceback;\n     4038          |                      ^~~~~~~~~~~~~\n     4039          |                      curexc_traceback\n>> 4040    numpy/random/mtrand/mtrand.c:43064:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4041    43064 |     tstate->exc_type = type;\n     4042          |             ^~~~~~~~\n     4043          |             curexc_type\n  >> 4044    numpy/random/mtrand/mtrand.c:43065:13: error: 'PyThreadState' {aka",
    ">> 4040    numpy/random/mtrand/mtrand.c:43064:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4041    43064 |     tstate->exc_type = type;\n     4042          |             ^~~~~~~~\n     4043          |             curexc_type\n>> 4044    numpy/random/mtrand/mtrand.c:43065:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4045    43065 |     tstate->exc_value = value;\n     4046          |             ^~~~~~~~~\n     4047          |             curexc_value\n  >> 4048    numpy/random/mtrand/mtrand.c:43066:13: error: 'PyThreadState' {aka",
    ">> 4044    numpy/random/mtrand/mtrand.c:43065:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4045    43065 |     tstate->exc_value = value;\n     4046          |             ^~~~~~~~~\n     4047          |             curexc_value\n>> 4048    numpy/random/mtrand/mtrand.c:43066:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4049    43066 |     tstate->exc_traceback = tb;\n     4050          |             ^~~~~~~~~~~~~\n     4051          |             curexc_traceback\n     4052    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4049    43066 |     tstate->exc_traceback = tb;\n     4050          |             ^~~~~~~~~~~~~\n     4051          |             curexc_traceback\n     4052    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':\n>> 4053    numpy/random/mtrand/mtrand.c:43121:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4054    43121 |     tmp_type = tstate->exc_type;\n     4055          |                        ^~~~~~~~\n     4056          |                        curexc_type\n  >> 4057    numpy/random/mtrand/mtrand.c:43122:25: error: 'PyThreadState' {aka",
    ">> 4053    numpy/random/mtrand/mtrand.c:43121:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4054    43121 |     tmp_type = tstate->exc_type;\n     4055          |                        ^~~~~~~~\n     4056          |                        curexc_type\n>> 4057    numpy/random/mtrand/mtrand.c:43122:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4058    43122 |     tmp_value = tstate->exc_value;\n     4059          |                         ^~~~~~~~~\n     4060          |                         curexc_value\n  >> 4061    numpy/random/mtrand/mtrand.c:43123:22: error: 'PyThreadState' {aka",
    ">> 4057    numpy/random/mtrand/mtrand.c:43122:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4058    43122 |     tmp_value = tstate->exc_value;\n     4059          |                         ^~~~~~~~~\n     4060          |                         curexc_value\n>> 4061    numpy/random/mtrand/mtrand.c:43123:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4062    43123 |     tmp_tb = tstate->exc_traceback;\n     4063          |                      ^~~~~~~~~~~~~\n     4064          |                      curexc_traceback\n  >> 4065    numpy/random/mtrand/mtrand.c:43124:13: error: 'PyThreadState' {aka",
    ">> 4061    numpy/random/mtrand/mtrand.c:43123:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4062    43123 |     tmp_tb = tstate->exc_traceback;\n     4063          |                      ^~~~~~~~~~~~~\n     4064          |                      curexc_traceback\n>> 4065    numpy/random/mtrand/mtrand.c:43124:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4066    43124 |     tstate->exc_type = local_type;\n     4067          |             ^~~~~~~~\n     4068          |             curexc_type\n  >> 4069    numpy/random/mtrand/mtrand.c:43125:13: error: 'PyThreadState' {aka",
    ">> 4065    numpy/random/mtrand/mtrand.c:43124:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4066    43124 |     tstate->exc_type = local_type;\n     4067          |             ^~~~~~~~\n     4068          |             curexc_type\n>> 4069    numpy/random/mtrand/mtrand.c:43125:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4070    43125 |     tstate->exc_value = local_value;\n     4071          |             ^~~~~~~~~\n     4072          |             curexc_value\n  >> 4073    numpy/random/mtrand/mtrand.c:43126:13: error: 'PyThreadState' {aka",
    ">> 4069    numpy/random/mtrand/mtrand.c:43125:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4070    43125 |     tstate->exc_value = local_value;\n     4071          |             ^~~~~~~~~\n     4072          |             curexc_value\n>> 4073    numpy/random/mtrand/mtrand.c:43126:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4074    43126 |     tstate->exc_traceback = local_tb;\n     4075          |             ^~~~~~~~~~~~~\n     4076          |             curexc_traceback\n  >> 4077    error: Command \"/p/vast1/koparasy/BUILD/head/spack/lib/spack/env/g"
]