[
    "y/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inump\n             y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-bro\n             adwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/in\n             clude/python3.8 -c'\n     764     gcc: _configtest.c\n765     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     766         3 | #pragma clang diagnostic error \"-Wattributes\"\n     767           |\n     768     _configtest.c: In function '__declspec':\n  >> 769     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'",
    "770         5 | int __declspec(thread) foo;\n     771           |                        ^~~\n  >> 772     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     773         9 | {\n     774           | ^\n775     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     776         5 | int __declspec(thread) foo;\n     777           |     ^~~~~~~~~~\n  >> 778     _configtest.c:11: error: expected '{' at end of input\n     779        11 | }\n     780           |",
    "implicit-int]\n     776         5 | int __declspec(thread) foo;\n     777           |     ^~~~~~~~~~\n  >> 778     _configtest.c:11: error: expected '{' at end of input\n     779        11 | }\n     780           |\n781     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     782        11 | }\n     783           |\n     784     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     785         3 | #pragma clang diagnostic error \"-Wattributes\"",
    "779        11 | }\n     780           |\n     781     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     782        11 | }\n     783           |\n784     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     785         3 | #pragma clang diagnostic error \"-Wattributes\"\n     786           |\n     787     _configtest.c: In function '__declspec':\n  >> 788     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'",
    "789         5 | int __declspec(thread) foo;\n     790           |                        ^~~\n  >> 791     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     792         9 | {\n     793           | ^\n794     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     795         5 | int __declspec(thread) foo;\n     796           |     ^~~~~~~~~~\n  >> 797     _configtest.c:11: error: expected '{' at end of input\n     798        11 | }\n     799           |",
    "implicit-int]\n     795         5 | int __declspec(thread) foo;\n     796           |     ^~~~~~~~~~\n  >> 797     _configtest.c:11: error: expected '{' at end of input\n     798        11 | }\n     799           |\n800     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     801        11 | }\n     802           |\n     803     failure.\n\n     ...",
    "z56muf3y24twbgptm5fwkbrmdx/lib/python3.8/site-packages/setuptools/\n             command/install.py:34: SetuptoolsDeprecationWarning: setup.py inst\n             all is deprecated. Use build and pip and other standards-based too\n             ls.\n     3993      warnings.warn(\n     3994    numpy/random/mtrand/mtrand.c: In function 'PyInit_mtrand':\n3995    numpy/random/mtrand/mtrand.c:37726:3: warning: 'tp_print' is depre\n             cated [-Wdeprecated-declarations]\n     3996    37726 |   __pyx_type_6mtrand_RandomState.tp_print = 0;\n     3997          |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n     3998    In file included from /p/vast1/koparasy/BUILD/spack_cluster_instal\n             ler/quartz/nrm/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/pytho\n             n-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/include/python3.8/object",
    "st.o -o _configtest\n     90      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 91      /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.11.1-pguacuxepfdj\n             qha5joopa2643iy6icpk/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 92      collect2: error: ld returned 1 exit status\n     93      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 94      /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.11.1-pguacuxepfdj\n             qha5joopa2643iy6icpk/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 95      collect2: error: ld returned 1 exit status",
    ">> 92      collect2: error: ld returned 1 exit status\n     93      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 94      /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.11.1-pguacuxepfdj\n             qha5joopa2643iy6icpk/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 95      collect2: error: ld returned 1 exit status\n     96      failure.\n     97      removing: _configtest.c _configtest.o\n     98      C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     99",
    "y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-bro\n             adwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/in\n             clude/python3.8 -c'\n     248     gcc: _configtest.c\n     249     _configtest.c: In function 'main':\n>> 250     _configtest.c:7:12: error: 'SIZEOF_LONGDOUBLE' undeclared (first u\n             se in this function); did you mean 'SIZEOF_LONG_DOUBLE'?\n     251         7 |     (void) SIZEOF_LONGDOUBLE;\n     252           |            ^~~~~~~~~~~~~~~~~\n     253           |            SIZEOF_LONG_DOUBLE\n     254     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "251         7 |     (void) SIZEOF_LONGDOUBLE;\n     252           |            ^~~~~~~~~~~~~~~~~\n     253           |            SIZEOF_LONG_DOUBLE\n     254     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in\n     255     _configtest.c: In function 'main':\n>> 256     _configtest.c:7:12: error: 'SIZEOF_LONGDOUBLE' undeclared (first u\n             se in this function); did you mean 'SIZEOF_LONG_DOUBLE'?\n     257         7 |     (void) SIZEOF_LONGDOUBLE;\n     258           |            ^~~~~~~~~~~~~~~~~\n     259           |            SIZEOF_LONG_DOUBLE\n     260     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "st.o -o _configtest\n     394     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 395     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.11.1-pguacuxepfdj\n             qha5joopa2643iy6icpk/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 396     collect2: error: ld returned 1 exit status\n     397     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 398     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.11.1-pguacuxepfdj\n             qha5joopa2643iy6icpk/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 399     collect2: error: ld returned 1 exit status",
    ">> 396     collect2: error: ld returned 1 exit status\n     397     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 398     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.11.1-pguacuxepfdj\n             qha5joopa2643iy6icpk/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 399     collect2: error: ld returned 1 exit status\n     400     failure.\n     401     removing: _configtest.c _configtest.o\n     402     C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     403",
    "764     gcc: _configtest.c\n     765     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     766         3 | #pragma clang diagnostic error \"-Wattributes\"\n     767           |\n     768     _configtest.c: In function '__declspec':\n>> 769     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     770         5 | int __declspec(thread) foo;\n     771           |                        ^~~\n  >> 772     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     773         9 | {",
    "767           |\n     768     _configtest.c: In function '__declspec':\n  >> 769     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     770         5 | int __declspec(thread) foo;\n     771           |                        ^~~\n>> 772     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     773         9 | {\n     774           | ^\n     775     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     776         5 | int __declspec(thread) foo;",
    "773         9 | {\n     774           | ^\n     775     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     776         5 | int __declspec(thread) foo;\n     777           |     ^~~~~~~~~~\n>> 778     _configtest.c:11: error: expected '{' at end of input\n     779        11 | }\n     780           |\n     781     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     782        11 | }\n     783           |",
    "783           |\n     784     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     785         3 | #pragma clang diagnostic error \"-Wattributes\"\n     786           |\n     787     _configtest.c: In function '__declspec':\n>> 788     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     789         5 | int __declspec(thread) foo;\n     790           |                        ^~~\n  >> 791     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     792         9 | {",
    "786           |\n     787     _configtest.c: In function '__declspec':\n  >> 788     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     789         5 | int __declspec(thread) foo;\n     790           |                        ^~~\n>> 791     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     792         9 | {\n     793           | ^\n     794     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     795         5 | int __declspec(thread) foo;",
    "792         9 | {\n     793           | ^\n     794     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     795         5 | int __declspec(thread) foo;\n     796           |     ^~~~~~~~~~\n>> 797     _configtest.c:11: error: expected '{' at end of input\n     798        11 | }\n     799           |\n     800     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     801        11 | }\n     802           |",
    "y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-bro\n             adwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/in\n             clude/python3.8 -c'\n     1130    gcc: _configtest.c\n     1131    _configtest.c: In function 'main':\n>> 1132    _configtest.c:8:12: error: 'HAVE_DECL_SIGNBIT' undeclared (first u\n             se in this function); did you mean 'HAVE_DECL_ISNAN'?\n     1133        8 |     (void) HAVE_DECL_SIGNBIT;\n     1134          |            ^~~~~~~~~~~~~~~~~\n     1135          |            HAVE_DECL_ISNAN\n     1136    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "1133        8 |     (void) HAVE_DECL_SIGNBIT;\n     1134          |            ^~~~~~~~~~~~~~~~~\n     1135          |            HAVE_DECL_ISNAN\n     1136    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in\n     1137    _configtest.c: In function 'main':\n>> 1138    _configtest.c:8:12: error: 'HAVE_DECL_SIGNBIT' undeclared (first u\n             se in this function); did you mean 'HAVE_DECL_ISNAN'?\n     1139        8 |     (void) HAVE_DECL_SIGNBIT;\n     1140          |            ^~~~~~~~~~~~~~~~~\n     1141          |            HAVE_DECL_ISNAN\n     1142    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "st.o -o _configtest\n     1720    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1721    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.11.1-pguacuxepfdj\n             qha5joopa2643iy6icpk/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 1722    collect2: error: ld returned 1 exit status\n     1723    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1724    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.11.1-pguacuxepfdj\n             qha5joopa2643iy6icpk/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 1725    collect2: error: ld returned 1 exit status",
    ">> 1722    collect2: error: ld returned 1 exit status\n     1723    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1724    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.11.1-pguacuxepfdj\n             qha5joopa2643iy6icpk/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 1725    collect2: error: ld returned 1 exit status\n     1726    failure.\n     1727    removing: _configtest.c _configtest.o\n     1728    C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     1729",
    "nidc7o5wtbfqu64d3ld/include/python3.8/cpython/object.h:260:30: not\n             e: declared here\n     3922      260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *,\n              int);\n     3923          |                              ^~~~~~~~\n     3924    numpy/random/mtrand/mtrand.c: In function '__Pyx_ExceptionSave':\n>> 3925    numpy/random/mtrand/mtrand.c:39571:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3926    39571 |     *type = tstate->exc_type;\n     3927          |                     ^~~~~~~~\n     3928          |                     curexc_type\n  >> 3929    numpy/random/mtrand/mtrand.c:39572:22: error: 'PyThreadState' {aka",
    ">> 3925    numpy/random/mtrand/mtrand.c:39571:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3926    39571 |     *type = tstate->exc_type;\n     3927          |                     ^~~~~~~~\n     3928          |                     curexc_type\n>> 3929    numpy/random/mtrand/mtrand.c:39572:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3930    39572 |     *value = tstate->exc_value;\n     3931          |                      ^~~~~~~~~\n     3932          |                      curexc_value\n  >> 3933    numpy/random/mtrand/mtrand.c:39573:19: error: 'PyThreadState' {aka",
    ">> 3929    numpy/random/mtrand/mtrand.c:39572:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3930    39572 |     *value = tstate->exc_value;\n     3931          |                      ^~~~~~~~~\n     3932          |                      curexc_value\n>> 3933    numpy/random/mtrand/mtrand.c:39573:19: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3934    39573 |     *tb = tstate->exc_traceback;\n     3935          |                   ^~~~~~~~~~~~~\n     3936          |                   curexc_traceback\n     3937    numpy/random/mtrand/mtrand.c: In function '__Pyx_ExceptionReset':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3934    39573 |     *tb = tstate->exc_traceback;\n     3935          |                   ^~~~~~~~~~~~~\n     3936          |                   curexc_traceback\n     3937    numpy/random/mtrand/mtrand.c: In function '__Pyx_ExceptionReset':\n>> 3938    numpy/random/mtrand/mtrand.c:39585:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3939    39585 |     tmp_type = tstate->exc_type;\n     3940          |                        ^~~~~~~~\n     3941          |                        curexc_type\n  >> 3942    numpy/random/mtrand/mtrand.c:39586:25: error: 'PyThreadState' {aka",
    ">> 3938    numpy/random/mtrand/mtrand.c:39585:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3939    39585 |     tmp_type = tstate->exc_type;\n     3940          |                        ^~~~~~~~\n     3941          |                        curexc_type\n>> 3942    numpy/random/mtrand/mtrand.c:39586:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3943    39586 |     tmp_value = tstate->exc_value;\n     3944          |                         ^~~~~~~~~\n     3945          |                         curexc_value\n  >> 3946    numpy/random/mtrand/mtrand.c:39587:22: error: 'PyThreadState' {aka",
    ">> 3942    numpy/random/mtrand/mtrand.c:39586:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3943    39586 |     tmp_value = tstate->exc_value;\n     3944          |                         ^~~~~~~~~\n     3945          |                         curexc_value\n>> 3946    numpy/random/mtrand/mtrand.c:39587:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3947    39587 |     tmp_tb = tstate->exc_traceback;\n     3948          |                      ^~~~~~~~~~~~~\n     3949          |                      curexc_traceback\n  >> 3950    numpy/random/mtrand/mtrand.c:39588:13: error: 'PyThreadState' {aka",
    ">> 3946    numpy/random/mtrand/mtrand.c:39587:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3947    39587 |     tmp_tb = tstate->exc_traceback;\n     3948          |                      ^~~~~~~~~~~~~\n     3949          |                      curexc_traceback\n>> 3950    numpy/random/mtrand/mtrand.c:39588:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3951    39588 |     tstate->exc_type = type;\n     3952          |             ^~~~~~~~\n     3953          |             curexc_type\n  >> 3954    numpy/random/mtrand/mtrand.c:39589:13: error: 'PyThreadState' {aka",
    ">> 3950    numpy/random/mtrand/mtrand.c:39588:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3951    39588 |     tstate->exc_type = type;\n     3952          |             ^~~~~~~~\n     3953          |             curexc_type\n>> 3954    numpy/random/mtrand/mtrand.c:39589:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3955    39589 |     tstate->exc_value = value;\n     3956          |             ^~~~~~~~~\n     3957          |             curexc_value\n  >> 3958    numpy/random/mtrand/mtrand.c:39590:13: error: 'PyThreadState' {aka",
    ">> 3954    numpy/random/mtrand/mtrand.c:39589:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3955    39589 |     tstate->exc_value = value;\n     3956          |             ^~~~~~~~~\n     3957          |             curexc_value\n>> 3958    numpy/random/mtrand/mtrand.c:39590:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3959    39590 |     tstate->exc_traceback = tb;\n     3960          |             ^~~~~~~~~~~~~\n     3961          |             curexc_traceback\n     3962    numpy/random/mtrand/mtrand.c: In function '__Pyx_GetException':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3959    39590 |     tstate->exc_traceback = tb;\n     3960          |             ^~~~~~~~~~~~~\n     3961          |             curexc_traceback\n     3962    numpy/random/mtrand/mtrand.c: In function '__Pyx_GetException':\n>> 3963    numpy/random/mtrand/mtrand.c:39633:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3964    39633 |     tmp_type = tstate->exc_type;\n     3965          |                        ^~~~~~~~\n     3966          |                        curexc_type\n  >> 3967    numpy/random/mtrand/mtrand.c:39634:25: error: 'PyThreadState' {aka",
    ">> 3963    numpy/random/mtrand/mtrand.c:39633:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3964    39633 |     tmp_type = tstate->exc_type;\n     3965          |                        ^~~~~~~~\n     3966          |                        curexc_type\n>> 3967    numpy/random/mtrand/mtrand.c:39634:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3968    39634 |     tmp_value = tstate->exc_value;\n     3969          |                         ^~~~~~~~~\n     3970          |                         curexc_value\n  >> 3971    numpy/random/mtrand/mtrand.c:39635:22: error: 'PyThreadState' {aka",
    ">> 3967    numpy/random/mtrand/mtrand.c:39634:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3968    39634 |     tmp_value = tstate->exc_value;\n     3969          |                         ^~~~~~~~~\n     3970          |                         curexc_value\n>> 3971    numpy/random/mtrand/mtrand.c:39635:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3972    39635 |     tmp_tb = tstate->exc_traceback;\n     3973          |                      ^~~~~~~~~~~~~\n     3974          |                      curexc_traceback\n  >> 3975    numpy/random/mtrand/mtrand.c:39636:13: error: 'PyThreadState' {aka",
    ">> 3971    numpy/random/mtrand/mtrand.c:39635:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3972    39635 |     tmp_tb = tstate->exc_traceback;\n     3973          |                      ^~~~~~~~~~~~~\n     3974          |                      curexc_traceback\n>> 3975    numpy/random/mtrand/mtrand.c:39636:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3976    39636 |     tstate->exc_type = local_type;\n     3977          |             ^~~~~~~~\n     3978          |             curexc_type\n  >> 3979    numpy/random/mtrand/mtrand.c:39637:13: error: 'PyThreadState' {aka",
    ">> 3975    numpy/random/mtrand/mtrand.c:39636:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     3976    39636 |     tstate->exc_type = local_type;\n     3977          |             ^~~~~~~~\n     3978          |             curexc_type\n>> 3979    numpy/random/mtrand/mtrand.c:39637:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3980    39637 |     tstate->exc_value = local_value;\n     3981          |             ^~~~~~~~~\n     3982          |             curexc_value\n  >> 3983    numpy/random/mtrand/mtrand.c:39638:13: error: 'PyThreadState' {aka",
    ">> 3979    numpy/random/mtrand/mtrand.c:39637:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     3980    39637 |     tstate->exc_value = local_value;\n     3981          |             ^~~~~~~~~\n     3982          |             curexc_value\n>> 3983    numpy/random/mtrand/mtrand.c:39638:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     3984    39638 |     tstate->exc_traceback = local_tb;\n     3985          |             ^~~~~~~~~~~~~\n     3986          |             curexc_traceback\n     3987    Running from numpy source directory.",
    "nidc7o5wtbfqu64d3ld/include/python3.8/cpython/object.h:260:30: not\n             e: declared here\n     4003      260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *,\n              int);\n     4004          |                              ^~~~~~~~\n     4005    numpy/random/mtrand/mtrand.c: In function '__Pyx_ExceptionSave':\n>> 4006    numpy/random/mtrand/mtrand.c:39571:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4007    39571 |     *type = tstate->exc_type;\n     4008          |                     ^~~~~~~~\n     4009          |                     curexc_type\n  >> 4010    numpy/random/mtrand/mtrand.c:39572:22: error: 'PyThreadState' {aka",
    ">> 4006    numpy/random/mtrand/mtrand.c:39571:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4007    39571 |     *type = tstate->exc_type;\n     4008          |                     ^~~~~~~~\n     4009          |                     curexc_type\n>> 4010    numpy/random/mtrand/mtrand.c:39572:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4011    39572 |     *value = tstate->exc_value;\n     4012          |                      ^~~~~~~~~\n     4013          |                      curexc_value\n  >> 4014    numpy/random/mtrand/mtrand.c:39573:19: error: 'PyThreadState' {aka",
    ">> 4010    numpy/random/mtrand/mtrand.c:39572:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4011    39572 |     *value = tstate->exc_value;\n     4012          |                      ^~~~~~~~~\n     4013          |                      curexc_value\n>> 4014    numpy/random/mtrand/mtrand.c:39573:19: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4015    39573 |     *tb = tstate->exc_traceback;\n     4016          |                   ^~~~~~~~~~~~~\n     4017          |                   curexc_traceback\n     4018    numpy/random/mtrand/mtrand.c: In function '__Pyx_ExceptionReset':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4015    39573 |     *tb = tstate->exc_traceback;\n     4016          |                   ^~~~~~~~~~~~~\n     4017          |                   curexc_traceback\n     4018    numpy/random/mtrand/mtrand.c: In function '__Pyx_ExceptionReset':\n>> 4019    numpy/random/mtrand/mtrand.c:39585:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4020    39585 |     tmp_type = tstate->exc_type;\n     4021          |                        ^~~~~~~~\n     4022          |                        curexc_type\n  >> 4023    numpy/random/mtrand/mtrand.c:39586:25: error: 'PyThreadState' {aka",
    ">> 4019    numpy/random/mtrand/mtrand.c:39585:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4020    39585 |     tmp_type = tstate->exc_type;\n     4021          |                        ^~~~~~~~\n     4022          |                        curexc_type\n>> 4023    numpy/random/mtrand/mtrand.c:39586:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4024    39586 |     tmp_value = tstate->exc_value;\n     4025          |                         ^~~~~~~~~\n     4026          |                         curexc_value\n  >> 4027    numpy/random/mtrand/mtrand.c:39587:22: error: 'PyThreadState' {aka",
    ">> 4023    numpy/random/mtrand/mtrand.c:39586:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4024    39586 |     tmp_value = tstate->exc_value;\n     4025          |                         ^~~~~~~~~\n     4026          |                         curexc_value\n>> 4027    numpy/random/mtrand/mtrand.c:39587:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4028    39587 |     tmp_tb = tstate->exc_traceback;\n     4029          |                      ^~~~~~~~~~~~~\n     4030          |                      curexc_traceback\n  >> 4031    numpy/random/mtrand/mtrand.c:39588:13: error: 'PyThreadState' {aka",
    ">> 4027    numpy/random/mtrand/mtrand.c:39587:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4028    39587 |     tmp_tb = tstate->exc_traceback;\n     4029          |                      ^~~~~~~~~~~~~\n     4030          |                      curexc_traceback\n>> 4031    numpy/random/mtrand/mtrand.c:39588:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4032    39588 |     tstate->exc_type = type;\n     4033          |             ^~~~~~~~\n     4034          |             curexc_type\n  >> 4035    numpy/random/mtrand/mtrand.c:39589:13: error: 'PyThreadState' {aka",
    ">> 4031    numpy/random/mtrand/mtrand.c:39588:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4032    39588 |     tstate->exc_type = type;\n     4033          |             ^~~~~~~~\n     4034          |             curexc_type\n>> 4035    numpy/random/mtrand/mtrand.c:39589:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4036    39589 |     tstate->exc_value = value;\n     4037          |             ^~~~~~~~~\n     4038          |             curexc_value\n  >> 4039    numpy/random/mtrand/mtrand.c:39590:13: error: 'PyThreadState' {aka",
    ">> 4035    numpy/random/mtrand/mtrand.c:39589:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4036    39589 |     tstate->exc_value = value;\n     4037          |             ^~~~~~~~~\n     4038          |             curexc_value\n>> 4039    numpy/random/mtrand/mtrand.c:39590:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4040    39590 |     tstate->exc_traceback = tb;\n     4041          |             ^~~~~~~~~~~~~\n     4042          |             curexc_traceback\n     4043    numpy/random/mtrand/mtrand.c: In function '__Pyx_GetException':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4040    39590 |     tstate->exc_traceback = tb;\n     4041          |             ^~~~~~~~~~~~~\n     4042          |             curexc_traceback\n     4043    numpy/random/mtrand/mtrand.c: In function '__Pyx_GetException':\n>> 4044    numpy/random/mtrand/mtrand.c:39633:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4045    39633 |     tmp_type = tstate->exc_type;\n     4046          |                        ^~~~~~~~\n     4047          |                        curexc_type\n  >> 4048    numpy/random/mtrand/mtrand.c:39634:25: error: 'PyThreadState' {aka",
    ">> 4044    numpy/random/mtrand/mtrand.c:39633:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4045    39633 |     tmp_type = tstate->exc_type;\n     4046          |                        ^~~~~~~~\n     4047          |                        curexc_type\n>> 4048    numpy/random/mtrand/mtrand.c:39634:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4049    39634 |     tmp_value = tstate->exc_value;\n     4050          |                         ^~~~~~~~~\n     4051          |                         curexc_value\n  >> 4052    numpy/random/mtrand/mtrand.c:39635:22: error: 'PyThreadState' {aka",
    ">> 4048    numpy/random/mtrand/mtrand.c:39634:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4049    39634 |     tmp_value = tstate->exc_value;\n     4050          |                         ^~~~~~~~~\n     4051          |                         curexc_value\n>> 4052    numpy/random/mtrand/mtrand.c:39635:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4053    39635 |     tmp_tb = tstate->exc_traceback;\n     4054          |                      ^~~~~~~~~~~~~\n     4055          |                      curexc_traceback\n  >> 4056    numpy/random/mtrand/mtrand.c:39636:13: error: 'PyThreadState' {aka",
    ">> 4052    numpy/random/mtrand/mtrand.c:39635:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4053    39635 |     tmp_tb = tstate->exc_traceback;\n     4054          |                      ^~~~~~~~~~~~~\n     4055          |                      curexc_traceback\n>> 4056    numpy/random/mtrand/mtrand.c:39636:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4057    39636 |     tstate->exc_type = local_type;\n     4058          |             ^~~~~~~~\n     4059          |             curexc_type\n  >> 4060    numpy/random/mtrand/mtrand.c:39637:13: error: 'PyThreadState' {aka",
    ">> 4056    numpy/random/mtrand/mtrand.c:39636:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4057    39636 |     tstate->exc_type = local_type;\n     4058          |             ^~~~~~~~\n     4059          |             curexc_type\n>> 4060    numpy/random/mtrand/mtrand.c:39637:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4061    39637 |     tstate->exc_value = local_value;\n     4062          |             ^~~~~~~~~\n     4063          |             curexc_value\n  >> 4064    numpy/random/mtrand/mtrand.c:39638:13: error: 'PyThreadState' {aka",
    ">> 4060    numpy/random/mtrand/mtrand.c:39637:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4061    39637 |     tstate->exc_value = local_value;\n     4062          |             ^~~~~~~~~\n     4063          |             curexc_value\n>> 4064    numpy/random/mtrand/mtrand.c:39638:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4065    39638 |     tstate->exc_traceback = local_tb;\n     4066          |             ^~~~~~~~~~~~~\n     4067          |             curexc_traceback\n  >> 4068    error: Command \"/p/vast1/koparasy/BUILD/head/spack/lib/spack/env/g"
]