[
    "/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy\n             /core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUILD\n             /spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-broa\n             dwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/inc\n             lude/python3.8 -c'\n     899     gcc: _configtest.c\n900     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     901         3 | #pragma clang diagnostic error \"-Wattributes\"\n     902           |\n     903     _configtest.c: In function '__declspec':\n  >> 904     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'",
    "905         5 | int __declspec(thread) foo;\n     906           |                        ^~~\n  >> 907     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     908         9 | {\n     909           | ^\n910     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     911         5 | int __declspec(thread) foo;\n     912           |     ^~~~~~~~~~\n  >> 913     _configtest.c:11: error: expected '{' at end of input\n     914        11 | }\n     915           |",
    "implicit-int]\n     911         5 | int __declspec(thread) foo;\n     912           |     ^~~~~~~~~~\n  >> 913     _configtest.c:11: error: expected '{' at end of input\n     914        11 | }\n     915           |\n916     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     917        11 | }\n     918           |\n     919     failure.\n\n     ...",
    "st.o -o _configtest\n     90      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 91      /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.17.1-6rplmjm2mkh7\n             qhq43jlz7hum537qvapc/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 92      collect2: error: ld returned 1 exit status\n     93      failure.\n     94      removing: _configtest.c _configtest.o _configtest.o.d\n     95      C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     96",
    "/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy\n             /core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUILD\n             /spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-broa\n             dwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/inc\n             lude/python3.8 -c'\n     148     gcc: _configtest.c\n>> 149     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory\n     150         1 | #include <sys/endian.h>\n     151           |          ^~~~~~~~~~~~~~\n     152     compilation terminated.\n     153     failure.\n     154     removing: _configtest.c _configtest.o",
    "/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUILD\n             /spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-broa\n             dwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/inc\n             lude/python3.8 -c'\n     260     gcc: _configtest.c\n     261     _configtest.c: In function 'main':\n>> 262     _configtest.c:7:12: error: 'SIZEOF_LONGDOUBLE' undeclared (first u\n             se in this function); did you mean 'SIZEOF_LONG_DOUBLE'?\n     263         7 |     (void) SIZEOF_LONGDOUBLE;\n     264           |            ^~~~~~~~~~~~~~~~~\n     265           |            SIZEOF_LONG_DOUBLE\n     266     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "st.o -o _configtest\n     400     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 401     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.17.1-6rplmjm2mkh7\n             qhq43jlz7hum537qvapc/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 402     collect2: error: ld returned 1 exit status\n     403     failure.\n     404     removing: _configtest.c _configtest.o _configtest.o.d\n     405     C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     406",
    "899     gcc: _configtest.c\n     900     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     901         3 | #pragma clang diagnostic error \"-Wattributes\"\n     902           |\n     903     _configtest.c: In function '__declspec':\n>> 904     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     905         5 | int __declspec(thread) foo;\n     906           |                        ^~~\n  >> 907     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     908         9 | {",
    "902           |\n     903     _configtest.c: In function '__declspec':\n  >> 904     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     905         5 | int __declspec(thread) foo;\n     906           |                        ^~~\n>> 907     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     908         9 | {\n     909           | ^\n     910     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     911         5 | int __declspec(thread) foo;",
    "908         9 | {\n     909           | ^\n     910     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     911         5 | int __declspec(thread) foo;\n     912           |     ^~~~~~~~~~\n>> 913     _configtest.c:11: error: expected '{' at end of input\n     914        11 | }\n     915           |\n     916     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     917        11 | }\n     918           |",
    "/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUILD\n             /spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-broa\n             dwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/inc\n             lude/python3.8 -c'\n     1246    gcc: _configtest.c\n     1247    _configtest.c: In function 'main':\n>> 1248    _configtest.c:8:12: error: 'HAVE_DECL_SIGNBIT' undeclared (first u\n             se in this function); did you mean 'HAVE_DECL_ISNAN'?\n     1249        8 |     (void) HAVE_DECL_SIGNBIT;\n     1250          |            ^~~~~~~~~~~~~~~~~\n     1251          |            HAVE_DECL_ISNAN\n     1252    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "st.o -o _configtest\n     1843    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1844    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.17.1-6rplmjm2mkh7\n             qhq43jlz7hum537qvapc/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 1845    collect2: error: ld returned 1 exit status\n     1846    failure.\n     1847    removing: _configtest.c _configtest.o _configtest.o.d\n     1848    C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     1849",
    "/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.8/numpy/core/sr\n             c/common -Ibuild/src.linux-x86_64-3.8/numpy/core/src/npymath -c'\n     2407    extra options: '-U__GNUC_GNU_INLINE__ -std=c99 -msse2'\n     2408    gcc: numpy/random/entropy.c\n     2409    gcc: numpy/random/src/entropy/entropy.c\n     2410    numpy/random/entropy.c: In function '__Pyx_InitCachedConstants':\n>> 2411    numpy/random/entropy.c:20741:273: error: macro \"__Pyx_PyCode_New\"\n             requires 16 arguments, but only 15 given\n     2412    20741 |   __pyx_codeobj__31 = (PyObject*)__Pyx_PyCode_New(2, 0, 14\n             , 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tup\n             le, __pyx_empty_tuple, __pyx_tuple__30, __pyx_empty_tuple, __pyx_e\n             mpty_tuple, __pyx_kp_s_entropy_pyx, __pyx_n_s_seed_by_array, 27, _\n             _pyx_empty_bytes); if (unlikely(!__pyx_codeobj__31)) __PYX_ERR(0,",
    "^\n     2414    numpy/random/entropy.c:317: note: macro \"__Pyx_PyCode_New\" defined\n              here\n     2415      317 |   #define __Pyx_PyCode_New(a, p, k, l, s, f, code, c, n, v\n             , fv, cell, fn, name, fline, lnos)\\\n     2416          |\n>> 2417    numpy/random/entropy.c:20741:34: error: '__Pyx_PyCode_New' undecla\n             red (first use in this function); did you mean 'PyCode_New'?\n     2418    20741 |   __pyx_codeobj__31 = (PyObject*)__Pyx_PyCode_New(2, 0, 14\n             , 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tup\n             le, __pyx_empty_tuple, __pyx_tuple__30, __pyx_empty_tuple, __pyx_e\n             mpty_tuple, __pyx_kp_s_entropy_pyx, __pyx_n_s_seed_by_array, 27, _\n             _pyx_empty_bytes); if (unlikely(!__pyx_codeobj__31)) __PYX_ERR(0,",
    "_pyx_empty_bytes); if (unlikely(!__pyx_codeobj__31)) __PYX_ERR(0,\n             27, __pyx_L1_error)\n     2419          |                                  ^~~~~~~~~~~~~~~~\n     2420          |                                  PyCode_New\n     2421    numpy/random/entropy.c:20741:34: note: each undeclared identifier\n             is reported only once for each function it appears in\n>> 2422    numpy/random/entropy.c:20753:273: error: macro \"__Pyx_PyCode_New\"\n             requires 16 arguments, but only 15 given\n     2423    20753 |   __pyx_codeobj__33 = (PyObject*)__Pyx_PyCode_New(2, 0, 6,\n              0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tupl\n             e, __pyx_empty_tuple, __pyx_tuple__32, __pyx_empty_tuple, __pyx_em\n             pty_tuple, __pyx_kp_s_entropy_pyx, __pyx_n_s_random_entropy, 95, _\n             _pyx_empty_bytes); if (unlikely(!__pyx_codeobj__33)) __PYX_ERR(0,",
    "^\n     2425    numpy/random/entropy.c:317: note: macro \"__Pyx_PyCode_New\" defined\n              here\n     2426      317 |   #define __Pyx_PyCode_New(a, p, k, l, s, f, code, c, n, v\n             , fv, cell, fn, name, fline, lnos)\\\n     2427          |\n>> 2428    numpy/random/entropy.c:20818:276: error: macro \"__Pyx_PyCode_New\"\n             requires 16 arguments, but only 15 given\n     2429    20818 |   __pyx_codeobj__40 = (PyObject*)__Pyx_PyCode_New(3, 0, 5,\n              0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tupl\n             e, __pyx_empty_tuple, __pyx_tuple__39, __pyx_empty_tuple, __pyx_em\n             pty_tuple, __pyx_kp_s_stringsource, __pyx_n_s_pyx_unpickle_Enum, 1\n             , __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__40)) __PYX_ERR(",
    "here\n     2432      317 |   #define __Pyx_PyCode_New(a, p, k, l, s, f, code, c, n, v\n             , fv, cell, fn, name, fline, lnos)\\\n     2433          |\n     2434    numpy/random/entropy.c: In function '__Pyx_CreateCodeObjectForTrac\n             eback':\n>> 2435    numpy/random/entropy.c:23700:5: error: macro \"__Pyx_PyCode_New\" re\n             quires 16 arguments, but only 15 given\n     2436    23700 |     );\n     2437          |     ^\n     2438    numpy/random/entropy.c:317: note: macro \"__Pyx_PyCode_New\" defined\n              here\n     2439      317 |   #define __Pyx_PyCode_New(a, p, k, l, s, f, code, c, n, v",
    "2437          |     ^\n     2438    numpy/random/entropy.c:317: note: macro \"__Pyx_PyCode_New\" defined\n              here\n     2439      317 |   #define __Pyx_PyCode_New(a, p, k, l, s, f, code, c, n, v\n             , fv, cell, fn, name, fline, lnos)\\\n     2440          |\n>> 2441    numpy/random/entropy.c:23684:15: error: '__Pyx_PyCode_New' undecla\n             red (first use in this function); did you mean 'PyCode_New'?\n     2442    23684 |     py_code = __Pyx_PyCode_New(\n     2443          |               ^~~~~~~~~~~~~~~~\n     2444          |               PyCode_New\n     2445    Running from numpy source directory.\n  >> 2446    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/nrm/spack_e"
]