[
    "/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy\n             /core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUILD\n             /spack_cluster_installer/quartz/py-warpx/spack_env_dir/linux-rhel7\n             -broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxwx2ytcv7sd3g35si6\n             /include/python3.9 -c'\n     902     gcc: _configtest.c\n903     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     904         3 | #pragma clang diagnostic error \"-Wattributes\"\n     905           |\n     906     _configtest.c: In function '__declspec':\n  >> 907     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'",
    "908         5 | int __declspec(thread) foo;\n     909           |                        ^~~\n  >> 910     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     911         9 | {\n     912           | ^\n913     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     914         5 | int __declspec(thread) foo;\n     915           |     ^~~~~~~~~~\n  >> 916     _configtest.c:11: error: expected '{' at end of input\n     917        11 | }\n     918           |",
    "implicit-int]\n     914         5 | int __declspec(thread) foo;\n     915           |     ^~~~~~~~~~\n  >> 916     _configtest.c:11: error: expected '{' at end of input\n     917        11 | }\n     918           |\n919     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     920        11 | }\n     921           |\n     922     failure.\n\n     ...",
    "st.o -o _configtest\n     93      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 94      /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.17.0-5ohpzfzykqgw\n             s25tpki5stvpiauwewgd/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 95      collect2: error: ld returned 1 exit status\n     96      failure.\n     97      removing: _configtest.c _configtest.o _configtest.o.d\n     98      C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     99",
    "/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy\n             /core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUILD\n             /spack_cluster_installer/quartz/py-warpx/spack_env_dir/linux-rhel7\n             -broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxwx2ytcv7sd3g35si6\n             /include/python3.9 -c'\n     151     gcc: _configtest.c\n>> 152     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory\n     153         1 | #include <sys/endian.h>\n     154           |          ^~~~~~~~~~~~~~\n     155     compilation terminated.\n     156     failure.\n     157     removing: _configtest.c _configtest.o",
    "/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUILD\n             /spack_cluster_installer/quartz/py-warpx/spack_env_dir/linux-rhel7\n             -broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxwx2ytcv7sd3g35si6\n             /include/python3.9 -c'\n     263     gcc: _configtest.c\n     264     _configtest.c: In function 'main':\n>> 265     _configtest.c:7:12: error: 'SIZEOF_LONGDOUBLE' undeclared (first u\n             se in this function); did you mean 'SIZEOF_LONG_DOUBLE'?\n     266         7 |     (void) SIZEOF_LONGDOUBLE;\n     267           |            ^~~~~~~~~~~~~~~~~\n     268           |            SIZEOF_LONG_DOUBLE\n     269     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "st.o -o _configtest\n     403     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 404     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.17.0-5ohpzfzykqgw\n             s25tpki5stvpiauwewgd/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 405     collect2: error: ld returned 1 exit status\n     406     failure.\n     407     removing: _configtest.c _configtest.o _configtest.o.d\n     408     C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     409",
    "902     gcc: _configtest.c\n     903     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     904         3 | #pragma clang diagnostic error \"-Wattributes\"\n     905           |\n     906     _configtest.c: In function '__declspec':\n>> 907     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     908         5 | int __declspec(thread) foo;\n     909           |                        ^~~\n  >> 910     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     911         9 | {",
    "905           |\n     906     _configtest.c: In function '__declspec':\n  >> 907     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     908         5 | int __declspec(thread) foo;\n     909           |                        ^~~\n>> 910     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     911         9 | {\n     912           | ^\n     913     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     914         5 | int __declspec(thread) foo;",
    "911         9 | {\n     912           | ^\n     913     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     914         5 | int __declspec(thread) foo;\n     915           |     ^~~~~~~~~~\n>> 916     _configtest.c:11: error: expected '{' at end of input\n     917        11 | }\n     918           |\n     919     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     920        11 | }\n     921           |",
    "/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUILD\n             /spack_cluster_installer/quartz/py-warpx/spack_env_dir/linux-rhel7\n             -broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxwx2ytcv7sd3g35si6\n             /include/python3.9 -c'\n     1249    gcc: _configtest.c\n     1250    _configtest.c: In function 'main':\n>> 1251    _configtest.c:8:12: error: 'HAVE_DECL_SIGNBIT' undeclared (first u\n             se in this function); did you mean 'HAVE_DECL_ISNAN'?\n     1252        8 |     (void) HAVE_DECL_SIGNBIT;\n     1253          |            ^~~~~~~~~~~~~~~~~\n     1254          |            HAVE_DECL_ISNAN\n     1255    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "st.o -o _configtest\n     1846    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1847    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.17.0-5ohpzfzykqgw\n             s25tpki5stvpiauwewgd/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 1848    collect2: error: ld returned 1 exit status\n     1849    failure.\n     1850    removing: _configtest.c _configtest.o _configtest.o.d\n     1851    C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     1852",
    "e/src/common -Ibuild/src.linux-x86_64-3.9/numpy/core/src/npymath -\n             c'\n     2825    extra options: '-U__GNUC_GNU_INLINE__ -std=c99 -msse2'\n     2826    gcc: numpy/random/entropy.c\n     2827    gcc: numpy/random/src/entropy/entropy.c\n     2828    numpy/random/entropy.c: In function '__Pyx_InitCachedConstants':\n>> 2829    numpy/random/entropy.c:20741:273: error: macro \"__Pyx_PyCode_New\"\n             requires 16 arguments, but only 15 given\n     2830    20741 |   __pyx_codeobj__31 = (PyObject*)__Pyx_PyCode_New(2, 0, 14\n             , 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tup\n             le, __pyx_empty_tuple, __pyx_tuple__30, __pyx_empty_tuple, __pyx_e\n             mpty_tuple, __pyx_kp_s_entropy_pyx, __pyx_n_s_seed_by_array, 27, _\n             _pyx_empty_bytes); if (unlikely(!__pyx_codeobj__31)) __PYX_ERR(0,",
    "^\n     2832    numpy/random/entropy.c:317: note: macro \"__Pyx_PyCode_New\" defined\n              here\n     2833      317 |   #define __Pyx_PyCode_New(a, p, k, l, s, f, code, c, n, v\n             , fv, cell, fn, name, fline, lnos)\\\n     2834          |\n>> 2835    numpy/random/entropy.c:20741:34: error: '__Pyx_PyCode_New' undecla\n             red (first use in this function); did you mean 'PyCode_New'?\n     2836    20741 |   __pyx_codeobj__31 = (PyObject*)__Pyx_PyCode_New(2, 0, 14\n             , 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tup\n             le, __pyx_empty_tuple, __pyx_tuple__30, __pyx_empty_tuple, __pyx_e\n             mpty_tuple, __pyx_kp_s_entropy_pyx, __pyx_n_s_seed_by_array, 27, _\n             _pyx_empty_bytes); if (unlikely(!__pyx_codeobj__31)) __PYX_ERR(0,",
    "_pyx_empty_bytes); if (unlikely(!__pyx_codeobj__31)) __PYX_ERR(0,\n             27, __pyx_L1_error)\n     2837          |                                  ^~~~~~~~~~~~~~~~\n     2838          |                                  PyCode_New\n     2839    numpy/random/entropy.c:20741:34: note: each undeclared identifier\n             is reported only once for each function it appears in\n>> 2840    numpy/random/entropy.c:20753:273: error: macro \"__Pyx_PyCode_New\"\n             requires 16 arguments, but only 15 given\n     2841    20753 |   __pyx_codeobj__33 = (PyObject*)__Pyx_PyCode_New(2, 0, 6,\n              0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tupl\n             e, __pyx_empty_tuple, __pyx_tuple__32, __pyx_empty_tuple, __pyx_em\n             pty_tuple, __pyx_kp_s_entropy_pyx, __pyx_n_s_random_entropy, 95, _\n             _pyx_empty_bytes); if (unlikely(!__pyx_codeobj__33)) __PYX_ERR(0,",
    "^\n     2843    numpy/random/entropy.c:317: note: macro \"__Pyx_PyCode_New\" defined\n              here\n     2844      317 |   #define __Pyx_PyCode_New(a, p, k, l, s, f, code, c, n, v\n             , fv, cell, fn, name, fline, lnos)\\\n     2845          |\n>> 2846    numpy/random/entropy.c:20818:276: error: macro \"__Pyx_PyCode_New\"\n             requires 16 arguments, but only 15 given\n     2847    20818 |   __pyx_codeobj__40 = (PyObject*)__Pyx_PyCode_New(3, 0, 5,\n              0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tupl\n             e, __pyx_empty_tuple, __pyx_tuple__39, __pyx_empty_tuple, __pyx_em\n             pty_tuple, __pyx_kp_s_stringsource, __pyx_n_s_pyx_unpickle_Enum, 1\n             , __pyx_empty_bytes); if (unlikely(!__pyx_codeobj__40)) __PYX_ERR(",
    "2969      551 | Py_DEPRECATED(3.3) PyAPI_FUNC(PyObject*) PyUnicode_FromUni\n             code(\n     2970          |                                          ^~~~~~~~~~~~~~~~~\n             ~~~~\n     2971    numpy/random/entropy.c: In function '__Pyx_CreateCodeObjectForTrac\n             eback':\n>> 2972    numpy/random/entropy.c:23700:5: error: macro \"__Pyx_PyCode_New\" re\n             quires 16 arguments, but only 15 given\n     2973    23700 |     );\n     2974          |     ^\n     2975    numpy/random/entropy.c:317: note: macro \"__Pyx_PyCode_New\" defined\n              here\n     2976      317 |   #define __Pyx_PyCode_New(a, p, k, l, s, f, code, c, n, v",
    "2974          |     ^\n     2975    numpy/random/entropy.c:317: note: macro \"__Pyx_PyCode_New\" defined\n              here\n     2976      317 |   #define __Pyx_PyCode_New(a, p, k, l, s, f, code, c, n, v\n             , fv, cell, fn, name, fline, lnos)\\\n     2977          |\n>> 2978    numpy/random/entropy.c:23684:15: error: '__Pyx_PyCode_New' undecla\n             red (first use in this function); did you mean 'PyCode_New'?\n     2979    23684 |     py_code = __Pyx_PyCode_New(\n     2980          |               ^~~~~~~~~~~~~~~~\n     2981          |               PyCode_New\n  >> 2982    error: Command \"/p/vast1/koparasy/BUILD/head/spack/lib/spack/env/g\n             cc/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -"
]