[
    "51     creating build/temp.linux-x86_64-3.9/src\n     52     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc -fPIC -Wno-unused-result -Wsig\n            n-compare -DNDEBUG -g -fwrapv -O3 -Wall -c src/pmpi-mpe.c -o build/\n            temp.linux-x86_64-3.9/src/pmpi-mpe.o\n53     src/pmpi-mpe.c:3:19: warning: 'name' defined but not used [-Wunused\n            -const-variable=]\n     54         3 | static const char name[] = \"mpe\";\n     55           |                   ^~~~\n     56     creating build/lib.linux-x86_64-3.9/mpi4py/lib-pmpi\n     57     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6",
    "94     building 'vt-mpi' dylib library\n     95     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc -fPIC -Wno-unused-result -Wsig\n            n-compare -DNDEBUG -g -fwrapv -O3 -Wall -c src/pmpi-vt-mpi.c -o bui\n            ld/temp.linux-x86_64-3.9/src/pmpi-vt-mpi.o\n96     src/pmpi-vt-mpi.c:3:19: warning: 'name' defined but not used [-Wunu\n            sed-const-variable=]\n     97         3 | static const char name[] = \"vt-mpi\";\n     98           |                   ^~~~\n     99     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc /p/vast1/koparasy/BUILD/head/s",
    "113    building 'vt-hyb' dylib library\n     114    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc -fPIC -Wno-unused-result -Wsig\n            n-compare -DNDEBUG -g -fwrapv -O3 -Wall -c src/pmpi-vt-hyb.c -o bui\n            ld/temp.linux-x86_64-3.9/src/pmpi-vt-hyb.o\n115    src/pmpi-vt-hyb.c:3:19: warning: 'name' defined but not used [-Wunu\n            sed-const-variable=]\n     116        3 | static const char name[] = \"vt-hyb\";\n     117          |                   ^~~~\n     118    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc /p/vast1/koparasy/BUILD/head/s",
    "'} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     231    113092 |     tstate->exc_traceback = local_tb;\n     232           |             ^~~~~~~~~~~~~\n     233           |             curexc_traceback\n     234    src/mpi4py.MPI.c: In function '__Pyx_Raise':\n235    src/mpi4py.MPI.c:113239:9: warning: 'PyEval_CallObjectWithKeywords'\n             is deprecated [-Wdeprecated-declarations]\n     236    113239 |         owned_instance = PyEval_CallObject(type, args);\n\n     ...\n\n     395                     from src/MPI.c:3:",
    "test.o\n     37     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc _configtest.o -lmpe -lpthread\n            -o _configtest\n  >> 38     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lmpe\n  >> 39     collect2: error: ld returned 1 exit status\n     40     failure.\n     41     removing: _configtest.c _configtest.o\n     42     checking for library 'lmpe' ...\n     43     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6",
    "37     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc _configtest.o -lmpe -lpthread\n            -o _configtest\n  >> 38     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lmpe\n>> 39     collect2: error: ld returned 1 exit status\n     40     failure.\n     41     removing: _configtest.c _configtest.o\n     42     checking for library 'lmpe' ...\n     43     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc -fPIC -Wno-unused-result -Wsig",
    "test.o\n     44     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc _configtest.o -llmpe -lpthread\n             -o _configtest\n  >> 45     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -llmpe\n  >> 46     collect2: error: ld returned 1 exit status\n     47     failure.\n     48     removing: _configtest.c _configtest.o\n     49     building 'mpe' dylib library\n     50     creating build/temp.linux-x86_64-3.9\n     51     creating build/temp.linux-x86_64-3.9/src",
    "44     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc _configtest.o -llmpe -lpthread\n             -o _configtest\n  >> 45     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -llmpe\n>> 46     collect2: error: ld returned 1 exit status\n     47     failure.\n     48     removing: _configtest.c _configtest.o\n     49     building 'mpe' dylib library\n     50     creating build/temp.linux-x86_64-3.9\n     51     creating build/temp.linux-x86_64-3.9/src\n     52     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb",
    "py-libensemble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/zlib-1\n            .2.11-dtzzlwcy6jw7hjm7z2aip4eyed2rizzu/lib build/temp.linux-x86_64-\n            3.9/src/pmpi-mpe.o -o build/lib.linux-x86_64-3.9/mpi4py/lib-pmpi/li\n            bmpe.so\n     58     /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/gcc: file not\n            recognized: file format not recognized\n>> 59     collect2: error: ld returned 1 exit status\n     60     warning: build_clib: building library \"mpe\" failed\n     61\n     62     warning: build_clib: command '/p/vast1/koparasy/BUILD/spack_cluster\n            _installer/quartz/py-libensemble/spack_env_dir/linux-rhel7-broadwel\n            l/gcc-9.3.1/mpich-3.1.3-unrvf6ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc'\n             failed with exit code 1",
    "test.o\n     66     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc _configtest.o -lvt-mpi -o _con\n            figtest\n  >> 67     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lvt-mpi\n  >> 68     collect2: error: ld returned 1 exit status\n     69     failure.\n     70     removing: _configtest.c _configtest.o\n     71     checking for library 'vt.mpi' ...\n     72     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6",
    "66     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc _configtest.o -lvt-mpi -o _con\n            figtest\n  >> 67     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lvt-mpi\n>> 68     collect2: error: ld returned 1 exit status\n     69     failure.\n     70     removing: _configtest.c _configtest.o\n     71     checking for library 'vt.mpi' ...\n     72     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc -fPIC -Wno-unused-result -Wsig",
    "test.o\n     73     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc _configtest.o -lvt.mpi -o _con\n            figtest\n  >> 74     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lvt.mpi\n  >> 75     collect2: error: ld returned 1 exit status\n     76     failure.\n     77     removing: _configtest.c _configtest.o\n     78     building 'vt' dylib library\n     79     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6",
    "73     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc _configtest.o -lvt.mpi -o _con\n            figtest\n  >> 74     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lvt.mpi\n>> 75     collect2: error: ld returned 1 exit status\n     76     failure.\n     77     removing: _configtest.c _configtest.o\n     78     building 'vt' dylib library\n     79     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc -fPIC -Wno-unused-result -Wsig",
    "py-libensemble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/zlib-1\n            .2.11-dtzzlwcy6jw7hjm7z2aip4eyed2rizzu/lib build/temp.linux-x86_64-\n            3.9/src/pmpi-vt.o -o build/lib.linux-x86_64-3.9/mpi4py/lib-pmpi/lib\n            vt.so\n     81     /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/gcc: file not\n            recognized: file format not recognized\n>> 82     collect2: error: ld returned 1 exit status\n     83     warning: build_clib: building library \"vt\" failed\n     84\n     85     warning: build_clib: command '/p/vast1/koparasy/BUILD/spack_cluster\n            _installer/quartz/py-libensemble/spack_env_dir/linux-rhel7-broadwel\n            l/gcc-9.3.1/mpich-3.1.3-unrvf6ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc'\n             failed with exit code 1",
    "test.o\n     89     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc _configtest.o -lvt-mpi -o _con\n            figtest\n  >> 90     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lvt-mpi\n  >> 91     collect2: error: ld returned 1 exit status\n     92     failure.\n     93     removing: _configtest.c _configtest.o\n     94     building 'vt-mpi' dylib library\n     95     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6",
    "89     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc _configtest.o -lvt-mpi -o _con\n            figtest\n  >> 90     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lvt-mpi\n>> 91     collect2: error: ld returned 1 exit status\n     92     failure.\n     93     removing: _configtest.c _configtest.o\n     94     building 'vt-mpi' dylib library\n     95     /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc -fPIC -Wno-unused-result -Wsig",
    "py-libensemble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/zlib-1\n            .2.11-dtzzlwcy6jw7hjm7z2aip4eyed2rizzu/lib build/temp.linux-x86_64-\n            3.9/src/pmpi-vt-mpi.o -o build/lib.linux-x86_64-3.9/mpi4py/lib-pmpi\n            /libvt-mpi.so\n     100    /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/gcc: file not\n            recognized: file format not recognized\n>> 101    collect2: error: ld returned 1 exit status\n     102    warning: build_clib: building library \"vt-mpi\" failed\n     103\n     104    warning: build_clib: command '/p/vast1/koparasy/BUILD/spack_cluster\n            _installer/quartz/py-libensemble/spack_env_dir/linux-rhel7-broadwel\n            l/gcc-9.3.1/mpich-3.1.3-unrvf6ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc'\n             failed with exit code 1",
    "test.o\n     108    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc _configtest.o -lvt-hyb -o _con\n            figtest\n  >> 109    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\ndhat-linux/9/ld: cannot find -lvt-hyb\n  >> 110    collect2: error: ld returned 1 exit status\n     111    failure.\n     112    removing: _configtest.c _configtest.o\n     113    building 'vt-hyb' dylib library\n     114    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6",
    "108    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc _configtest.o -lvt-hyb -o _con\n            figtest\n  >> 109    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-re\n            dhat-linux/9/ld: cannot find -lvt-hyb\n>> 110    collect2: error: ld returned 1 exit status\n     111    failure.\n     112    removing: _configtest.c _configtest.o\n     113    building 'vt-hyb' dylib library\n     114    /p/vast1/koparasy/BUILD/spack_cluster_installer/quartz/py-libensemb\n            le/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/mpich-3.1.3-unrvf6\n            ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc -fPIC -Wno-unused-result -Wsig",
    "py-libensemble/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/zlib-1\n            .2.11-dtzzlwcy6jw7hjm7z2aip4eyed2rizzu/lib build/temp.linux-x86_64-\n            3.9/src/pmpi-vt-hyb.o -o build/lib.linux-x86_64-3.9/mpi4py/lib-pmpi\n            /libvt-hyb.so\n     119    /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/gcc: file not\n            recognized: file format not recognized\n>> 120    collect2: error: ld returned 1 exit status\n     121    warning: build_clib: building library \"vt-hyb\" failed\n     122\n     123    warning: build_clib: command '/p/vast1/koparasy/BUILD/spack_cluster\n            _installer/quartz/py-libensemble/spack_env_dir/linux-rhel7-broadwel\n            l/gcc-9.3.1/mpich-3.1.3-unrvf6ehypzcbivpfz3d3a6wwj7ab4bi/bin/mpicc'\n             failed with exit code 1",
    "te: declared here\n     206      334 | Py_DEPRECATED(3.0) PyAPI_FUNC(int) PyObject_CheckReadBuffer\n            (PyObject *obj);\n     207          |                                    ^~~~~~~~~~~~~~~~~~~~~~~~\n     208    In file included from src/MPI.c:3:\n     209    src/mpi4py.MPI.c: In function '__Pyx_GetException':\n>> 210    src/mpi4py.MPI.c:113087:24: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     211    113087 |     tmp_type = tstate->exc_type;\n     212           |                        ^~~~~~~~\n     213           |                        curexc_type\n  >> 214    src/mpi4py.MPI.c:113088:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "209    src/mpi4py.MPI.c: In function '__Pyx_GetException':\n  >> 210    src/mpi4py.MPI.c:113087:24: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     211    113087 |     tmp_type = tstate->exc_type;\n     212           |                        ^~~~~~~~\n     213           |                        curexc_type\n>> 214    src/mpi4py.MPI.c:113088:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     215    113088 |     tmp_value = tstate->exc_value;\n     216           |                         ^~~~~~~~~\n     217           |                         curexc_value\n  >> 218    src/mpi4py.MPI.c:113089:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "213           |                        curexc_type\n  >> 214    src/mpi4py.MPI.c:113088:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     215    113088 |     tmp_value = tstate->exc_value;\n     216           |                         ^~~~~~~~~\n     217           |                         curexc_value\n>> 218    src/mpi4py.MPI.c:113089:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     219    113089 |     tmp_tb = tstate->exc_traceback;\n     220           |                      ^~~~~~~~~~~~~\n     221           |                      curexc_traceback\n  >> 222    src/mpi4py.MPI.c:113090:13: error: 'PyThreadState' {aka 'struct _ts",
    ">> 218    src/mpi4py.MPI.c:113089:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     219    113089 |     tmp_tb = tstate->exc_traceback;\n     220           |                      ^~~~~~~~~~~~~\n     221           |                      curexc_traceback\n>> 222    src/mpi4py.MPI.c:113090:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     223    113090 |     tstate->exc_type = local_type;\n     224           |             ^~~~~~~~\n     225           |             curexc_type\n  >> 226    src/mpi4py.MPI.c:113091:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "221           |                      curexc_traceback\n  >> 222    src/mpi4py.MPI.c:113090:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     223    113090 |     tstate->exc_type = local_type;\n     224           |             ^~~~~~~~\n     225           |             curexc_type\n>> 226    src/mpi4py.MPI.c:113091:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     227    113091 |     tstate->exc_value = local_value;\n     228           |             ^~~~~~~~~\n     229           |             curexc_value\n  >> 230    src/mpi4py.MPI.c:113092:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "225           |             curexc_type\n  >> 226    src/mpi4py.MPI.c:113091:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     227    113091 |     tstate->exc_value = local_value;\n     228           |             ^~~~~~~~~\n     229           |             curexc_value\n>> 230    src/mpi4py.MPI.c:113092:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     231    113092 |     tstate->exc_traceback = local_tb;\n     232           |             ^~~~~~~~~~~~~\n     233           |             curexc_traceback\n     234    src/mpi4py.MPI.c: In function '__Pyx_Raise':",
    "note: declared here\n     397       33 | Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyCFunction_Call(\n            PyObject *, PyObject *, PyObject *);\n     398          |                                           ^~~~~~~~~~~~~~~~\n     399    In file included from src/MPI.c:3:\n     400    src/mpi4py.MPI.c: In function '__Pyx_ExceptionSave':\n>> 401    src/mpi4py.MPI.c:114569:21: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     402    114569 |     *type = tstate->exc_type;\n     403           |                     ^~~~~~~~\n     404           |                     curexc_type\n  >> 405    src/mpi4py.MPI.c:114570:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "400    src/mpi4py.MPI.c: In function '__Pyx_ExceptionSave':\n  >> 401    src/mpi4py.MPI.c:114569:21: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     402    114569 |     *type = tstate->exc_type;\n     403           |                     ^~~~~~~~\n     404           |                     curexc_type\n>> 405    src/mpi4py.MPI.c:114570:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     406    114570 |     *value = tstate->exc_value;\n     407           |                      ^~~~~~~~~\n     408           |                      curexc_value\n  >> 409    src/mpi4py.MPI.c:114571:19: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "404           |                     curexc_type\n  >> 405    src/mpi4py.MPI.c:114570:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     406    114570 |     *value = tstate->exc_value;\n     407           |                      ^~~~~~~~~\n     408           |                      curexc_value\n>> 409    src/mpi4py.MPI.c:114571:19: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     410    114571 |     *tb = tstate->exc_traceback;\n     411           |                   ^~~~~~~~~~~~~\n     412           |                   curexc_traceback\n     413    src/mpi4py.MPI.c: In function '__Pyx_ExceptionReset':",
    "'} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     410    114571 |     *tb = tstate->exc_traceback;\n     411           |                   ^~~~~~~~~~~~~\n     412           |                   curexc_traceback\n     413    src/mpi4py.MPI.c: In function '__Pyx_ExceptionReset':\n>> 414    src/mpi4py.MPI.c:114583:24: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     415    114583 |     tmp_type = tstate->exc_type;\n     416           |                        ^~~~~~~~\n     417           |                        curexc_type\n  >> 418    src/mpi4py.MPI.c:114584:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "413    src/mpi4py.MPI.c: In function '__Pyx_ExceptionReset':\n  >> 414    src/mpi4py.MPI.c:114583:24: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     415    114583 |     tmp_type = tstate->exc_type;\n     416           |                        ^~~~~~~~\n     417           |                        curexc_type\n>> 418    src/mpi4py.MPI.c:114584:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     419    114584 |     tmp_value = tstate->exc_value;\n     420           |                         ^~~~~~~~~\n     421           |                         curexc_value\n  >> 422    src/mpi4py.MPI.c:114585:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "417           |                        curexc_type\n  >> 418    src/mpi4py.MPI.c:114584:25: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     419    114584 |     tmp_value = tstate->exc_value;\n     420           |                         ^~~~~~~~~\n     421           |                         curexc_value\n>> 422    src/mpi4py.MPI.c:114585:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     423    114585 |     tmp_tb = tstate->exc_traceback;\n     424           |                      ^~~~~~~~~~~~~\n     425           |                      curexc_traceback\n  >> 426    src/mpi4py.MPI.c:114586:13: error: 'PyThreadState' {aka 'struct _ts",
    ">> 422    src/mpi4py.MPI.c:114585:22: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     423    114585 |     tmp_tb = tstate->exc_traceback;\n     424           |                      ^~~~~~~~~~~~~\n     425           |                      curexc_traceback\n>> 426    src/mpi4py.MPI.c:114586:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     427    114586 |     tstate->exc_type = type;\n     428           |             ^~~~~~~~\n     429           |             curexc_type\n  >> 430    src/mpi4py.MPI.c:114587:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?",
    "425           |                      curexc_traceback\n  >> 426    src/mpi4py.MPI.c:114586:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_type'; did you mean 'curexc_type'?\n     427    114586 |     tstate->exc_type = type;\n     428           |             ^~~~~~~~\n     429           |             curexc_type\n>> 430    src/mpi4py.MPI.c:114587:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     431    114587 |     tstate->exc_value = value;\n     432           |             ^~~~~~~~~\n     433           |             curexc_value\n  >> 434    src/mpi4py.MPI.c:114588:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb",
    "429           |             curexc_type\n  >> 430    src/mpi4py.MPI.c:114587:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_value'; did you mean 'curexc_value'?\n     431    114587 |     tstate->exc_value = value;\n     432           |             ^~~~~~~~~\n     433           |             curexc_value\n>> 434    src/mpi4py.MPI.c:114588:13: error: 'PyThreadState' {aka 'struct _ts\n            '} has no member named 'exc_traceback'; did you mean 'curexc_traceb\n            ack'?\n     435    114588 |     tstate->exc_traceback = tb;\n     436           |             ^~~~~~~~~~~~~\n     437           |             curexc_traceback\n  >> 438    error: command '/p/vast1/koparasy/BUILD/spack_cluster_installer/qua"
]