[
    "y/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inump\n             y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-bro\n             adwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/in\n             clude/python3.8 -c'\n     852     gcc: _configtest.c\n853     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     854         3 | #pragma clang diagnostic error \"-Wattributes\"\n     855           |\n     856     _configtest.c: In function '__declspec':\n  >> 857     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'",
    "858         5 | int __declspec(thread) foo;\n     859           |                        ^~~\n  >> 860     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     861         9 | {\n     862           | ^\n863     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     864         5 | int __declspec(thread) foo;\n     865           |     ^~~~~~~~~~\n  >> 866     _configtest.c:11: error: expected '{' at end of input\n     867        11 | }\n     868           |",
    "implicit-int]\n     864         5 | int __declspec(thread) foo;\n     865           |     ^~~~~~~~~~\n  >> 866     _configtest.c:11: error: expected '{' at end of input\n     867        11 | }\n     868           |\n869     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     870        11 | }\n     871           |\n     872     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     873         3 | #pragma clang diagnostic error \"-Wattributes\"",
    "867        11 | }\n     868           |\n     869     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     870        11 | }\n     871           |\n872     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     873         3 | #pragma clang diagnostic error \"-Wattributes\"\n     874           |\n     875     _configtest.c: In function '__declspec':\n  >> 876     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'",
    "877         5 | int __declspec(thread) foo;\n     878           |                        ^~~\n  >> 879     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     880         9 | {\n     881           | ^\n882     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     883         5 | int __declspec(thread) foo;\n     884           |     ^~~~~~~~~~\n  >> 885     _configtest.c:11: error: expected '{' at end of input\n     886        11 | }\n     887           |",
    "implicit-int]\n     883         5 | int __declspec(thread) foo;\n     884           |     ^~~~~~~~~~\n  >> 885     _configtest.c:11: error: expected '{' at end of input\n     886        11 | }\n     887           |\n888     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     889        11 | }\n     890           |\n     891     failure.\n\n     ...",
    "z56muf3y24twbgptm5fwkbrmdx/lib/python3.8/site-packages/setuptools/\n             command/install.py:34: SetuptoolsDeprecationWarning: setup.py inst\n             all is deprecated. Use build and pip and other standards-based too\n             ls.\n     4107      warnings.warn(\n     4108    numpy/random/mtrand/mtrand.c: In function 'PyInit_mtrand':\n4109    numpy/random/mtrand/mtrand.c:43380:3: warning: 'tp_print' is depre\n             cated [-Wdeprecated-declarations]\n     4110    43380 |   __pyx_type_6mtrand_RandomState.tp_print = 0;\n     4111          |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n     4112    In file included from /p/vast1/koparasy/BUILD/spack_cluster_instal\n             ler/quartz/nrm/spack_env_dir/linux-rhel7-broadwell/gcc-9.3.1/pytho\n             n-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/include/python3.8/object",
    "st.o -o _configtest\n     98      /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 99      /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.13.3-mleccg5l4ofx\n             klt7hdlf5djawhr4fa5u/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 100     collect2: error: ld returned 1 exit status\n     101     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 102     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.13.3-mleccg5l4ofx\n             klt7hdlf5djawhr4fa5u/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 103     collect2: error: ld returned 1 exit status",
    ">> 100     collect2: error: ld returned 1 exit status\n     101     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 102     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.13.3-mleccg5l4ofx\n             klt7hdlf5djawhr4fa5u/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 103     collect2: error: ld returned 1 exit status\n     104     failure.\n     105     removing: _configtest.c _configtest.o\n     106     C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     107",
    "y/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inump\n             y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-bro\n             adwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/in\n             clude/python3.8 -c'\n     156     gcc: _configtest.c\n>> 157     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory\n     158         1 | #include <sys/endian.h>\n     159           |          ^~~~~~~~~~~~~~\n     160     compilation terminated.\n  >> 161     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory",
    "156     gcc: _configtest.c\n  >> 157     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory\n     158         1 | #include <sys/endian.h>\n     159           |          ^~~~~~~~~~~~~~\n     160     compilation terminated.\n>> 161     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory\n     162         1 | #include <sys/endian.h>\n     163           |          ^~~~~~~~~~~~~~\n     164     compilation terminated.\n     165     failure.\n     166     removing: _configtest.c _configtest.o",
    "y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-bro\n             adwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/in\n             clude/python3.8 -c'\n     272     gcc: _configtest.c\n     273     _configtest.c: In function 'main':\n>> 274     _configtest.c:7:12: error: 'SIZEOF_LONGDOUBLE' undeclared (first u\n             se in this function); did you mean 'SIZEOF_LONG_DOUBLE'?\n     275         7 |     (void) SIZEOF_LONGDOUBLE;\n     276           |            ^~~~~~~~~~~~~~~~~\n     277           |            SIZEOF_LONG_DOUBLE\n     278     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "275         7 |     (void) SIZEOF_LONGDOUBLE;\n     276           |            ^~~~~~~~~~~~~~~~~\n     277           |            SIZEOF_LONG_DOUBLE\n     278     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in\n     279     _configtest.c: In function 'main':\n>> 280     _configtest.c:7:12: error: 'SIZEOF_LONGDOUBLE' undeclared (first u\n             se in this function); did you mean 'SIZEOF_LONG_DOUBLE'?\n     281         7 |     (void) SIZEOF_LONGDOUBLE;\n     282           |            ^~~~~~~~~~~~~~~~~\n     283           |            SIZEOF_LONG_DOUBLE\n     284     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "st.o -o _configtest\n     418     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 419     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.13.3-mleccg5l4ofx\n             klt7hdlf5djawhr4fa5u/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 420     collect2: error: ld returned 1 exit status\n     421     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 422     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.13.3-mleccg5l4ofx\n             klt7hdlf5djawhr4fa5u/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 423     collect2: error: ld returned 1 exit status",
    ">> 420     collect2: error: ld returned 1 exit status\n     421     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 422     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.13.3-mleccg5l4ofx\n             klt7hdlf5djawhr4fa5u/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 423     collect2: error: ld returned 1 exit status\n     424     failure.\n     425     removing: _configtest.c _configtest.o\n     426     C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     427",
    "852     gcc: _configtest.c\n     853     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     854         3 | #pragma clang diagnostic error \"-Wattributes\"\n     855           |\n     856     _configtest.c: In function '__declspec':\n>> 857     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     858         5 | int __declspec(thread) foo;\n     859           |                        ^~~\n  >> 860     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     861         9 | {",
    "855           |\n     856     _configtest.c: In function '__declspec':\n  >> 857     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     858         5 | int __declspec(thread) foo;\n     859           |                        ^~~\n>> 860     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     861         9 | {\n     862           | ^\n     863     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     864         5 | int __declspec(thread) foo;",
    "861         9 | {\n     862           | ^\n     863     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     864         5 | int __declspec(thread) foo;\n     865           |     ^~~~~~~~~~\n>> 866     _configtest.c:11: error: expected '{' at end of input\n     867        11 | }\n     868           |\n     869     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     870        11 | }\n     871           |",
    "871           |\n     872     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     873         3 | #pragma clang diagnostic error \"-Wattributes\"\n     874           |\n     875     _configtest.c: In function '__declspec':\n>> 876     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     877         5 | int __declspec(thread) foo;\n     878           |                        ^~~\n  >> 879     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     880         9 | {",
    "874           |\n     875     _configtest.c: In function '__declspec':\n  >> 876     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     877         5 | int __declspec(thread) foo;\n     878           |                        ^~~\n>> 879     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     880         9 | {\n     881           | ^\n     882     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     883         5 | int __declspec(thread) foo;",
    "880         9 | {\n     881           | ^\n     882     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     883         5 | int __declspec(thread) foo;\n     884           |     ^~~~~~~~~~\n>> 885     _configtest.c:11: error: expected '{' at end of input\n     886        11 | }\n     887           |\n     888     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     889        11 | }\n     890           |",
    "y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/nrm/spack_env_dir/linux-rhel7-bro\n             adwell/gcc-9.3.1/python-3.8.12-zq6ku5weq2g2lnidc7o5wtbfqu64d3ld/in\n             clude/python3.8 -c'\n     1218    gcc: _configtest.c\n     1219    _configtest.c: In function 'main':\n>> 1220    _configtest.c:8:12: error: 'HAVE_DECL_SIGNBIT' undeclared (first u\n             se in this function); did you mean 'HAVE_DECL_ISNAN'?\n     1221        8 |     (void) HAVE_DECL_SIGNBIT;\n     1222          |            ^~~~~~~~~~~~~~~~~\n     1223          |            HAVE_DECL_ISNAN\n     1224    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "1221        8 |     (void) HAVE_DECL_SIGNBIT;\n     1222          |            ^~~~~~~~~~~~~~~~~\n     1223          |            HAVE_DECL_ISNAN\n     1224    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in\n     1225    _configtest.c: In function 'main':\n>> 1226    _configtest.c:8:12: error: 'HAVE_DECL_SIGNBIT' undeclared (first u\n             se in this function); did you mean 'HAVE_DECL_ISNAN'?\n     1227        8 |     (void) HAVE_DECL_SIGNBIT;\n     1228          |            ^~~~~~~~~~~~~~~~~\n     1229          |            HAVE_DECL_ISNAN\n     1230    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "st.o -o _configtest\n     1812    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1813    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.13.3-mleccg5l4ofx\n             klt7hdlf5djawhr4fa5u/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 1814    collect2: error: ld returned 1 exit status\n     1815    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1816    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.13.3-mleccg5l4ofx\n             klt7hdlf5djawhr4fa5u/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 1817    collect2: error: ld returned 1 exit status",
    ">> 1814    collect2: error: ld returned 1 exit status\n     1815    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1816    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.13.3-mleccg5l4ofx\n             klt7hdlf5djawhr4fa5u/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 1817    collect2: error: ld returned 1 exit status\n     1818    failure.\n     1819    removing: _configtest.c _configtest.o\n     1820    C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     1821",
    "nidc7o5wtbfqu64d3ld/include/python3.8/cpython/object.h:260:30: not\n             e: declared here\n     4036      260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *,\n              int);\n     4037          |                              ^~~~~~~~\n     4038    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionSave':\n>> 4039    numpy/random/mtrand/mtrand.c:45208:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4040    45208 |     *type = tstate->exc_type;\n     4041          |                     ^~~~~~~~\n     4042          |                     curexc_type\n  >> 4043    numpy/random/mtrand/mtrand.c:45209:22: error: 'PyThreadState' {aka",
    ">> 4039    numpy/random/mtrand/mtrand.c:45208:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4040    45208 |     *type = tstate->exc_type;\n     4041          |                     ^~~~~~~~\n     4042          |                     curexc_type\n>> 4043    numpy/random/mtrand/mtrand.c:45209:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4044    45209 |     *value = tstate->exc_value;\n     4045          |                      ^~~~~~~~~\n     4046          |                      curexc_value\n  >> 4047    numpy/random/mtrand/mtrand.c:45210:19: error: 'PyThreadState' {aka",
    ">> 4043    numpy/random/mtrand/mtrand.c:45209:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4044    45209 |     *value = tstate->exc_value;\n     4045          |                      ^~~~~~~~~\n     4046          |                      curexc_value\n>> 4047    numpy/random/mtrand/mtrand.c:45210:19: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4048    45210 |     *tb = tstate->exc_traceback;\n     4049          |                   ^~~~~~~~~~~~~\n     4050          |                   curexc_traceback\n     4051    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4048    45210 |     *tb = tstate->exc_traceback;\n     4049          |                   ^~~~~~~~~~~~~\n     4050          |                   curexc_traceback\n     4051    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':\n>> 4052    numpy/random/mtrand/mtrand.c:45217:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4053    45217 |     tmp_type = tstate->exc_type;\n     4054          |                        ^~~~~~~~\n     4055          |                        curexc_type\n  >> 4056    numpy/random/mtrand/mtrand.c:45218:25: error: 'PyThreadState' {aka",
    ">> 4052    numpy/random/mtrand/mtrand.c:45217:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4053    45217 |     tmp_type = tstate->exc_type;\n     4054          |                        ^~~~~~~~\n     4055          |                        curexc_type\n>> 4056    numpy/random/mtrand/mtrand.c:45218:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4057    45218 |     tmp_value = tstate->exc_value;\n     4058          |                         ^~~~~~~~~\n     4059          |                         curexc_value\n  >> 4060    numpy/random/mtrand/mtrand.c:45219:22: error: 'PyThreadState' {aka",
    ">> 4056    numpy/random/mtrand/mtrand.c:45218:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4057    45218 |     tmp_value = tstate->exc_value;\n     4058          |                         ^~~~~~~~~\n     4059          |                         curexc_value\n>> 4060    numpy/random/mtrand/mtrand.c:45219:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4061    45219 |     tmp_tb = tstate->exc_traceback;\n     4062          |                      ^~~~~~~~~~~~~\n     4063          |                      curexc_traceback\n  >> 4064    numpy/random/mtrand/mtrand.c:45220:13: error: 'PyThreadState' {aka",
    ">> 4060    numpy/random/mtrand/mtrand.c:45219:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4061    45219 |     tmp_tb = tstate->exc_traceback;\n     4062          |                      ^~~~~~~~~~~~~\n     4063          |                      curexc_traceback\n>> 4064    numpy/random/mtrand/mtrand.c:45220:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4065    45220 |     tstate->exc_type = type;\n     4066          |             ^~~~~~~~\n     4067          |             curexc_type\n  >> 4068    numpy/random/mtrand/mtrand.c:45221:13: error: 'PyThreadState' {aka",
    ">> 4064    numpy/random/mtrand/mtrand.c:45220:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4065    45220 |     tstate->exc_type = type;\n     4066          |             ^~~~~~~~\n     4067          |             curexc_type\n>> 4068    numpy/random/mtrand/mtrand.c:45221:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4069    45221 |     tstate->exc_value = value;\n     4070          |             ^~~~~~~~~\n     4071          |             curexc_value\n  >> 4072    numpy/random/mtrand/mtrand.c:45222:13: error: 'PyThreadState' {aka",
    ">> 4068    numpy/random/mtrand/mtrand.c:45221:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4069    45221 |     tstate->exc_value = value;\n     4070          |             ^~~~~~~~~\n     4071          |             curexc_value\n>> 4072    numpy/random/mtrand/mtrand.c:45222:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4073    45222 |     tstate->exc_traceback = tb;\n     4074          |             ^~~~~~~~~~~~~\n     4075          |             curexc_traceback\n     4076    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4073    45222 |     tstate->exc_traceback = tb;\n     4074          |             ^~~~~~~~~~~~~\n     4075          |             curexc_traceback\n     4076    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':\n>> 4077    numpy/random/mtrand/mtrand.c:45277:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4078    45277 |     tmp_type = tstate->exc_type;\n     4079          |                        ^~~~~~~~\n     4080          |                        curexc_type\n  >> 4081    numpy/random/mtrand/mtrand.c:45278:25: error: 'PyThreadState' {aka",
    ">> 4077    numpy/random/mtrand/mtrand.c:45277:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4078    45277 |     tmp_type = tstate->exc_type;\n     4079          |                        ^~~~~~~~\n     4080          |                        curexc_type\n>> 4081    numpy/random/mtrand/mtrand.c:45278:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4082    45278 |     tmp_value = tstate->exc_value;\n     4083          |                         ^~~~~~~~~\n     4084          |                         curexc_value\n  >> 4085    numpy/random/mtrand/mtrand.c:45279:22: error: 'PyThreadState' {aka",
    ">> 4081    numpy/random/mtrand/mtrand.c:45278:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4082    45278 |     tmp_value = tstate->exc_value;\n     4083          |                         ^~~~~~~~~\n     4084          |                         curexc_value\n>> 4085    numpy/random/mtrand/mtrand.c:45279:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4086    45279 |     tmp_tb = tstate->exc_traceback;\n     4087          |                      ^~~~~~~~~~~~~\n     4088          |                      curexc_traceback\n  >> 4089    numpy/random/mtrand/mtrand.c:45280:13: error: 'PyThreadState' {aka",
    ">> 4085    numpy/random/mtrand/mtrand.c:45279:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4086    45279 |     tmp_tb = tstate->exc_traceback;\n     4087          |                      ^~~~~~~~~~~~~\n     4088          |                      curexc_traceback\n>> 4089    numpy/random/mtrand/mtrand.c:45280:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4090    45280 |     tstate->exc_type = local_type;\n     4091          |             ^~~~~~~~\n     4092          |             curexc_type\n  >> 4093    numpy/random/mtrand/mtrand.c:45281:13: error: 'PyThreadState' {aka",
    ">> 4089    numpy/random/mtrand/mtrand.c:45280:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4090    45280 |     tstate->exc_type = local_type;\n     4091          |             ^~~~~~~~\n     4092          |             curexc_type\n>> 4093    numpy/random/mtrand/mtrand.c:45281:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4094    45281 |     tstate->exc_value = local_value;\n     4095          |             ^~~~~~~~~\n     4096          |             curexc_value\n  >> 4097    numpy/random/mtrand/mtrand.c:45282:13: error: 'PyThreadState' {aka",
    ">> 4093    numpy/random/mtrand/mtrand.c:45281:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4094    45281 |     tstate->exc_value = local_value;\n     4095          |             ^~~~~~~~~\n     4096          |             curexc_value\n>> 4097    numpy/random/mtrand/mtrand.c:45282:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4098    45282 |     tstate->exc_traceback = local_tb;\n     4099          |             ^~~~~~~~~~~~~\n     4100          |             curexc_traceback\n     4101    Running from numpy source directory.",
    "nidc7o5wtbfqu64d3ld/include/python3.8/cpython/object.h:260:30: not\n             e: declared here\n     4117      260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *,\n              int);\n     4118          |                              ^~~~~~~~\n     4119    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionSave':\n>> 4120    numpy/random/mtrand/mtrand.c:45208:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4121    45208 |     *type = tstate->exc_type;\n     4122          |                     ^~~~~~~~\n     4123          |                     curexc_type\n  >> 4124    numpy/random/mtrand/mtrand.c:45209:22: error: 'PyThreadState' {aka",
    ">> 4120    numpy/random/mtrand/mtrand.c:45208:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4121    45208 |     *type = tstate->exc_type;\n     4122          |                     ^~~~~~~~\n     4123          |                     curexc_type\n>> 4124    numpy/random/mtrand/mtrand.c:45209:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4125    45209 |     *value = tstate->exc_value;\n     4126          |                      ^~~~~~~~~\n     4127          |                      curexc_value\n  >> 4128    numpy/random/mtrand/mtrand.c:45210:19: error: 'PyThreadState' {aka",
    ">> 4124    numpy/random/mtrand/mtrand.c:45209:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4125    45209 |     *value = tstate->exc_value;\n     4126          |                      ^~~~~~~~~\n     4127          |                      curexc_value\n>> 4128    numpy/random/mtrand/mtrand.c:45210:19: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4129    45210 |     *tb = tstate->exc_traceback;\n     4130          |                   ^~~~~~~~~~~~~\n     4131          |                   curexc_traceback\n     4132    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4129    45210 |     *tb = tstate->exc_traceback;\n     4130          |                   ^~~~~~~~~~~~~\n     4131          |                   curexc_traceback\n     4132    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':\n>> 4133    numpy/random/mtrand/mtrand.c:45217:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4134    45217 |     tmp_type = tstate->exc_type;\n     4135          |                        ^~~~~~~~\n     4136          |                        curexc_type\n  >> 4137    numpy/random/mtrand/mtrand.c:45218:25: error: 'PyThreadState' {aka",
    ">> 4133    numpy/random/mtrand/mtrand.c:45217:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4134    45217 |     tmp_type = tstate->exc_type;\n     4135          |                        ^~~~~~~~\n     4136          |                        curexc_type\n>> 4137    numpy/random/mtrand/mtrand.c:45218:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4138    45218 |     tmp_value = tstate->exc_value;\n     4139          |                         ^~~~~~~~~\n     4140          |                         curexc_value\n  >> 4141    numpy/random/mtrand/mtrand.c:45219:22: error: 'PyThreadState' {aka",
    ">> 4137    numpy/random/mtrand/mtrand.c:45218:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4138    45218 |     tmp_value = tstate->exc_value;\n     4139          |                         ^~~~~~~~~\n     4140          |                         curexc_value\n>> 4141    numpy/random/mtrand/mtrand.c:45219:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4142    45219 |     tmp_tb = tstate->exc_traceback;\n     4143          |                      ^~~~~~~~~~~~~\n     4144          |                      curexc_traceback\n  >> 4145    numpy/random/mtrand/mtrand.c:45220:13: error: 'PyThreadState' {aka",
    ">> 4141    numpy/random/mtrand/mtrand.c:45219:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4142    45219 |     tmp_tb = tstate->exc_traceback;\n     4143          |                      ^~~~~~~~~~~~~\n     4144          |                      curexc_traceback\n>> 4145    numpy/random/mtrand/mtrand.c:45220:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4146    45220 |     tstate->exc_type = type;\n     4147          |             ^~~~~~~~\n     4148          |             curexc_type\n  >> 4149    numpy/random/mtrand/mtrand.c:45221:13: error: 'PyThreadState' {aka",
    ">> 4145    numpy/random/mtrand/mtrand.c:45220:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4146    45220 |     tstate->exc_type = type;\n     4147          |             ^~~~~~~~\n     4148          |             curexc_type\n>> 4149    numpy/random/mtrand/mtrand.c:45221:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4150    45221 |     tstate->exc_value = value;\n     4151          |             ^~~~~~~~~\n     4152          |             curexc_value\n  >> 4153    numpy/random/mtrand/mtrand.c:45222:13: error: 'PyThreadState' {aka",
    ">> 4149    numpy/random/mtrand/mtrand.c:45221:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4150    45221 |     tstate->exc_value = value;\n     4151          |             ^~~~~~~~~\n     4152          |             curexc_value\n>> 4153    numpy/random/mtrand/mtrand.c:45222:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4154    45222 |     tstate->exc_traceback = tb;\n     4155          |             ^~~~~~~~~~~~~\n     4156          |             curexc_traceback\n     4157    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4154    45222 |     tstate->exc_traceback = tb;\n     4155          |             ^~~~~~~~~~~~~\n     4156          |             curexc_traceback\n     4157    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':\n>> 4158    numpy/random/mtrand/mtrand.c:45277:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4159    45277 |     tmp_type = tstate->exc_type;\n     4160          |                        ^~~~~~~~\n     4161          |                        curexc_type\n  >> 4162    numpy/random/mtrand/mtrand.c:45278:25: error: 'PyThreadState' {aka",
    ">> 4158    numpy/random/mtrand/mtrand.c:45277:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4159    45277 |     tmp_type = tstate->exc_type;\n     4160          |                        ^~~~~~~~\n     4161          |                        curexc_type\n>> 4162    numpy/random/mtrand/mtrand.c:45278:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4163    45278 |     tmp_value = tstate->exc_value;\n     4164          |                         ^~~~~~~~~\n     4165          |                         curexc_value\n  >> 4166    numpy/random/mtrand/mtrand.c:45279:22: error: 'PyThreadState' {aka",
    ">> 4162    numpy/random/mtrand/mtrand.c:45278:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4163    45278 |     tmp_value = tstate->exc_value;\n     4164          |                         ^~~~~~~~~\n     4165          |                         curexc_value\n>> 4166    numpy/random/mtrand/mtrand.c:45279:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4167    45279 |     tmp_tb = tstate->exc_traceback;\n     4168          |                      ^~~~~~~~~~~~~\n     4169          |                      curexc_traceback\n  >> 4170    numpy/random/mtrand/mtrand.c:45280:13: error: 'PyThreadState' {aka",
    ">> 4166    numpy/random/mtrand/mtrand.c:45279:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4167    45279 |     tmp_tb = tstate->exc_traceback;\n     4168          |                      ^~~~~~~~~~~~~\n     4169          |                      curexc_traceback\n>> 4170    numpy/random/mtrand/mtrand.c:45280:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4171    45280 |     tstate->exc_type = local_type;\n     4172          |             ^~~~~~~~\n     4173          |             curexc_type\n  >> 4174    numpy/random/mtrand/mtrand.c:45281:13: error: 'PyThreadState' {aka",
    ">> 4170    numpy/random/mtrand/mtrand.c:45280:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4171    45280 |     tstate->exc_type = local_type;\n     4172          |             ^~~~~~~~\n     4173          |             curexc_type\n>> 4174    numpy/random/mtrand/mtrand.c:45281:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4175    45281 |     tstate->exc_value = local_value;\n     4176          |             ^~~~~~~~~\n     4177          |             curexc_value\n  >> 4178    numpy/random/mtrand/mtrand.c:45282:13: error: 'PyThreadState' {aka",
    ">> 4174    numpy/random/mtrand/mtrand.c:45281:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4175    45281 |     tstate->exc_value = local_value;\n     4176          |             ^~~~~~~~~\n     4177          |             curexc_value\n>> 4178    numpy/random/mtrand/mtrand.c:45282:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4179    45282 |     tstate->exc_traceback = local_tb;\n     4180          |             ^~~~~~~~~~~~~\n     4181          |             curexc_traceback\n  >> 4182    error: Command \"/p/vast1/koparasy/BUILD/head/spack/lib/spack/env/g"
]