[
    "dc7o5wtbfqu64d3ld/include/python3.8/cpython/object.h:260:30: note:\n            declared here\n     526      260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *,\n            int);\n     527          |                              ^~~~~~~~\n     528    ext/_yaml.c: In function '__Pyx__ExceptionSave':\n>> 529    ext/_yaml.c:24143:21: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_type'; did you mean 'curexc_type'?\n     530    24143 |     *type = tstate->exc_type;\n     531          |                     ^~~~~~~~\n     532          |                     curexc_type\n  >> 533    ext/_yaml.c:24144:22: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_value'; did you mean 'curexc_value'?",
    "528    ext/_yaml.c: In function '__Pyx__ExceptionSave':\n  >> 529    ext/_yaml.c:24143:21: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_type'; did you mean 'curexc_type'?\n     530    24143 |     *type = tstate->exc_type;\n     531          |                     ^~~~~~~~\n     532          |                     curexc_type\n>> 533    ext/_yaml.c:24144:22: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_value'; did you mean 'curexc_value'?\n     534    24144 |     *value = tstate->exc_value;\n     535          |                      ^~~~~~~~~\n     536          |                      curexc_value\n  >> 537    ext/_yaml.c:24145:19: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_traceback'; did you mean 'curexc_traceback'?",
    "532          |                     curexc_type\n  >> 533    ext/_yaml.c:24144:22: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_value'; did you mean 'curexc_value'?\n     534    24144 |     *value = tstate->exc_value;\n     535          |                      ^~~~~~~~~\n     536          |                      curexc_value\n>> 537    ext/_yaml.c:24145:19: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_traceback'; did you mean 'curexc_traceback'?\n     538    24145 |     *tb = tstate->exc_traceback;\n     539          |                   ^~~~~~~~~~~~~\n     540          |                   curexc_traceback\n     541    ext/_yaml.c: In function '__Pyx__ExceptionReset':\n  >> 542    ext/_yaml.c:24152:24: error: 'PyThreadState' {aka 'struct _ts'} has",
    ">> 537    ext/_yaml.c:24145:19: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_traceback'; did you mean 'curexc_traceback'?\n     538    24145 |     *tb = tstate->exc_traceback;\n     539          |                   ^~~~~~~~~~~~~\n     540          |                   curexc_traceback\n     541    ext/_yaml.c: In function '__Pyx__ExceptionReset':\n>> 542    ext/_yaml.c:24152:24: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_type'; did you mean 'curexc_type'?\n     543    24152 |     tmp_type = tstate->exc_type;\n     544          |                        ^~~~~~~~\n     545          |                        curexc_type\n  >> 546    ext/_yaml.c:24153:25: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_value'; did you mean 'curexc_value'?",
    "541    ext/_yaml.c: In function '__Pyx__ExceptionReset':\n  >> 542    ext/_yaml.c:24152:24: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_type'; did you mean 'curexc_type'?\n     543    24152 |     tmp_type = tstate->exc_type;\n     544          |                        ^~~~~~~~\n     545          |                        curexc_type\n>> 546    ext/_yaml.c:24153:25: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_value'; did you mean 'curexc_value'?\n     547    24153 |     tmp_value = tstate->exc_value;\n     548          |                         ^~~~~~~~~\n     549          |                         curexc_value\n  >> 550    ext/_yaml.c:24154:22: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_traceback'; did you mean 'curexc_traceback'?",
    "545          |                        curexc_type\n  >> 546    ext/_yaml.c:24153:25: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_value'; did you mean 'curexc_value'?\n     547    24153 |     tmp_value = tstate->exc_value;\n     548          |                         ^~~~~~~~~\n     549          |                         curexc_value\n>> 550    ext/_yaml.c:24154:22: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_traceback'; did you mean 'curexc_traceback'?\n     551    24154 |     tmp_tb = tstate->exc_traceback;\n     552          |                      ^~~~~~~~~~~~~\n     553          |                      curexc_traceback\n  >> 554    ext/_yaml.c:24155:13: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_type'; did you mean 'curexc_type'?",
    "549          |                         curexc_value\n  >> 550    ext/_yaml.c:24154:22: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_traceback'; did you mean 'curexc_traceback'?\n     551    24154 |     tmp_tb = tstate->exc_traceback;\n     552          |                      ^~~~~~~~~~~~~\n     553          |                      curexc_traceback\n>> 554    ext/_yaml.c:24155:13: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_type'; did you mean 'curexc_type'?\n     555    24155 |     tstate->exc_type = type;\n     556          |             ^~~~~~~~\n     557          |             curexc_type\n  >> 558    ext/_yaml.c:24156:13: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_value'; did you mean 'curexc_value'?",
    "553          |                      curexc_traceback\n  >> 554    ext/_yaml.c:24155:13: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_type'; did you mean 'curexc_type'?\n     555    24155 |     tstate->exc_type = type;\n     556          |             ^~~~~~~~\n     557          |             curexc_type\n>> 558    ext/_yaml.c:24156:13: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_value'; did you mean 'curexc_value'?\n     559    24156 |     tstate->exc_value = value;\n     560          |             ^~~~~~~~~\n     561          |             curexc_value\n  >> 562    ext/_yaml.c:24157:13: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_traceback'; did you mean 'curexc_traceback'?",
    "557          |             curexc_type\n  >> 558    ext/_yaml.c:24156:13: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_value'; did you mean 'curexc_value'?\n     559    24156 |     tstate->exc_value = value;\n     560          |             ^~~~~~~~~\n     561          |             curexc_value\n>> 562    ext/_yaml.c:24157:13: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_traceback'; did you mean 'curexc_traceback'?\n     563    24157 |     tstate->exc_traceback = tb;\n     564          |             ^~~~~~~~~~~~~\n     565          |             curexc_traceback\n     566    ext/_yaml.c: In function '__Pyx__GetException':\n  >> 567    ext/_yaml.c:24212:24: error: 'PyThreadState' {aka 'struct _ts'} has",
    ">> 562    ext/_yaml.c:24157:13: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_traceback'; did you mean 'curexc_traceback'?\n     563    24157 |     tstate->exc_traceback = tb;\n     564          |             ^~~~~~~~~~~~~\n     565          |             curexc_traceback\n     566    ext/_yaml.c: In function '__Pyx__GetException':\n>> 567    ext/_yaml.c:24212:24: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_type'; did you mean 'curexc_type'?\n     568    24212 |     tmp_type = tstate->exc_type;\n     569          |                        ^~~~~~~~\n     570          |                        curexc_type\n  >> 571    ext/_yaml.c:24213:25: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_value'; did you mean 'curexc_value'?",
    "566    ext/_yaml.c: In function '__Pyx__GetException':\n  >> 567    ext/_yaml.c:24212:24: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_type'; did you mean 'curexc_type'?\n     568    24212 |     tmp_type = tstate->exc_type;\n     569          |                        ^~~~~~~~\n     570          |                        curexc_type\n>> 571    ext/_yaml.c:24213:25: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_value'; did you mean 'curexc_value'?\n     572    24213 |     tmp_value = tstate->exc_value;\n     573          |                         ^~~~~~~~~\n     574          |                         curexc_value\n  >> 575    ext/_yaml.c:24214:22: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_traceback'; did you mean 'curexc_traceback'?",
    "570          |                        curexc_type\n  >> 571    ext/_yaml.c:24213:25: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_value'; did you mean 'curexc_value'?\n     572    24213 |     tmp_value = tstate->exc_value;\n     573          |                         ^~~~~~~~~\n     574          |                         curexc_value\n>> 575    ext/_yaml.c:24214:22: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_traceback'; did you mean 'curexc_traceback'?\n     576    24214 |     tmp_tb = tstate->exc_traceback;\n     577          |                      ^~~~~~~~~~~~~\n     578          |                      curexc_traceback\n  >> 579    ext/_yaml.c:24215:13: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_type'; did you mean 'curexc_type'?",
    "574          |                         curexc_value\n  >> 575    ext/_yaml.c:24214:22: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_traceback'; did you mean 'curexc_traceback'?\n     576    24214 |     tmp_tb = tstate->exc_traceback;\n     577          |                      ^~~~~~~~~~~~~\n     578          |                      curexc_traceback\n>> 579    ext/_yaml.c:24215:13: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_type'; did you mean 'curexc_type'?\n     580    24215 |     tstate->exc_type = local_type;\n     581          |             ^~~~~~~~\n     582          |             curexc_type\n  >> 583    ext/_yaml.c:24216:13: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_value'; did you mean 'curexc_value'?",
    "578          |                      curexc_traceback\n  >> 579    ext/_yaml.c:24215:13: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_type'; did you mean 'curexc_type'?\n     580    24215 |     tstate->exc_type = local_type;\n     581          |             ^~~~~~~~\n     582          |             curexc_type\n>> 583    ext/_yaml.c:24216:13: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_value'; did you mean 'curexc_value'?\n     584    24216 |     tstate->exc_value = local_value;\n     585          |             ^~~~~~~~~\n     586          |             curexc_value\n  >> 587    ext/_yaml.c:24217:13: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_traceback'; did you mean 'curexc_traceback'?",
    "582          |             curexc_type\n  >> 583    ext/_yaml.c:24216:13: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_value'; did you mean 'curexc_value'?\n     584    24216 |     tstate->exc_value = local_value;\n     585          |             ^~~~~~~~~\n     586          |             curexc_value\n>> 587    ext/_yaml.c:24217:13: error: 'PyThreadState' {aka 'struct _ts'} has\n             no member named 'exc_traceback'; did you mean 'curexc_traceback'?\n     588    24217 |     tstate->exc_traceback = local_tb;\n     589          |             ^~~~~~~~~~~~~\n     590          |             curexc_traceback\n  >> 591    error: command '/p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gc\n            c/gcc' failed with exit status 1"
]