[
    "y/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inump\n             y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/py-libensemble/spack_env_dir/linu\n             x-rhel7-broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxwx2ytcv7sd\n             3g35si6/include/python3.9 -c'\n     869     gcc: _configtest.c\n870     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     871         3 | #pragma clang diagnostic error \"-Wattributes\"\n     872           |\n     873     _configtest.c: In function '__declspec':\n  >> 874     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'",
    "875         5 | int __declspec(thread) foo;\n     876           |                        ^~~\n  >> 877     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     878         9 | {\n     879           | ^\n880     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     881         5 | int __declspec(thread) foo;\n     882           |     ^~~~~~~~~~\n  >> 883     _configtest.c:11: error: expected '{' at end of input\n     884        11 | }\n     885           |",
    "implicit-int]\n     881         5 | int __declspec(thread) foo;\n     882           |     ^~~~~~~~~~\n  >> 883     _configtest.c:11: error: expected '{' at end of input\n     884        11 | }\n     885           |\n886     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     887        11 | }\n     888           |\n     889     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     890         3 | #pragma clang diagnostic error \"-Wattributes\"",
    "884        11 | }\n     885           |\n     886     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     887        11 | }\n     888           |\n889     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     890         3 | #pragma clang diagnostic error \"-Wattributes\"\n     891           |\n     892     _configtest.c: In function '__declspec':\n  >> 893     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'",
    "894         5 | int __declspec(thread) foo;\n     895           |                        ^~~\n  >> 896     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     897         9 | {\n     898           | ^\n899     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     900         5 | int __declspec(thread) foo;\n     901           |     ^~~~~~~~~~\n  >> 902     _configtest.c:11: error: expected '{' at end of input\n     903        11 | }\n     904           |",
    "implicit-int]\n     900         5 | int __declspec(thread) foo;\n     901           |     ^~~~~~~~~~\n  >> 902     _configtest.c:11: error: expected '{' at end of input\n     903        11 | }\n     904           |\n905     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     906        11 | }\n     907           |\n     908     failure.\n\n     ...",
    ">> 4399    numpy/random/mtrand/mtrand.c:43644:33: error: 'PyTypeObject' {aka\n             'struct _typeobject'} has no member named 'tp_print'\n     4400    43644 |   __pyx_type_6mtrand_RandomState.tp_print = 0;\n     4401          |                                 ^\n     4402    numpy/random/mtrand/mtrand.c: In function '__Pyx_ParseOptionalKeyw\n             ords':\n4403    numpy/random/mtrand/mtrand.c:45175:21: warning: '_PyUnicode_get_ws\n             tr_length' is deprecated [-Wdeprecated-declarations]\n     4404    45175 |                     (PyUnicode_GET_SIZE(**name) != PyUnico\n             de_GET_SIZE(key)) ? 1 :\n     4405          |                     ^\n\n     ...",
    ">> 4575    numpy/random/mtrand/mtrand.c:43644:33: error: 'PyTypeObject' {aka\n             'struct _typeobject'} has no member named 'tp_print'\n     4576    43644 |   __pyx_type_6mtrand_RandomState.tp_print = 0;\n     4577          |                                 ^\n     4578    numpy/random/mtrand/mtrand.c: In function '__Pyx_ParseOptionalKeyw\n             ords':\n4579    numpy/random/mtrand/mtrand.c:45175:21: warning: '_PyUnicode_get_ws\n             tr_length' is deprecated [-Wdeprecated-declarations]\n     4580    45175 |                     (PyUnicode_GET_SIZE(**name) != PyUnico\n             de_GET_SIZE(key)) ? 1 :\n     4581          |                     ^\n\n     ...",
    "st.o -o _configtest\n     115     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 116     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.2-idultfc7vj5o\n             57xh25muozpbqgzn4xll/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 117     collect2: error: ld returned 1 exit status\n     118     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 119     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.2-idultfc7vj5o\n             57xh25muozpbqgzn4xll/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 120     collect2: error: ld returned 1 exit status",
    ">> 117     collect2: error: ld returned 1 exit status\n     118     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 119     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.2-idultfc7vj5o\n             57xh25muozpbqgzn4xll/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 120     collect2: error: ld returned 1 exit status\n     121     failure.\n     122     removing: _configtest.c _configtest.o\n     123     C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     124",
    "y/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inump\n             y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/py-libensemble/spack_env_dir/linu\n             x-rhel7-broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxwx2ytcv7sd\n             3g35si6/include/python3.9 -c'\n     173     gcc: _configtest.c\n>> 174     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory\n     175         1 | #include <sys/endian.h>\n     176           |          ^~~~~~~~~~~~~~\n     177     compilation terminated.\n  >> 178     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory",
    "173     gcc: _configtest.c\n  >> 174     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory\n     175         1 | #include <sys/endian.h>\n     176           |          ^~~~~~~~~~~~~~\n     177     compilation terminated.\n>> 178     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory\n     179         1 | #include <sys/endian.h>\n     180           |          ^~~~~~~~~~~~~~\n     181     compilation terminated.\n     182     failure.\n     183     removing: _configtest.c _configtest.o",
    "y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/py-libensemble/spack_env_dir/linu\n             x-rhel7-broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxwx2ytcv7sd\n             3g35si6/include/python3.9 -c'\n     289     gcc: _configtest.c\n     290     _configtest.c: In function 'main':\n>> 291     _configtest.c:7:12: error: 'SIZEOF_LONGDOUBLE' undeclared (first u\n             se in this function); did you mean 'SIZEOF_LONG_DOUBLE'?\n     292         7 |     (void) SIZEOF_LONGDOUBLE;\n     293           |            ^~~~~~~~~~~~~~~~~\n     294           |            SIZEOF_LONG_DOUBLE\n     295     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "292         7 |     (void) SIZEOF_LONGDOUBLE;\n     293           |            ^~~~~~~~~~~~~~~~~\n     294           |            SIZEOF_LONG_DOUBLE\n     295     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in\n     296     _configtest.c: In function 'main':\n>> 297     _configtest.c:7:12: error: 'SIZEOF_LONGDOUBLE' undeclared (first u\n             se in this function); did you mean 'SIZEOF_LONG_DOUBLE'?\n     298         7 |     (void) SIZEOF_LONGDOUBLE;\n     299           |            ^~~~~~~~~~~~~~~~~\n     300           |            SIZEOF_LONG_DOUBLE\n     301     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "st.o -o _configtest\n     435     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 436     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.2-idultfc7vj5o\n             57xh25muozpbqgzn4xll/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 437     collect2: error: ld returned 1 exit status\n     438     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 439     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.2-idultfc7vj5o\n             57xh25muozpbqgzn4xll/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 440     collect2: error: ld returned 1 exit status",
    ">> 437     collect2: error: ld returned 1 exit status\n     438     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 439     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.2-idultfc7vj5o\n             57xh25muozpbqgzn4xll/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 440     collect2: error: ld returned 1 exit status\n     441     failure.\n     442     removing: _configtest.c _configtest.o\n     443     C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     444",
    "869     gcc: _configtest.c\n     870     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     871         3 | #pragma clang diagnostic error \"-Wattributes\"\n     872           |\n     873     _configtest.c: In function '__declspec':\n>> 874     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     875         5 | int __declspec(thread) foo;\n     876           |                        ^~~\n  >> 877     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     878         9 | {",
    "872           |\n     873     _configtest.c: In function '__declspec':\n  >> 874     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     875         5 | int __declspec(thread) foo;\n     876           |                        ^~~\n>> 877     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     878         9 | {\n     879           | ^\n     880     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     881         5 | int __declspec(thread) foo;",
    "878         9 | {\n     879           | ^\n     880     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     881         5 | int __declspec(thread) foo;\n     882           |     ^~~~~~~~~~\n>> 883     _configtest.c:11: error: expected '{' at end of input\n     884        11 | }\n     885           |\n     886     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     887        11 | }\n     888           |",
    "888           |\n     889     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     890         3 | #pragma clang diagnostic error \"-Wattributes\"\n     891           |\n     892     _configtest.c: In function '__declspec':\n>> 893     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     894         5 | int __declspec(thread) foo;\n     895           |                        ^~~\n  >> 896     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     897         9 | {",
    "891           |\n     892     _configtest.c: In function '__declspec':\n  >> 893     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     894         5 | int __declspec(thread) foo;\n     895           |                        ^~~\n>> 896     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     897         9 | {\n     898           | ^\n     899     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     900         5 | int __declspec(thread) foo;",
    "897         9 | {\n     898           | ^\n     899     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     900         5 | int __declspec(thread) foo;\n     901           |     ^~~~~~~~~~\n>> 902     _configtest.c:11: error: expected '{' at end of input\n     903        11 | }\n     904           |\n     905     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     906        11 | }\n     907           |",
    "y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/py-libensemble/spack_env_dir/linu\n             x-rhel7-broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxwx2ytcv7sd\n             3g35si6/include/python3.9 -c'\n     1235    gcc: _configtest.c\n     1236    _configtest.c: In function 'main':\n>> 1237    _configtest.c:8:12: error: 'HAVE_DECL_SIGNBIT' undeclared (first u\n             se in this function); did you mean 'HAVE_DECL_ISNAN'?\n     1238        8 |     (void) HAVE_DECL_SIGNBIT;\n     1239          |            ^~~~~~~~~~~~~~~~~\n     1240          |            HAVE_DECL_ISNAN\n     1241    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "1238        8 |     (void) HAVE_DECL_SIGNBIT;\n     1239          |            ^~~~~~~~~~~~~~~~~\n     1240          |            HAVE_DECL_ISNAN\n     1241    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in\n     1242    _configtest.c: In function 'main':\n>> 1243    _configtest.c:8:12: error: 'HAVE_DECL_SIGNBIT' undeclared (first u\n             se in this function); did you mean 'HAVE_DECL_ISNAN'?\n     1244        8 |     (void) HAVE_DECL_SIGNBIT;\n     1245          |            ^~~~~~~~~~~~~~~~~\n     1246          |            HAVE_DECL_ISNAN\n     1247    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "st.o -o _configtest\n     1829    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1830    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.2-idultfc7vj5o\n             57xh25muozpbqgzn4xll/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 1831    collect2: error: ld returned 1 exit status\n     1832    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1833    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.2-idultfc7vj5o\n             57xh25muozpbqgzn4xll/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 1834    collect2: error: ld returned 1 exit status",
    ">> 1831    collect2: error: ld returned 1 exit status\n     1832    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1833    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.2-idultfc7vj5o\n             57xh25muozpbqgzn4xll/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 1834    collect2: error: ld returned 1 exit status\n     1835    failure.\n     1836    removing: _configtest.c _configtest.o\n     1837    C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     1838",
    "c/npymath -Ibuild/src.linux-x86_64-3.9/numpy/core/src/private -Ibu\n             ild/src.linux-x86_64-3.9/numpy/core/src/npymath -Ibuild/src.linux-\n             x86_64-3.9/numpy/core/src/private -Ibuild/src.linux-x86_64-3.9/num\n             py/core/src/npymath -c'\n     4397    gcc: numpy/random/mtrand/mtrand.c\n     4398    numpy/random/mtrand/mtrand.c: In function 'PyInit_mtrand':\n>> 4399    numpy/random/mtrand/mtrand.c:43644:33: error: 'PyTypeObject' {aka\n             'struct _typeobject'} has no member named 'tp_print'\n     4400    43644 |   __pyx_type_6mtrand_RandomState.tp_print = 0;\n     4401          |                                 ^\n     4402    numpy/random/mtrand/mtrand.c: In function '__Pyx_ParseOptionalKeyw\n             ords':\n     4403    numpy/random/mtrand/mtrand.c:45175:21: warning: '_PyUnicode_get_ws",
    "6m4utiyrsvuxwx2ytcv7sd3g35si6/include/python3.9/cpython/unicodeobj\n             ect.h:446:26: note: declared here\n     4509      446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObje\n             ct *op) {\n     4510          |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~\n     4511    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionSave':\n>> 4512    numpy/random/mtrand/mtrand.c:45472:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4513    45472 |     *type = tstate->exc_type;\n     4514          |                     ^~~~~~~~\n     4515          |                     curexc_type\n  >> 4516    numpy/random/mtrand/mtrand.c:45473:22: error: 'PyThreadState' {aka",
    ">> 4512    numpy/random/mtrand/mtrand.c:45472:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4513    45472 |     *type = tstate->exc_type;\n     4514          |                     ^~~~~~~~\n     4515          |                     curexc_type\n>> 4516    numpy/random/mtrand/mtrand.c:45473:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4517    45473 |     *value = tstate->exc_value;\n     4518          |                      ^~~~~~~~~\n     4519          |                      curexc_value\n  >> 4520    numpy/random/mtrand/mtrand.c:45474:19: error: 'PyThreadState' {aka",
    ">> 4516    numpy/random/mtrand/mtrand.c:45473:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4517    45473 |     *value = tstate->exc_value;\n     4518          |                      ^~~~~~~~~\n     4519          |                      curexc_value\n>> 4520    numpy/random/mtrand/mtrand.c:45474:19: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4521    45474 |     *tb = tstate->exc_traceback;\n     4522          |                   ^~~~~~~~~~~~~\n     4523          |                   curexc_traceback\n     4524    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4521    45474 |     *tb = tstate->exc_traceback;\n     4522          |                   ^~~~~~~~~~~~~\n     4523          |                   curexc_traceback\n     4524    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':\n>> 4525    numpy/random/mtrand/mtrand.c:45481:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4526    45481 |     tmp_type = tstate->exc_type;\n     4527          |                        ^~~~~~~~\n     4528          |                        curexc_type\n  >> 4529    numpy/random/mtrand/mtrand.c:45482:25: error: 'PyThreadState' {aka",
    ">> 4525    numpy/random/mtrand/mtrand.c:45481:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4526    45481 |     tmp_type = tstate->exc_type;\n     4527          |                        ^~~~~~~~\n     4528          |                        curexc_type\n>> 4529    numpy/random/mtrand/mtrand.c:45482:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4530    45482 |     tmp_value = tstate->exc_value;\n     4531          |                         ^~~~~~~~~\n     4532          |                         curexc_value\n  >> 4533    numpy/random/mtrand/mtrand.c:45483:22: error: 'PyThreadState' {aka",
    ">> 4529    numpy/random/mtrand/mtrand.c:45482:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4530    45482 |     tmp_value = tstate->exc_value;\n     4531          |                         ^~~~~~~~~\n     4532          |                         curexc_value\n>> 4533    numpy/random/mtrand/mtrand.c:45483:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4534    45483 |     tmp_tb = tstate->exc_traceback;\n     4535          |                      ^~~~~~~~~~~~~\n     4536          |                      curexc_traceback\n  >> 4537    numpy/random/mtrand/mtrand.c:45484:13: error: 'PyThreadState' {aka",
    ">> 4533    numpy/random/mtrand/mtrand.c:45483:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4534    45483 |     tmp_tb = tstate->exc_traceback;\n     4535          |                      ^~~~~~~~~~~~~\n     4536          |                      curexc_traceback\n>> 4537    numpy/random/mtrand/mtrand.c:45484:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4538    45484 |     tstate->exc_type = type;\n     4539          |             ^~~~~~~~\n     4540          |             curexc_type\n  >> 4541    numpy/random/mtrand/mtrand.c:45485:13: error: 'PyThreadState' {aka",
    ">> 4537    numpy/random/mtrand/mtrand.c:45484:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4538    45484 |     tstate->exc_type = type;\n     4539          |             ^~~~~~~~\n     4540          |             curexc_type\n>> 4541    numpy/random/mtrand/mtrand.c:45485:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4542    45485 |     tstate->exc_value = value;\n     4543          |             ^~~~~~~~~\n     4544          |             curexc_value\n  >> 4545    numpy/random/mtrand/mtrand.c:45486:13: error: 'PyThreadState' {aka",
    ">> 4541    numpy/random/mtrand/mtrand.c:45485:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4542    45485 |     tstate->exc_value = value;\n     4543          |             ^~~~~~~~~\n     4544          |             curexc_value\n>> 4545    numpy/random/mtrand/mtrand.c:45486:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4546    45486 |     tstate->exc_traceback = tb;\n     4547          |             ^~~~~~~~~~~~~\n     4548          |             curexc_traceback\n     4549    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4546    45486 |     tstate->exc_traceback = tb;\n     4547          |             ^~~~~~~~~~~~~\n     4548          |             curexc_traceback\n     4549    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':\n>> 4550    numpy/random/mtrand/mtrand.c:45541:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4551    45541 |     tmp_type = tstate->exc_type;\n     4552          |                        ^~~~~~~~\n     4553          |                        curexc_type\n  >> 4554    numpy/random/mtrand/mtrand.c:45542:25: error: 'PyThreadState' {aka",
    ">> 4550    numpy/random/mtrand/mtrand.c:45541:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4551    45541 |     tmp_type = tstate->exc_type;\n     4552          |                        ^~~~~~~~\n     4553          |                        curexc_type\n>> 4554    numpy/random/mtrand/mtrand.c:45542:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4555    45542 |     tmp_value = tstate->exc_value;\n     4556          |                         ^~~~~~~~~\n     4557          |                         curexc_value\n  >> 4558    numpy/random/mtrand/mtrand.c:45543:22: error: 'PyThreadState' {aka",
    ">> 4554    numpy/random/mtrand/mtrand.c:45542:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4555    45542 |     tmp_value = tstate->exc_value;\n     4556          |                         ^~~~~~~~~\n     4557          |                         curexc_value\n>> 4558    numpy/random/mtrand/mtrand.c:45543:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4559    45543 |     tmp_tb = tstate->exc_traceback;\n     4560          |                      ^~~~~~~~~~~~~\n     4561          |                      curexc_traceback\n  >> 4562    numpy/random/mtrand/mtrand.c:45544:13: error: 'PyThreadState' {aka",
    ">> 4558    numpy/random/mtrand/mtrand.c:45543:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4559    45543 |     tmp_tb = tstate->exc_traceback;\n     4560          |                      ^~~~~~~~~~~~~\n     4561          |                      curexc_traceback\n>> 4562    numpy/random/mtrand/mtrand.c:45544:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4563    45544 |     tstate->exc_type = local_type;\n     4564          |             ^~~~~~~~\n     4565          |             curexc_type\n  >> 4566    numpy/random/mtrand/mtrand.c:45545:13: error: 'PyThreadState' {aka",
    ">> 4562    numpy/random/mtrand/mtrand.c:45544:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4563    45544 |     tstate->exc_type = local_type;\n     4564          |             ^~~~~~~~\n     4565          |             curexc_type\n>> 4566    numpy/random/mtrand/mtrand.c:45545:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4567    45545 |     tstate->exc_value = local_value;\n     4568          |             ^~~~~~~~~\n     4569          |             curexc_value\n  >> 4570    numpy/random/mtrand/mtrand.c:45546:13: error: 'PyThreadState' {aka",
    ">> 4566    numpy/random/mtrand/mtrand.c:45545:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4567    45545 |     tstate->exc_value = local_value;\n     4568          |             ^~~~~~~~~\n     4569          |             curexc_value\n>> 4570    numpy/random/mtrand/mtrand.c:45546:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4571    45546 |     tstate->exc_traceback = local_tb;\n     4572          |             ^~~~~~~~~~~~~\n     4573          |             curexc_traceback\n     4574    numpy/random/mtrand/mtrand.c: In function 'PyInit_mtrand':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4571    45546 |     tstate->exc_traceback = local_tb;\n     4572          |             ^~~~~~~~~~~~~\n     4573          |             curexc_traceback\n     4574    numpy/random/mtrand/mtrand.c: In function 'PyInit_mtrand':\n>> 4575    numpy/random/mtrand/mtrand.c:43644:33: error: 'PyTypeObject' {aka\n             'struct _typeobject'} has no member named 'tp_print'\n     4576    43644 |   __pyx_type_6mtrand_RandomState.tp_print = 0;\n     4577          |                                 ^\n     4578    numpy/random/mtrand/mtrand.c: In function '__Pyx_ParseOptionalKeyw\n             ords':\n     4579    numpy/random/mtrand/mtrand.c:45175:21: warning: '_PyUnicode_get_ws",
    "6m4utiyrsvuxwx2ytcv7sd3g35si6/include/python3.9/cpython/unicodeobj\n             ect.h:446:26: note: declared here\n     4685      446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObje\n             ct *op) {\n     4686          |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~\n     4687    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionSave':\n>> 4688    numpy/random/mtrand/mtrand.c:45472:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4689    45472 |     *type = tstate->exc_type;\n     4690          |                     ^~~~~~~~\n     4691          |                     curexc_type\n  >> 4692    numpy/random/mtrand/mtrand.c:45473:22: error: 'PyThreadState' {aka",
    ">> 4688    numpy/random/mtrand/mtrand.c:45472:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4689    45472 |     *type = tstate->exc_type;\n     4690          |                     ^~~~~~~~\n     4691          |                     curexc_type\n>> 4692    numpy/random/mtrand/mtrand.c:45473:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4693    45473 |     *value = tstate->exc_value;\n     4694          |                      ^~~~~~~~~\n     4695          |                      curexc_value\n  >> 4696    numpy/random/mtrand/mtrand.c:45474:19: error: 'PyThreadState' {aka",
    ">> 4692    numpy/random/mtrand/mtrand.c:45473:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4693    45473 |     *value = tstate->exc_value;\n     4694          |                      ^~~~~~~~~\n     4695          |                      curexc_value\n>> 4696    numpy/random/mtrand/mtrand.c:45474:19: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4697    45474 |     *tb = tstate->exc_traceback;\n     4698          |                   ^~~~~~~~~~~~~\n     4699          |                   curexc_traceback\n     4700    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4697    45474 |     *tb = tstate->exc_traceback;\n     4698          |                   ^~~~~~~~~~~~~\n     4699          |                   curexc_traceback\n     4700    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':\n>> 4701    numpy/random/mtrand/mtrand.c:45481:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4702    45481 |     tmp_type = tstate->exc_type;\n     4703          |                        ^~~~~~~~\n     4704          |                        curexc_type\n  >> 4705    numpy/random/mtrand/mtrand.c:45482:25: error: 'PyThreadState' {aka",
    ">> 4701    numpy/random/mtrand/mtrand.c:45481:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4702    45481 |     tmp_type = tstate->exc_type;\n     4703          |                        ^~~~~~~~\n     4704          |                        curexc_type\n>> 4705    numpy/random/mtrand/mtrand.c:45482:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4706    45482 |     tmp_value = tstate->exc_value;\n     4707          |                         ^~~~~~~~~\n     4708          |                         curexc_value\n  >> 4709    numpy/random/mtrand/mtrand.c:45483:22: error: 'PyThreadState' {aka",
    ">> 4705    numpy/random/mtrand/mtrand.c:45482:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4706    45482 |     tmp_value = tstate->exc_value;\n     4707          |                         ^~~~~~~~~\n     4708          |                         curexc_value\n>> 4709    numpy/random/mtrand/mtrand.c:45483:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4710    45483 |     tmp_tb = tstate->exc_traceback;\n     4711          |                      ^~~~~~~~~~~~~\n     4712          |                      curexc_traceback\n  >> 4713    numpy/random/mtrand/mtrand.c:45484:13: error: 'PyThreadState' {aka",
    ">> 4709    numpy/random/mtrand/mtrand.c:45483:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4710    45483 |     tmp_tb = tstate->exc_traceback;\n     4711          |                      ^~~~~~~~~~~~~\n     4712          |                      curexc_traceback\n>> 4713    numpy/random/mtrand/mtrand.c:45484:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4714    45484 |     tstate->exc_type = type;\n     4715          |             ^~~~~~~~\n     4716          |             curexc_type\n  >> 4717    numpy/random/mtrand/mtrand.c:45485:13: error: 'PyThreadState' {aka",
    ">> 4713    numpy/random/mtrand/mtrand.c:45484:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4714    45484 |     tstate->exc_type = type;\n     4715          |             ^~~~~~~~\n     4716          |             curexc_type\n>> 4717    numpy/random/mtrand/mtrand.c:45485:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4718    45485 |     tstate->exc_value = value;\n     4719          |             ^~~~~~~~~\n     4720          |             curexc_value\n  >> 4721    numpy/random/mtrand/mtrand.c:45486:13: error: 'PyThreadState' {aka",
    ">> 4717    numpy/random/mtrand/mtrand.c:45485:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4718    45485 |     tstate->exc_value = value;\n     4719          |             ^~~~~~~~~\n     4720          |             curexc_value\n>> 4721    numpy/random/mtrand/mtrand.c:45486:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4722    45486 |     tstate->exc_traceback = tb;\n     4723          |             ^~~~~~~~~~~~~\n     4724          |             curexc_traceback\n     4725    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4722    45486 |     tstate->exc_traceback = tb;\n     4723          |             ^~~~~~~~~~~~~\n     4724          |             curexc_traceback\n     4725    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':\n>> 4726    numpy/random/mtrand/mtrand.c:45541:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4727    45541 |     tmp_type = tstate->exc_type;\n     4728          |                        ^~~~~~~~\n     4729          |                        curexc_type\n  >> 4730    numpy/random/mtrand/mtrand.c:45542:25: error: 'PyThreadState' {aka",
    ">> 4726    numpy/random/mtrand/mtrand.c:45541:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4727    45541 |     tmp_type = tstate->exc_type;\n     4728          |                        ^~~~~~~~\n     4729          |                        curexc_type\n>> 4730    numpy/random/mtrand/mtrand.c:45542:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4731    45542 |     tmp_value = tstate->exc_value;\n     4732          |                         ^~~~~~~~~\n     4733          |                         curexc_value\n  >> 4734    numpy/random/mtrand/mtrand.c:45543:22: error: 'PyThreadState' {aka",
    ">> 4730    numpy/random/mtrand/mtrand.c:45542:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4731    45542 |     tmp_value = tstate->exc_value;\n     4732          |                         ^~~~~~~~~\n     4733          |                         curexc_value\n>> 4734    numpy/random/mtrand/mtrand.c:45543:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4735    45543 |     tmp_tb = tstate->exc_traceback;\n     4736          |                      ^~~~~~~~~~~~~\n     4737          |                      curexc_traceback\n  >> 4738    numpy/random/mtrand/mtrand.c:45544:13: error: 'PyThreadState' {aka",
    ">> 4734    numpy/random/mtrand/mtrand.c:45543:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4735    45543 |     tmp_tb = tstate->exc_traceback;\n     4736          |                      ^~~~~~~~~~~~~\n     4737          |                      curexc_traceback\n>> 4738    numpy/random/mtrand/mtrand.c:45544:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4739    45544 |     tstate->exc_type = local_type;\n     4740          |             ^~~~~~~~\n     4741          |             curexc_type\n  >> 4742    numpy/random/mtrand/mtrand.c:45545:13: error: 'PyThreadState' {aka",
    ">> 4738    numpy/random/mtrand/mtrand.c:45544:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4739    45544 |     tstate->exc_type = local_type;\n     4740          |             ^~~~~~~~\n     4741          |             curexc_type\n>> 4742    numpy/random/mtrand/mtrand.c:45545:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4743    45545 |     tstate->exc_value = local_value;\n     4744          |             ^~~~~~~~~\n     4745          |             curexc_value\n  >> 4746    numpy/random/mtrand/mtrand.c:45546:13: error: 'PyThreadState' {aka",
    ">> 4742    numpy/random/mtrand/mtrand.c:45545:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4743    45545 |     tstate->exc_value = local_value;\n     4744          |             ^~~~~~~~~\n     4745          |             curexc_value\n>> 4746    numpy/random/mtrand/mtrand.c:45546:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4747    45546 |     tstate->exc_traceback = local_tb;\n     4748          |             ^~~~~~~~~~~~~\n     4749          |             curexc_traceback\n  >> 4750    error: Command \"/p/vast1/koparasy/BUILD/head/spack/lib/spack/env/g",
    "y/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inump\n             y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/py-warpx/spack_env_dir/linux-rhel\n             7-broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxwx2ytcv7sd3g35si\n             6/include/python3.9 -c'\n     869     gcc: _configtest.c\n870     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     871         3 | #pragma clang diagnostic error \"-Wattributes\"\n     872           |\n     873     _configtest.c: In function '__declspec':\n  >> 874     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'",
    "875         5 | int __declspec(thread) foo;\n     876           |                        ^~~\n  >> 877     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     878         9 | {\n     879           | ^\n880     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     881         5 | int __declspec(thread) foo;\n     882           |     ^~~~~~~~~~\n  >> 883     _configtest.c:11: error: expected '{' at end of input\n     884        11 | }\n     885           |",
    "implicit-int]\n     881         5 | int __declspec(thread) foo;\n     882           |     ^~~~~~~~~~\n  >> 883     _configtest.c:11: error: expected '{' at end of input\n     884        11 | }\n     885           |\n886     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     887        11 | }\n     888           |\n     889     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     890         3 | #pragma clang diagnostic error \"-Wattributes\"",
    "884        11 | }\n     885           |\n     886     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     887        11 | }\n     888           |\n889     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     890         3 | #pragma clang diagnostic error \"-Wattributes\"\n     891           |\n     892     _configtest.c: In function '__declspec':\n  >> 893     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'",
    "894         5 | int __declspec(thread) foo;\n     895           |                        ^~~\n  >> 896     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     897         9 | {\n     898           | ^\n899     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     900         5 | int __declspec(thread) foo;\n     901           |     ^~~~~~~~~~\n  >> 902     _configtest.c:11: error: expected '{' at end of input\n     903        11 | }\n     904           |",
    "implicit-int]\n     900         5 | int __declspec(thread) foo;\n     901           |     ^~~~~~~~~~\n  >> 902     _configtest.c:11: error: expected '{' at end of input\n     903        11 | }\n     904           |\n905     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     906        11 | }\n     907           |\n     908     failure.\n\n     ...",
    ">> 4399    numpy/random/mtrand/mtrand.c:43644:33: error: 'PyTypeObject' {aka\n             'struct _typeobject'} has no member named 'tp_print'\n     4400    43644 |   __pyx_type_6mtrand_RandomState.tp_print = 0;\n     4401          |                                 ^\n     4402    numpy/random/mtrand/mtrand.c: In function '__Pyx_ParseOptionalKeyw\n             ords':\n4403    numpy/random/mtrand/mtrand.c:45175:21: warning: '_PyUnicode_get_ws\n             tr_length' is deprecated [-Wdeprecated-declarations]\n     4404    45175 |                     (PyUnicode_GET_SIZE(**name) != PyUnico\n             de_GET_SIZE(key)) ? 1 :\n     4405          |                     ^\n\n     ...",
    ">> 4575    numpy/random/mtrand/mtrand.c:43644:33: error: 'PyTypeObject' {aka\n             'struct _typeobject'} has no member named 'tp_print'\n     4576    43644 |   __pyx_type_6mtrand_RandomState.tp_print = 0;\n     4577          |                                 ^\n     4578    numpy/random/mtrand/mtrand.c: In function '__Pyx_ParseOptionalKeyw\n             ords':\n4579    numpy/random/mtrand/mtrand.c:45175:21: warning: '_PyUnicode_get_ws\n             tr_length' is deprecated [-Wdeprecated-declarations]\n     4580    45175 |                     (PyUnicode_GET_SIZE(**name) != PyUnico\n             de_GET_SIZE(key)) ? 1 :\n     4581          |                     ^\n\n     ...",
    "st.o -o _configtest\n     115     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 116     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.2-idultfc7vj5o\n             57xh25muozpbqgzn4xll/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 117     collect2: error: ld returned 1 exit status\n     118     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 119     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.2-idultfc7vj5o\n             57xh25muozpbqgzn4xll/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 120     collect2: error: ld returned 1 exit status",
    ">> 117     collect2: error: ld returned 1 exit status\n     118     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 119     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.2-idultfc7vj5o\n             57xh25muozpbqgzn4xll/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 120     collect2: error: ld returned 1 exit status\n     121     failure.\n     122     removing: _configtest.c _configtest.o\n     123     C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     124",
    "y/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inump\n             y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/py-warpx/spack_env_dir/linux-rhel\n             7-broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxwx2ytcv7sd3g35si\n             6/include/python3.9 -c'\n     173     gcc: _configtest.c\n>> 174     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory\n     175         1 | #include <sys/endian.h>\n     176           |          ^~~~~~~~~~~~~~\n     177     compilation terminated.\n  >> 178     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory",
    "173     gcc: _configtest.c\n  >> 174     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory\n     175         1 | #include <sys/endian.h>\n     176           |          ^~~~~~~~~~~~~~\n     177     compilation terminated.\n>> 178     _configtest.c:1:10: fatal error: sys/endian.h: No such file or dir\n             ectory\n     179         1 | #include <sys/endian.h>\n     180           |          ^~~~~~~~~~~~~~\n     181     compilation terminated.\n     182     failure.\n     183     removing: _configtest.c _configtest.o",
    "y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/py-warpx/spack_env_dir/linux-rhel\n             7-broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxwx2ytcv7sd3g35si\n             6/include/python3.9 -c'\n     289     gcc: _configtest.c\n     290     _configtest.c: In function 'main':\n>> 291     _configtest.c:7:12: error: 'SIZEOF_LONGDOUBLE' undeclared (first u\n             se in this function); did you mean 'SIZEOF_LONG_DOUBLE'?\n     292         7 |     (void) SIZEOF_LONGDOUBLE;\n     293           |            ^~~~~~~~~~~~~~~~~\n     294           |            SIZEOF_LONG_DOUBLE\n     295     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "292         7 |     (void) SIZEOF_LONGDOUBLE;\n     293           |            ^~~~~~~~~~~~~~~~~\n     294           |            SIZEOF_LONG_DOUBLE\n     295     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in\n     296     _configtest.c: In function 'main':\n>> 297     _configtest.c:7:12: error: 'SIZEOF_LONGDOUBLE' undeclared (first u\n             se in this function); did you mean 'SIZEOF_LONG_DOUBLE'?\n     298         7 |     (void) SIZEOF_LONGDOUBLE;\n     299           |            ^~~~~~~~~~~~~~~~~\n     300           |            SIZEOF_LONG_DOUBLE\n     301     _configtest.c:7:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "st.o -o _configtest\n     435     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 436     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.2-idultfc7vj5o\n             57xh25muozpbqgzn4xll/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 437     collect2: error: ld returned 1 exit status\n     438     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 439     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.2-idultfc7vj5o\n             57xh25muozpbqgzn4xll/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 440     collect2: error: ld returned 1 exit status",
    ">> 437     collect2: error: ld returned 1 exit status\n     438     /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 439     /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.2-idultfc7vj5o\n             57xh25muozpbqgzn4xll/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 440     collect2: error: ld returned 1 exit status\n     441     failure.\n     442     removing: _configtest.c _configtest.o\n     443     C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     444",
    "869     gcc: _configtest.c\n     870     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     871         3 | #pragma clang diagnostic error \"-Wattributes\"\n     872           |\n     873     _configtest.c: In function '__declspec':\n>> 874     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     875         5 | int __declspec(thread) foo;\n     876           |                        ^~~\n  >> 877     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     878         9 | {",
    "872           |\n     873     _configtest.c: In function '__declspec':\n  >> 874     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     875         5 | int __declspec(thread) foo;\n     876           |                        ^~~\n>> 877     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     878         9 | {\n     879           | ^\n     880     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     881         5 | int __declspec(thread) foo;",
    "878         9 | {\n     879           | ^\n     880     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     881         5 | int __declspec(thread) foo;\n     882           |     ^~~~~~~~~~\n>> 883     _configtest.c:11: error: expected '{' at end of input\n     884        11 | }\n     885           |\n     886     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     887        11 | }\n     888           |",
    "888           |\n     889     _configtest.c:3: warning: ignoring #pragma clang diagnostic [-Wunk\n             nown-pragmas]\n     890         3 | #pragma clang diagnostic error \"-Wattributes\"\n     891           |\n     892     _configtest.c: In function '__declspec':\n>> 893     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     894         5 | int __declspec(thread) foo;\n     895           |                        ^~~\n  >> 896     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     897         9 | {",
    "891           |\n     892     _configtest.c: In function '__declspec':\n  >> 893     _configtest.c:5:24: error: expected declaration specifiers before\n             'foo'\n     894         5 | int __declspec(thread) foo;\n     895           |                        ^~~\n>> 896     _configtest.c:9:1: error: expected '=', ',', ';', 'asm' or '__attr\n             ibute__' before '{' token\n     897         9 | {\n     898           | ^\n     899     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     900         5 | int __declspec(thread) foo;",
    "897         9 | {\n     898           | ^\n     899     _configtest.c:5:5: warning: type of 'thread' defaults to 'int' [-W\n             implicit-int]\n     900         5 | int __declspec(thread) foo;\n     901           |     ^~~~~~~~~~\n>> 902     _configtest.c:11: error: expected '{' at end of input\n     903        11 | }\n     904           |\n     905     _configtest.c:11: warning: control reaches end of non-void functio\n             n [-Wreturn-type]\n     906        11 | }\n     907           |",
    "y/core/src/umath -Inumpy/core/src/npysort -I/p/vast1/koparasy/BUIL\n             D/spack_cluster_installer/quartz/py-warpx/spack_env_dir/linux-rhel\n             7-broadwell/gcc-9.3.1/python-3.9.9-3o76m4utiyrsvuxwx2ytcv7sd3g35si\n             6/include/python3.9 -c'\n     1235    gcc: _configtest.c\n     1236    _configtest.c: In function 'main':\n>> 1237    _configtest.c:8:12: error: 'HAVE_DECL_SIGNBIT' undeclared (first u\n             se in this function); did you mean 'HAVE_DECL_ISNAN'?\n     1238        8 |     (void) HAVE_DECL_SIGNBIT;\n     1239          |            ^~~~~~~~~~~~~~~~~\n     1240          |            HAVE_DECL_ISNAN\n     1241    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "1238        8 |     (void) HAVE_DECL_SIGNBIT;\n     1239          |            ^~~~~~~~~~~~~~~~~\n     1240          |            HAVE_DECL_ISNAN\n     1241    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in\n     1242    _configtest.c: In function 'main':\n>> 1243    _configtest.c:8:12: error: 'HAVE_DECL_SIGNBIT' undeclared (first u\n             se in this function); did you mean 'HAVE_DECL_ISNAN'?\n     1244        8 |     (void) HAVE_DECL_SIGNBIT;\n     1245          |            ^~~~~~~~~~~~~~~~~\n     1246          |            HAVE_DECL_ISNAN\n     1247    _configtest.c:8:12: note: each undeclared identifier is reported o\n             nly once for each function it appears in",
    "st.o -o _configtest\n     1829    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1830    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.2-idultfc7vj5o\n             57xh25muozpbqgzn4xll/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 1831    collect2: error: ld returned 1 exit status\n     1832    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1833    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.2-idultfc7vj5o\n             57xh25muozpbqgzn4xll/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n  >> 1834    collect2: error: ld returned 1 exit status",
    ">> 1831    collect2: error: ld returned 1 exit status\n     1832    /usr/tce/packages/gcc/gcc-9.3.1/rh/usr/bin/../libexec/gcc/x86_64-r\n             edhat-linux/9/ld: _configtest.o: in function `main':\n  >> 1833    /tmp/koparasy/spack-stage/spack-stage-py-numpy-1.14.2-idultfc7vj5o\n             57xh25muozpbqgzn4xll/spack-src/_configtest.c:6: undefined referenc\n             e to `exp'\n>> 1834    collect2: error: ld returned 1 exit status\n     1835    failure.\n     1836    removing: _configtest.c _configtest.o\n     1837    C compiler: /p/vast1/koparasy/BUILD/head/spack/lib/spack/env/gcc/g\n             cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall\n              -fPIC -fPIC\n     1838",
    "ath -Ibuild/src.linux-x86_64-3.9/numpy/core/src/private -Ibuild/sr\n             c.linux-x86_64-3.9/numpy/core/src/npymath -Ibuild/src.linux-x86_64\n             -3.9/numpy/core/src/private -Ibuild/src.linux-x86_64-3.9/numpy/cor\n             e/src/npymath -c'\n     4397    gcc: numpy/random/mtrand/mtrand.c\n     4398    numpy/random/mtrand/mtrand.c: In function 'PyInit_mtrand':\n>> 4399    numpy/random/mtrand/mtrand.c:43644:33: error: 'PyTypeObject' {aka\n             'struct _typeobject'} has no member named 'tp_print'\n     4400    43644 |   __pyx_type_6mtrand_RandomState.tp_print = 0;\n     4401          |                                 ^\n     4402    numpy/random/mtrand/mtrand.c: In function '__Pyx_ParseOptionalKeyw\n             ords':\n     4403    numpy/random/mtrand/mtrand.c:45175:21: warning: '_PyUnicode_get_ws",
    "yrsvuxwx2ytcv7sd3g35si6/include/python3.9/cpython/unicodeobject.h:\n             446:26: note: declared here\n     4509      446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObje\n             ct *op) {\n     4510          |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~\n     4511    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionSave':\n>> 4512    numpy/random/mtrand/mtrand.c:45472:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4513    45472 |     *type = tstate->exc_type;\n     4514          |                     ^~~~~~~~\n     4515          |                     curexc_type\n  >> 4516    numpy/random/mtrand/mtrand.c:45473:22: error: 'PyThreadState' {aka",
    ">> 4512    numpy/random/mtrand/mtrand.c:45472:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4513    45472 |     *type = tstate->exc_type;\n     4514          |                     ^~~~~~~~\n     4515          |                     curexc_type\n>> 4516    numpy/random/mtrand/mtrand.c:45473:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4517    45473 |     *value = tstate->exc_value;\n     4518          |                      ^~~~~~~~~\n     4519          |                      curexc_value\n  >> 4520    numpy/random/mtrand/mtrand.c:45474:19: error: 'PyThreadState' {aka",
    ">> 4516    numpy/random/mtrand/mtrand.c:45473:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4517    45473 |     *value = tstate->exc_value;\n     4518          |                      ^~~~~~~~~\n     4519          |                      curexc_value\n>> 4520    numpy/random/mtrand/mtrand.c:45474:19: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4521    45474 |     *tb = tstate->exc_traceback;\n     4522          |                   ^~~~~~~~~~~~~\n     4523          |                   curexc_traceback\n     4524    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4521    45474 |     *tb = tstate->exc_traceback;\n     4522          |                   ^~~~~~~~~~~~~\n     4523          |                   curexc_traceback\n     4524    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':\n>> 4525    numpy/random/mtrand/mtrand.c:45481:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4526    45481 |     tmp_type = tstate->exc_type;\n     4527          |                        ^~~~~~~~\n     4528          |                        curexc_type\n  >> 4529    numpy/random/mtrand/mtrand.c:45482:25: error: 'PyThreadState' {aka",
    ">> 4525    numpy/random/mtrand/mtrand.c:45481:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4526    45481 |     tmp_type = tstate->exc_type;\n     4527          |                        ^~~~~~~~\n     4528          |                        curexc_type\n>> 4529    numpy/random/mtrand/mtrand.c:45482:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4530    45482 |     tmp_value = tstate->exc_value;\n     4531          |                         ^~~~~~~~~\n     4532          |                         curexc_value\n  >> 4533    numpy/random/mtrand/mtrand.c:45483:22: error: 'PyThreadState' {aka",
    ">> 4529    numpy/random/mtrand/mtrand.c:45482:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4530    45482 |     tmp_value = tstate->exc_value;\n     4531          |                         ^~~~~~~~~\n     4532          |                         curexc_value\n>> 4533    numpy/random/mtrand/mtrand.c:45483:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4534    45483 |     tmp_tb = tstate->exc_traceback;\n     4535          |                      ^~~~~~~~~~~~~\n     4536          |                      curexc_traceback\n  >> 4537    numpy/random/mtrand/mtrand.c:45484:13: error: 'PyThreadState' {aka",
    ">> 4533    numpy/random/mtrand/mtrand.c:45483:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4534    45483 |     tmp_tb = tstate->exc_traceback;\n     4535          |                      ^~~~~~~~~~~~~\n     4536          |                      curexc_traceback\n>> 4537    numpy/random/mtrand/mtrand.c:45484:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4538    45484 |     tstate->exc_type = type;\n     4539          |             ^~~~~~~~\n     4540          |             curexc_type\n  >> 4541    numpy/random/mtrand/mtrand.c:45485:13: error: 'PyThreadState' {aka",
    ">> 4537    numpy/random/mtrand/mtrand.c:45484:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4538    45484 |     tstate->exc_type = type;\n     4539          |             ^~~~~~~~\n     4540          |             curexc_type\n>> 4541    numpy/random/mtrand/mtrand.c:45485:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4542    45485 |     tstate->exc_value = value;\n     4543          |             ^~~~~~~~~\n     4544          |             curexc_value\n  >> 4545    numpy/random/mtrand/mtrand.c:45486:13: error: 'PyThreadState' {aka",
    ">> 4541    numpy/random/mtrand/mtrand.c:45485:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4542    45485 |     tstate->exc_value = value;\n     4543          |             ^~~~~~~~~\n     4544          |             curexc_value\n>> 4545    numpy/random/mtrand/mtrand.c:45486:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4546    45486 |     tstate->exc_traceback = tb;\n     4547          |             ^~~~~~~~~~~~~\n     4548          |             curexc_traceback\n     4549    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4546    45486 |     tstate->exc_traceback = tb;\n     4547          |             ^~~~~~~~~~~~~\n     4548          |             curexc_traceback\n     4549    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':\n>> 4550    numpy/random/mtrand/mtrand.c:45541:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4551    45541 |     tmp_type = tstate->exc_type;\n     4552          |                        ^~~~~~~~\n     4553          |                        curexc_type\n  >> 4554    numpy/random/mtrand/mtrand.c:45542:25: error: 'PyThreadState' {aka",
    ">> 4550    numpy/random/mtrand/mtrand.c:45541:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4551    45541 |     tmp_type = tstate->exc_type;\n     4552          |                        ^~~~~~~~\n     4553          |                        curexc_type\n>> 4554    numpy/random/mtrand/mtrand.c:45542:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4555    45542 |     tmp_value = tstate->exc_value;\n     4556          |                         ^~~~~~~~~\n     4557          |                         curexc_value\n  >> 4558    numpy/random/mtrand/mtrand.c:45543:22: error: 'PyThreadState' {aka",
    ">> 4554    numpy/random/mtrand/mtrand.c:45542:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4555    45542 |     tmp_value = tstate->exc_value;\n     4556          |                         ^~~~~~~~~\n     4557          |                         curexc_value\n>> 4558    numpy/random/mtrand/mtrand.c:45543:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4559    45543 |     tmp_tb = tstate->exc_traceback;\n     4560          |                      ^~~~~~~~~~~~~\n     4561          |                      curexc_traceback\n  >> 4562    numpy/random/mtrand/mtrand.c:45544:13: error: 'PyThreadState' {aka",
    ">> 4558    numpy/random/mtrand/mtrand.c:45543:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4559    45543 |     tmp_tb = tstate->exc_traceback;\n     4560          |                      ^~~~~~~~~~~~~\n     4561          |                      curexc_traceback\n>> 4562    numpy/random/mtrand/mtrand.c:45544:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4563    45544 |     tstate->exc_type = local_type;\n     4564          |             ^~~~~~~~\n     4565          |             curexc_type\n  >> 4566    numpy/random/mtrand/mtrand.c:45545:13: error: 'PyThreadState' {aka",
    ">> 4562    numpy/random/mtrand/mtrand.c:45544:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4563    45544 |     tstate->exc_type = local_type;\n     4564          |             ^~~~~~~~\n     4565          |             curexc_type\n>> 4566    numpy/random/mtrand/mtrand.c:45545:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4567    45545 |     tstate->exc_value = local_value;\n     4568          |             ^~~~~~~~~\n     4569          |             curexc_value\n  >> 4570    numpy/random/mtrand/mtrand.c:45546:13: error: 'PyThreadState' {aka",
    ">> 4566    numpy/random/mtrand/mtrand.c:45545:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4567    45545 |     tstate->exc_value = local_value;\n     4568          |             ^~~~~~~~~\n     4569          |             curexc_value\n>> 4570    numpy/random/mtrand/mtrand.c:45546:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4571    45546 |     tstate->exc_traceback = local_tb;\n     4572          |             ^~~~~~~~~~~~~\n     4573          |             curexc_traceback\n     4574    numpy/random/mtrand/mtrand.c: In function 'PyInit_mtrand':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4571    45546 |     tstate->exc_traceback = local_tb;\n     4572          |             ^~~~~~~~~~~~~\n     4573          |             curexc_traceback\n     4574    numpy/random/mtrand/mtrand.c: In function 'PyInit_mtrand':\n>> 4575    numpy/random/mtrand/mtrand.c:43644:33: error: 'PyTypeObject' {aka\n             'struct _typeobject'} has no member named 'tp_print'\n     4576    43644 |   __pyx_type_6mtrand_RandomState.tp_print = 0;\n     4577          |                                 ^\n     4578    numpy/random/mtrand/mtrand.c: In function '__Pyx_ParseOptionalKeyw\n             ords':\n     4579    numpy/random/mtrand/mtrand.c:45175:21: warning: '_PyUnicode_get_ws",
    "yrsvuxwx2ytcv7sd3g35si6/include/python3.9/cpython/unicodeobject.h:\n             446:26: note: declared here\n     4685      446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObje\n             ct *op) {\n     4686          |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~\n     4687    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionSave':\n>> 4688    numpy/random/mtrand/mtrand.c:45472:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4689    45472 |     *type = tstate->exc_type;\n     4690          |                     ^~~~~~~~\n     4691          |                     curexc_type\n  >> 4692    numpy/random/mtrand/mtrand.c:45473:22: error: 'PyThreadState' {aka",
    ">> 4688    numpy/random/mtrand/mtrand.c:45472:21: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4689    45472 |     *type = tstate->exc_type;\n     4690          |                     ^~~~~~~~\n     4691          |                     curexc_type\n>> 4692    numpy/random/mtrand/mtrand.c:45473:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4693    45473 |     *value = tstate->exc_value;\n     4694          |                      ^~~~~~~~~\n     4695          |                      curexc_value\n  >> 4696    numpy/random/mtrand/mtrand.c:45474:19: error: 'PyThreadState' {aka",
    ">> 4692    numpy/random/mtrand/mtrand.c:45473:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4693    45473 |     *value = tstate->exc_value;\n     4694          |                      ^~~~~~~~~\n     4695          |                      curexc_value\n>> 4696    numpy/random/mtrand/mtrand.c:45474:19: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4697    45474 |     *tb = tstate->exc_traceback;\n     4698          |                   ^~~~~~~~~~~~~\n     4699          |                   curexc_traceback\n     4700    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4697    45474 |     *tb = tstate->exc_traceback;\n     4698          |                   ^~~~~~~~~~~~~\n     4699          |                   curexc_traceback\n     4700    numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':\n>> 4701    numpy/random/mtrand/mtrand.c:45481:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4702    45481 |     tmp_type = tstate->exc_type;\n     4703          |                        ^~~~~~~~\n     4704          |                        curexc_type\n  >> 4705    numpy/random/mtrand/mtrand.c:45482:25: error: 'PyThreadState' {aka",
    ">> 4701    numpy/random/mtrand/mtrand.c:45481:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4702    45481 |     tmp_type = tstate->exc_type;\n     4703          |                        ^~~~~~~~\n     4704          |                        curexc_type\n>> 4705    numpy/random/mtrand/mtrand.c:45482:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4706    45482 |     tmp_value = tstate->exc_value;\n     4707          |                         ^~~~~~~~~\n     4708          |                         curexc_value\n  >> 4709    numpy/random/mtrand/mtrand.c:45483:22: error: 'PyThreadState' {aka",
    ">> 4705    numpy/random/mtrand/mtrand.c:45482:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4706    45482 |     tmp_value = tstate->exc_value;\n     4707          |                         ^~~~~~~~~\n     4708          |                         curexc_value\n>> 4709    numpy/random/mtrand/mtrand.c:45483:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4710    45483 |     tmp_tb = tstate->exc_traceback;\n     4711          |                      ^~~~~~~~~~~~~\n     4712          |                      curexc_traceback\n  >> 4713    numpy/random/mtrand/mtrand.c:45484:13: error: 'PyThreadState' {aka",
    ">> 4709    numpy/random/mtrand/mtrand.c:45483:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4710    45483 |     tmp_tb = tstate->exc_traceback;\n     4711          |                      ^~~~~~~~~~~~~\n     4712          |                      curexc_traceback\n>> 4713    numpy/random/mtrand/mtrand.c:45484:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4714    45484 |     tstate->exc_type = type;\n     4715          |             ^~~~~~~~\n     4716          |             curexc_type\n  >> 4717    numpy/random/mtrand/mtrand.c:45485:13: error: 'PyThreadState' {aka",
    ">> 4713    numpy/random/mtrand/mtrand.c:45484:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4714    45484 |     tstate->exc_type = type;\n     4715          |             ^~~~~~~~\n     4716          |             curexc_type\n>> 4717    numpy/random/mtrand/mtrand.c:45485:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4718    45485 |     tstate->exc_value = value;\n     4719          |             ^~~~~~~~~\n     4720          |             curexc_value\n  >> 4721    numpy/random/mtrand/mtrand.c:45486:13: error: 'PyThreadState' {aka",
    ">> 4717    numpy/random/mtrand/mtrand.c:45485:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4718    45485 |     tstate->exc_value = value;\n     4719          |             ^~~~~~~~~\n     4720          |             curexc_value\n>> 4721    numpy/random/mtrand/mtrand.c:45486:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4722    45486 |     tstate->exc_traceback = tb;\n     4723          |             ^~~~~~~~~~~~~\n     4724          |             curexc_traceback\n     4725    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':",
    "'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4722    45486 |     tstate->exc_traceback = tb;\n     4723          |             ^~~~~~~~~~~~~\n     4724          |             curexc_traceback\n     4725    numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':\n>> 4726    numpy/random/mtrand/mtrand.c:45541:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4727    45541 |     tmp_type = tstate->exc_type;\n     4728          |                        ^~~~~~~~\n     4729          |                        curexc_type\n  >> 4730    numpy/random/mtrand/mtrand.c:45542:25: error: 'PyThreadState' {aka",
    ">> 4726    numpy/random/mtrand/mtrand.c:45541:24: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4727    45541 |     tmp_type = tstate->exc_type;\n     4728          |                        ^~~~~~~~\n     4729          |                        curexc_type\n>> 4730    numpy/random/mtrand/mtrand.c:45542:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4731    45542 |     tmp_value = tstate->exc_value;\n     4732          |                         ^~~~~~~~~\n     4733          |                         curexc_value\n  >> 4734    numpy/random/mtrand/mtrand.c:45543:22: error: 'PyThreadState' {aka",
    ">> 4730    numpy/random/mtrand/mtrand.c:45542:25: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4731    45542 |     tmp_value = tstate->exc_value;\n     4732          |                         ^~~~~~~~~\n     4733          |                         curexc_value\n>> 4734    numpy/random/mtrand/mtrand.c:45543:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4735    45543 |     tmp_tb = tstate->exc_traceback;\n     4736          |                      ^~~~~~~~~~~~~\n     4737          |                      curexc_traceback\n  >> 4738    numpy/random/mtrand/mtrand.c:45544:13: error: 'PyThreadState' {aka",
    ">> 4734    numpy/random/mtrand/mtrand.c:45543:22: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4735    45543 |     tmp_tb = tstate->exc_traceback;\n     4736          |                      ^~~~~~~~~~~~~\n     4737          |                      curexc_traceback\n>> 4738    numpy/random/mtrand/mtrand.c:45544:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4739    45544 |     tstate->exc_type = local_type;\n     4740          |             ^~~~~~~~\n     4741          |             curexc_type\n  >> 4742    numpy/random/mtrand/mtrand.c:45545:13: error: 'PyThreadState' {aka",
    ">> 4738    numpy/random/mtrand/mtrand.c:45544:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_type'; did you mean 'curex\n             c_type'?\n     4739    45544 |     tstate->exc_type = local_type;\n     4740          |             ^~~~~~~~\n     4741          |             curexc_type\n>> 4742    numpy/random/mtrand/mtrand.c:45545:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4743    45545 |     tstate->exc_value = local_value;\n     4744          |             ^~~~~~~~~\n     4745          |             curexc_value\n  >> 4746    numpy/random/mtrand/mtrand.c:45546:13: error: 'PyThreadState' {aka",
    ">> 4742    numpy/random/mtrand/mtrand.c:45545:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_value'; did you mean 'cure\n             xc_value'?\n     4743    45545 |     tstate->exc_value = local_value;\n     4744          |             ^~~~~~~~~\n     4745          |             curexc_value\n>> 4746    numpy/random/mtrand/mtrand.c:45546:13: error: 'PyThreadState' {aka\n              'struct _ts'} has no member named 'exc_traceback'; did you mean '\n             curexc_traceback'?\n     4747    45546 |     tstate->exc_traceback = local_tb;\n     4748          |             ^~~~~~~~~~~~~\n     4749          |             curexc_traceback\n  >> 4750    error: Command \"/p/vast1/koparasy/BUILD/head/spack/lib/spack/env/g"
]